var city_feature = [
    	"Six-headed gargoyle fountain",
        "Two huge feet, all that remains of a toppled statue",
        "Iron column 20 feet high",
        "Ancient, decaying elm tree",
        "Large bathing pool fed by lion-faced outflows",
        "Hot spring with a marble statue of a white dragon rising from its center",
        "Three bronze horsemen looking west",
        "Roadside shrine to a local saint",
        "Bust of the local mayor",
        "Gilded statue of the sun goddess",
        "A stone carving of the god of magic standing over 20 feet tall",
        "Black stone pyramid 10 feet high",
        "Huge weathered sphinx",
        "Line of 20 stylized stone faces",
        "Bronze colossus of the city’s patron god",
        "Marble statue commemorating a local hero, showing him on a chariot pulled by eight white chargers",
        "Fresco depicting a natural disaster",
        "Three trees intertwined to create a crude throne",
        "Golden orb on a plinth held aloft by stone rocs",
        "Ancient, weathered statue of a mysterious woman in otherrworldly garb",
        "Stone platform jutting from the roof of the tallest building from which criminals are thrown",
        "Small, bronze courtyard fountain",
        "Street fountain and watering trough",
        "Statue of a dwarf riding a griffon",
        "Washing fountain decorated with carved oak leaves",
        "Fountain held aloft by eight lions",
        "Alley with 100 fountains",
        "Fountain depicting six seahorses",
        "Weathered dolmen",
        "Sarcophagus carved with one-eyed crows",
        "Stone altar",
        "Marble statue of a scholar instructing a trio of admiring students",
        "Retired guillotine",
        "Large metal copy of a holy book; a novice turns the page each day with a key",
        "This city has a large Temple to a very minor deity.",
		"The South side of the city has a heavy Dwarven population and the West side has a large Halfling population.",
		"⁠There's a world famous bridge here that recently started falling down.",
		"⁠A famous University is in the city.",
		"A world renowned Academy is in this city.",
		"The most prestigious Military academy in the world is in this city.",
		"This city is famous for its rumored underground (figurative or literal) fight club.",
		"This city is world famous for its Apple Orchards",
		"This one for its coast line",
		"This one for its extremely strict laws regarding wine.",
		"This city is famous for its fashion trends.",
		"This one is famous for its gigantic horse drawn carriages.",
		"This city is well known for its dense population.",
		"This city is home to masterpieces of architecture.",
		"This one is known for its Opera House.",
		"The city is made specifically for creatures that can fly or levitate, and everything is elevated off the ground. However, nothing in the city is inaccessible to creatures that cannot fly, with ladders and staircases being the primary mode of access.",
		"Everything in the city is made to accommodate larger creatures.",
		"Everything is detailed with metal and stone due to its abundance of mining operations. As you may be able to guess, many dwarves reside in this city.",
		"This city is a human city amongst a wild land of Dragonborn tribes.",
		"These humans have become able to ride and domesticate dragons. In the city center there is a massive eyrie of dragons.",
		"There is a specific agricultural product which is common in the area around this city (spice, dye, wine, fruit, nut, vegetable) but is unavailable elsewhere due to the unique combination of climate, soil, rainfall and the difficulty of transporting fresh produce to other cities. The city has an annual festival celebrating the harvest of this product and its economic impact on the city.",
		"Since the mine shut down, this city has become a ghost town.",
		"This city is a tourist destination for those wishing to see the Great Crater of Isham for themselves.",
		"This city lies at the center of a contested land and has changed hands many times over a thousand years. It's architecture and inhabitants are incredibly diverse.",
		"This city lies at the center of a contested land and has changed hands many times over a thousand years. It's architecture and inhabitants are incredibly diverse.",
		"This city is made up of a labyrinthian system of tunnels and caves.",
		"You must cross a swamp to enter this city.",
		"This city is surrounded by tall mountains.",
		"This city is actually three cities that are separated by tributaries of a delta. Each city has grown so large they now are vying to expand either upward or outward. Each city is ruled by a different noble family that refuses to join into one city. Every time you cross a bridge, you have to pass through city gates that right now are charging a retaliation tariff over a recent dispute.",
		"The city is built over a humongous cave system. Many buildings have secret underground sections that almost nobody knows about.",
		"some creature with multiple personalities just chained up in the middle of the city.",
		"This city has a fruit tree in its centre that produce unusually large fruit. The type of fruit change each year.",
		"This city is know for its amazing murals painted all through out the city",
		"This city has had a resident that has lived there since its founding over 1500 years ago, she's an old human lady that still runs the same bakery that she opened a few years after the city founding. The bread there is delicious.",
		"The city has a very strict one dog per capita rule. No more, no less. Visitors are given guide dogs when they enter town and are required to keep them by their side at all times. The dogs carry their official paperwork and can lead them to the right place if they ask by name or type of item. 'Armor!' for the armor shop, for instance.",
		"The city has a strict curfew, because once the sun goes down, beautiful but ravenous pirahna-like fireflies appear everywhere throughout the streets, devouring any who step outside. It looks really pretty when it happens though.",
		"The city is home to people who never speak. If a word is spoken by somebody, everybody else stops what they're doing immediately, points at the person who spoke, and screams non-stop until a city guard comes and arrests the person.",
		"The city is only accessible by drawbridge. To enter, you must solve the gatemaster's puzzle: 'I haff tvelve metchsteek...'",
		"The city is populated primarily by wizards, with strange laws to match.",
		"The city is based around a pillar of floating azure marble.",
		"The city is covered in canals, the fish-folk of the city often have underwater entrances to their buildings",
		"The city has an incredibly tall pole. Nothing special about it, just very very very tall.",
		"The city's structures are built from the bones of titans long dead.",
		"The city is coastal and houses a large temple on the rocky shore with glass floors. The monks there study and worship the sea life they can view when the tides are high.",
		"The entire village is made up of friendly dopplegangers and house sized mimics",
		"A large river bisects the city, and there are two radicly different ideologies on either side",
		"A geyser/hot spring feeds hot water through complex aquaducts to small pools for bathing and drinking everywhere around the city",
		"The city rests in a crater that keeps it safe from the howling winds just above",
		"The city was built around an abandoned quary, with a massive, ominous dark crystal at its heart",
		"The city was built around the now retrofitted stronghold of a defeated lich",
		"The city was built on ancient druidic burial grounds, and hauntings are common",
		"Slave trading capital of the world. Currently facing abolitionists protests",
		"The city spirals down into obscurity and is entirely built on the inner walls of a vast natural cavern (or long dead volcano). Many bridges cross from one side to the other, and a few elevators are accessible to the top tier citizens.",
		"Rumors say that the nightmarish creatures sometimes creep up the walls to eat children during their sleep.",
		"The city is populated only by shapeshifted dragons.",
		"The city walls are made entirely of human bones and skulls.",
		"Though it appears normal from outside, once you step through the gate you realise that the city is set in permanent night.",
		"The city has the opposite meteorology from outside it's walls. If it is night out, it is day within; if the sun shines without, it is pouring within; hot outside, freezing in etc...",
		"The buildings consist only of circular towers.",
		"Everyone in the city goes around naked, and clothes are considered a perversion. Armour merely kinky.",
		"The city is known for its bard college and the regular literary festivals it holds.",
		"The city contains the largest library in the world.",
		"This city's residents are known to be annoyingly proud of where they come from - despite not being able to say exactly what they're proud of.",
		"This city's residents are known to complain about everything around them, but no one ever moves away.",
		"The city's founder will tell anyone who'll listen, 'When I first came here, this was all swamp. Everyone said I was daft to build a castlecity on a swamp, but I built it all the same, just to show them. It sank into the swamp. So I built a second one. And that one sank into the swamp. So I built a third. That burned down, fell over, and then sank into the swamp. But the fourth one stayed up.'",
		"The city has a large aqueduct from a nearby mountain, and several ornate fountains form the focal point for city squares.",
		"Every year near the end of Spring, a huge migration of songbirds turns the city into a riot of color and sound.",
		"The city is ancient. Having been around for centuries, it has been destroyed, rebuilt, and expanded several times. Beneath the ground are ruins of successively older buildings, artefacts, catacombs, and caverns.",
		"The city is a way station and major trade hub for horse trading, and the Great Bazaar meets every year in the summer. The city doubles in size and a forest of tents cover the plain outside as traders come from all over to buy, sell, haggle, and enter new contracts.",
		"Tall slender spires rise up from the city, as a complex network of messenger birds flit back and forth, allowing news and gossip to spread like wild fire. The birds roost in their high nests in the towers, tended by civil servants who only occasionally peruse the mail.",
		"The city has a smiling statue of its most famous export. Could be a fish, an apple, a bolt of silk... Whatever it is, it has a smiling face, arms and legs, and appears to be waving in greeting to all visitors.",
		"The catacombs below this city are famous for their non-euclidal corridors and constantly changing layout.",
		"The city is covered by a gigantic, man made dome and mighty pillars that support it. There is a small sun inside, covered by a multilayered clockwork sphere, creating a simple day and night cycle. The city even has It's own weather.",
		"Everyone who enters the city knows the main language perfectly. The main language changes every day. Nobody knows how or why, but nobody also really cares, because the city is now a fortress of some maniacal lich.",
		"Rivers of this city are magical water tunnels flowing through the air at different heights, from a few meters above the ground to even a kilometer. Most upper rivers are connected to a giant floating lake blob of water and aqutic fauna. Flying fish are the main food source and equivalent of pigeons. Except for landing to eat bread. And eating bread. They just float around the nearby plains looking for squirrels to eat.",
		"The city is mostly made out of hardened and detoxicated slime blocks. Fighters who live there are adept at fighting liquid creatures.",
		"The city uses undead creatures for unskilled labor such as carrying goods, courier services, pulling carts or plows, etc. Unemployment is a large problem because of this.",
		"The city is crisscrossed with dozens of canals. Locals transport goods, travel along, and even swim and draw water from these canals.",
		"The city is home to a series of hot springs that provide warm water to several great bath houses and the homes of the wealthier private citizens. It has become a tourist destination for many seeking rest and respite in the hot waters.",
		"The city streets are lined with flowering trees. Each spring the entire city blossoms, filling the air with sweet fragrances and a riot of color.",
		"The city is built in a deep crevasse between two large rocky hills. Due to the intense rainfall of the region and the high water table, these cliffs constantly stream water down them, creating a waterfall and river that surrounds the city. The city has even built every house on high stilts and stone platforms to keep everything dry. Once a night, the stream are diverted from around the city to through the city, washing away grime, muck, and litter.",
		"There is a well in the center of the city which grants one wish per year. Everyone is permitted one wish and at the height of the solstice one minor wish is granted.",
		"A man in a strange horseless carraige goes up and down the street seeking frozen milk products. He plays a strange tune the name of which no Bard can place.",
		"Residents of the town are addicted to carrying minor magical items that display nonsensical pictures, which they spread from person to person through unknown means. The items lose power if removed from the city for 24 hours.",
		"Home to a particularly large population of wild rabbits, no one knows how but they've managed to adapt to the urban street life like any stray dog or cat",
		"There's a duck statue in the city centre, artist unknown, it just appeared there overnight and has become a fixture since as the city has been unable to remove it, rumoured to be a prank played by a band of bards",
		"A fireworks factory with one too few walls",
		"This city has powerful wards from a time of legends.",
		"This city is built around the tower of a powerful wizard, no one knows if he is still alive.",
		"This city is at the intersection of several waylines, grating it a greet magical potential.",
		"This city was founded around a spring with powerful healing abilities.",
		"There is a monster that defends the city in exchange for food.",
		"At night the streets are lit by magical spheres.",
		"The buildings in the city centre very slowly change colour, it can take years to notice.",
		"The oldest buildings were there before the city, there architecture is alien and seamless.",
		"People buried in its graveyard sometimes comeback perfectly fine.",
		"The city is built on treetops of a large forest.",
		"The city is built on a high plateau, great bridges stretch downwards in every direction.",
		"The dead return as benevolent ghosts.",
		"The beer brewed here is praised throughout the land.",
		"The local guild of artificer is responsible for a new discovery.",
		"The city is a prosperous trade hub.",
		"The ruler has made medicine free to everyone.",
		"An ancient tree in its centre is cited in several religious texts.",
		"Bridges span between building, above the street.",
		"Metal is used heavily in construction.",
		"Most people own a swimming pool, its size is a status symbol.",
		"A fire burned down a chunk of the city town recently.",
		"The river that divides the city/town also divides a social rift between the two sides. Perhaps it's cultural, religion, economic etc.",
		"It appears to have a very angry/sad/mad/pleading wizard/nobal/child in the stocks. Why? Who knows?",
		"For one reason or another most of the populace has made insects their main source of food; the city is even renown for some of its bug infused dishes.",
		"The city has alcohol on tap",
		"This city is constantly moving. Be it by nomadic packing everything up and moving or as far as the city has been built onto massive moving machines. Think Mortal Engines but can be treads or wheels or even legs!",
		"The city has a 2 story tall, 1.5 mile long public bookshelf situated along it's southern wall.",
		"From above the city looks like a network of creeks, rivers, and swamps. That actually a complex water and sewage system for the city that lies beneath the swamp, protected from the dragons that are known to pillage the area.",
		"This dwarven city is surrounded by stone trees. each tree is actually an incredibly detailed statue created by a dwarven craftsman in order to prove their mastery.",
		"Abattoir: slaughterhouse",
		"Abbey: large religious building",
		"Alchemist: shop specializing in alchemical items",
		"Amphitheater: large open air stadium",
		"Apiary: collection of beehives for production of honey",
		"Apothecary: the business premises of a medical man",
		"Aqueduct: channel to move and deliver water",
		"Arboretum: garden for exotic plants",
		"Arena: stadium for sports and other entertainments",
		"Armory: military building housing weapons and armor",
		"Asylum: hospital for the treatment of the mentally ill",
		"Aviary: building housing rare or useful birds",
		"Baker: workroom or shop selling baked goods",
		"Bandstand: open-air stage for concerts",
		"Bank: secure building for the storage of valuables",
		"Barber: business offering haircutting and dentistry",
		"Barn: agricultural storage building",
		"Barracks: military building housing soldiers",
		"Basilica: religious meeting place",
		"Bazaar: type of market",
		"Bathhouse: building for public bathing and cleansing",
		"Blacksmith: shop for worked metal goods",
		"Brewery: building used to manufacture beer and ale",
		"Bridge: structure connecting two separate areas",
		"Brothel: building housing prostitutes",
		"Bullring: arena for bullfighting",
		"Butcher: workshop for the killing and cutting of meat",
		"Canal: man-made watercourse",
		"Carpenter: workshop where wood is worked",
		"Cartographer: shop where maps are sold",
		"Castle: large defensive structure",
		"Cathedral: huge center of worship",
		"Chapel: small religious building",
		"Church: place of worship",
		"Cistern: artificial reservoir",
		"Citadel: fortress for protecting a large settlement",
		"Coaching House: superior inn specializing in customers",
		"veling by coach",
		"Convent: religious establishment housing nuns",
		"Cottage: small residence",
		"Courthouse: official building for the judgement of law",
		"Crematorium: building for the disposal of dead bodies",
		"Distillery: building used to manufacture liquor and spirits",
		"Docks: point of embarkation and unloading for ships",
		"Dump: area for the disposal of garbage",
		"Drying Room: building used to dry fish, meat, and so on",
		"Embassy: official representative of a foreign nation",
		"Exchange: place where traders meet to buy and sell",
		"Flea Market: market specializing in secondhand goods",
		"Folly: building made purely for decorative purposes",
		"Forum: public meeting place",
		"Fortress: large fortified military building",
		"Gaol: prison or jail",
		"Garden: space for growing flowers, vegetables, and so on",
		"Gatehouse: defensive structure built around a gate",
		"Granary: storehouse for grain or animal feed",
		"Graveyard: place where the dead are buried",
		"Hippodrome: stadium for horse or chariot racing",
		"Hospice: guesthouse for travelers",
		"Hospital: place where the sick are treated",
		"Horse Mill: horse-powered mill for grinding grain",
		"Inn: house providing food and lodging",
		"Keep: defensive structure often built as part of a castle",
		"Library: building housing a collection of written texts",
		"Lighthouse: towering light used to warn ships of danger",
		"Longhouse: timber structure used as a meeting place",
		"Magic Shop: shop for the sale and trade of magic items",
		"Manor: large residential building",
		"Manse: large residential house",
		"Market Square: communal area for commerce",
		"Menagerie: collection of exotic animals",
		"Mint: building where official money is made",
		"Monastery: building where a religious community lives",
		"Museum: building housing objects of historical interest",
		"Pagoda: multi-tiered tower with overhanging eaves",
		"Palace: opulent home of rich and important local people",
		"Park: open space set aside instead of being developed, often landscaped and sometimes public",
		"Pawnbroker: shop that exchanges money for items",
		"Pigpen: agricultural building for raising pigs",
		"Plaza: open urban public space",
		"Poorhouse: place where the destitute are forced to work for room and board",
		"Pyramid: massive pyramidal tomb",
		"Rectory: home of a religious minister or cleric",
		"Shanty/Slum: a badly built or maintained structure",
		"Smokehouse: building for smoking meats",
		"Souk: market and neutral ground",
		"Square: open public space",
		"Stable: shelter for horses and mounts",
		"Tannery: workshop where leather is made",
		"Tavern: premises selling alcohol",
		"Temple: place of religious worship",
		"Tenement: building made up of several smaller residential units",
		"Theater: building used for the performance of plays",
		"Tower: tall structure with multiple levels",
		"Town Hall: administrative center of a district or town",
		"Townhouse: superior urban residence",
		"University: center for education",
		"Vomitorium: passage from an amphitheater or stadium",
		"Warehouse: large building used for bulk storage",
		"Water Mill: mill powered by flowing water",
		"Windmill: wind-powered mill, often for making flour"
    ]