var city_feature = [
    	"Six-headed gargoyle fountain",
        "Two huge feet, all that remains of a toppled statue",
        "Iron column 20 feet high",
        "Ancient, decaying elm tree",
        "Large bathing pool fed by lion-faced outflows",
        "Hot spring with a marble statue of a white dragon rising from its center",
        "Three bronze horsemen looking west",
        "Roadside shrine to a local saint",
        "Bust of the local mayor",
        "Gilded statue of the sun goddess",
        "A stone carving of the god of magic standing over 20 feet tall",
        "Black stone pyramid 10 feet high",
        "Huge weathered sphinx",
        "Line of 20 stylized stone faces",
        "Bronze colossus of the city’s patron god",
        "Marble statue commemorating a local hero, showing him on a chariot pulled by eight white chargers",
        "Fresco depicting a natural disaster",
        "Three trees intertwined to create a crude throne",
        "Golden orb on a plinth held aloft by stone rocs",
        "Ancient, weathered statue of a mysterious woman in otherrworldly garb",
        "Stone platform jutting from the roof of the tallest building from which criminals are thrown",
        "Small, bronze courtyard fountain",
        "Street fountain and watering trough",
        "Statue of a dwarf riding a griffon",
        "Washing fountain decorated with carved oak leaves",
        "Fountain held aloft by eight lions",
        "Alley with 100 fountains",
        "Fountain depicting six seahorses",
        "Weathered dolmen",
        "Sarcophagus carved with one-eyed crows",
        "Stone altar",
        "Marble statue of a scholar instructing a trio of admiring students",
        "Retired guillotine",
        "Large metal copy of a holy book; a novice turns the page each day with a key",
        "This city has a large Temple to a very minor deity.",
		"The South side of the city has a heavy Dwarven population and the West side has a large Halfling population.",
		"⁠There's a world famous bridge here that recently started falling down.",
		"⁠A famous University is in the city.",
		"A world renowned Academy is in this city.",
		"The most prestigious Military academy in the world is in this city.",
		"This city is famous for its rumored underground (figurative or literal) fight club.",
		"This city is world famous for its Apple Orchards",
		"This one for its coast line",
		"This one for its extremely strict laws regarding wine.",
		"This city is famous for its fashion trends.",
		"This one is famous for its gigantic horse drawn carriages.",
		"This city is well known for its dense population.",
		"This city is home to masterpieces of architecture.",
		"This one is known for its Opera House.",
		"The city is made specifically for creatures that can fly or levitate, and everything is elevated off the ground. However, nothing in the city is inaccessible to creatures that cannot fly, with ladders and staircases being the primary mode of access.",
		"Everything in the city is made to accommodate larger creatures.",
		"Everything is detailed with metal and stone due to its abundance of mining operations. As you may be able to guess, many dwarves reside in this city.",
		"This city is a human city amongst a wild land of Dragonborn tribes.",
		"These humans have become able to ride and domesticate dragons. In the city center there is a massive eyrie of dragons.",
		"There is a specific agricultural product which is common in the area around this city (spice, dye, wine, fruit, nut, vegetable) but is unavailable elsewhere due to the unique combination of climate, soil, rainfall and the difficulty of transporting fresh produce to other cities. The city has an annual festival celebrating the harvest of this product and its economic impact on the city.",
		"Since the mine shut down, this city has become a ghost town.",
		"This city is a tourist destination for those wishing to see the Great Crater of Isham for themselves.",
		"This city lies at the center of a contested land and has changed hands many times over a thousand years. It's architecture and inhabitants are incredibly diverse.",
		"This city lies at the center of a contested land and has changed hands many times over a thousand years. It's architecture and inhabitants are incredibly diverse.",
		"This city is made up of a labyrinthian system of tunnels and caves.",
		"You must cross a swamp to enter this city.",
		"This city is surrounded by tall mountains.",
		"This city is actually three cities that are separated by tributaries of a delta. Each city has grown so large they now are vying to expand either upward or outward. Each city is ruled by a different noble family that refuses to join into one city. Every time you cross a bridge, you have to pass through city gates that right now are charging a retaliation tariff over a recent dispute.",
		"The city is built over a humongous cave system. Many buildings have secret underground sections that almost nobody knows about.",
		"some creature with multiple personalities just chained up in the middle of the city.",
		"This city has a fruit tree in its centre that produce unusually large fruit. The type of fruit change each year.",
		"This city is know for its amazing murals painted all through out the city",
		"This city has had a resident that has lived there since its founding over 1500 years ago, she's an old human lady that still runs the same bakery that she opened a few years after the city founding. The bread there is delicious.",
		"The city has a very strict one dog per capita rule. No more, no less. Visitors are given guide dogs when they enter town and are required to keep them by their side at all times. The dogs carry their official paperwork and can lead them to the right place if they ask by name or type of item. 'Armor!' for the armor shop, for instance.",
		"The city has a strict curfew, because once the sun goes down, beautiful but ravenous pirahna-like fireflies appear everywhere throughout the streets, devouring any who step outside. It looks really pretty when it happens though.",
		"The city is home to people who never speak. If a word is spoken by somebody, everybody else stops what they're doing immediately, points at the person who spoke, and screams non-stop until a city guard comes and arrests the person.",
		"The city is only accessible by drawbridge. To enter, you must solve the gatemaster's puzzle: 'I haff tvelve metchsteek...'",
		"The city is populated primarily by wizards, with strange laws to match.",
		"The city is based around a pillar of floating azure marble.",
		"The city is covered in canals, the fish-folk of the city often have underwater entrances to their buildings",
		"The city has an incredibly tall pole. Nothing special about it, just very very very tall.",
		"The city's structures are built from the bones of titans long dead.",
		"The city is coastal and houses a large temple on the rocky shore with glass floors. The monks there study and worship the sea life they can view when the tides are high.",
		"The entire village is made up of friendly dopplegangers and house sized mimics",
		"A large river bisects the city, and there are two radicly different ideologies on either side",
		"A geyser/hot spring feeds hot water through complex aquaducts to small pools for bathing and drinking everywhere around the city",
		"The city rests in a crater that keeps it safe from the howling winds just above",
		"The city was built around an abandoned quary, with a massive, ominous dark crystal at its heart",
		"The city was built around the now retrofitted stronghold of a defeated lich",
		"The city was built on ancient druidic burial grounds, and hauntings are common",
		"Slave trading capital of the world. Currently facing abolitionists protests",
		"The city spirals down into obscurity and is entirely built on the inner walls of a vast natural cavern (or long dead volcano). Many bridges cross from one side to the other, and a few elevators are accessible to the top tier citizens.",
		"Rumors say that the nightmarish creatures sometimes creep up the walls to eat children during their sleep.",
		"The city is populated only by shapeshifted dragons.",
		"The city walls are made entirely of human bones and skulls.",
		"Though it appears normal from outside, once you step through the gate you realise that the city is set in permanent night.",
		"The city has the opposite meteorology from outside it's walls. If it is night out, it is day within; if the sun shines without, it is pouring within; hot outside, freezing in etc...",
		"The buildings consist only of circular towers.",
		"Everyone in the city goes around naked, and clothes are considered a perversion. Armour merely kinky.",
		"The city is known for its bard college and the regular literary festivals it holds.",
		"The city contains the largest library in the world.",
		"This city's residents are known to be annoyingly proud of where they come from - despite not being able to say exactly what they're proud of.",
		"This city's residents are known to complain about everything around them, but no one ever moves away.",
		"The city's founder will tell anyone who'll listen, 'When I first came here, this was all swamp. Everyone said I was daft to build a castlecity on a swamp, but I built it all the same, just to show them. It sank into the swamp. So I built a second one. And that one sank into the swamp. So I built a third. That burned down, fell over, and then sank into the swamp. But the fourth one stayed up.'",
		"The city has a large aqueduct from a nearby mountain, and several ornate fountains form the focal point for city squares.",
		"Every year near the end of Spring, a huge migration of songbirds turns the city into a riot of color and sound.",
		"The city is ancient. Having been around for centuries, it has been destroyed, rebuilt, and expanded several times. Beneath the ground are ruins of successively older buildings, artefacts, catacombs, and caverns.",
		"The city is a way station and major trade hub for horse trading, and the Great Bazaar meets every year in the summer. The city doubles in size and a forest of tents cover the plain outside as traders come from all over to buy, sell, haggle, and enter new contracts.",
		"Tall slender spires rise up from the city, as a complex network of messenger birds flit back and forth, allowing news and gossip to spread like wild fire. The birds roost in their high nests in the towers, tended by civil servants who only occasionally peruse the mail.",
		"The city has a smiling statue of its most famous export. Could be a fish, an apple, a bolt of silk... Whatever it is, it has a smiling face, arms and legs, and appears to be waving in greeting to all visitors.",
		"The catacombs below this city are famous for their non-euclidal corridors and constantly changing layout.",
		"The city is covered by a gigantic, man made dome and mighty pillars that support it. There is a small sun inside, covered by a multilayered clockwork sphere, creating a simple day and night cycle. The city even has It's own weather.",
		"Everyone who enters the city knows the main language perfectly. The main language changes every day. Nobody knows how or why, but nobody also really cares, because the city is now a fortress of some maniacal lich.",
		"Rivers of this city are magical water tunnels flowing through the air at different heights, from a few meters above the ground to even a kilometer. Most upper rivers are connected to a giant floating lake blob of water and aqutic fauna. Flying fish are the main food source and equivalent of pigeons. Except for landing to eat bread. And eating bread. They just float around the nearby plains looking for squirrels to eat.",
		"The city is mostly made out of hardened and detoxicated slime blocks. Fighters who live there are adept at fighting liquid creatures.",
		"The city uses undead creatures for unskilled labor such as carrying goods, courier services, pulling carts or plows, etc. Unemployment is a large problem because of this.",
		"The city is crisscrossed with dozens of canals. Locals transport goods, travel along, and even swim and draw water from these canals.",
		"The city is home to a series of hot springs that provide warm water to several great bath houses and the homes of the wealthier private citizens. It has become a tourist destination for many seeking rest and respite in the hot waters.",
		"The city streets are lined with flowering trees. Each spring the entire city blossoms, filling the air with sweet fragrances and a riot of color.",
		"The city is built in a deep crevasse between two large rocky hills. Due to the intense rainfall of the region and the high water table, these cliffs constantly stream water down them, creating a waterfall and river that surrounds the city. The city has even built every house on high stilts and stone platforms to keep everything dry. Once a night, the stream are diverted from around the city to through the city, washing away grime, muck, and litter.",
		"There is a well in the center of the city which grants one wish per year. Everyone is permitted one wish and at the height of the solstice one minor wish is granted.",
		"A man in a strange horseless carraige goes up and down the street seeking frozen milk products. He plays a strange tune the name of which no Bard can place.",
		"Residents of the town are addicted to carrying minor magical items that display nonsensical pictures, which they spread from person to person through unknown means. The items lose power if removed from the city for 24 hours.",
		"Home to a particularly large population of wild rabbits, no one knows how but they've managed to adapt to the urban street life like any stray dog or cat",
		"There's a duck statue in the city centre, artist unknown, it just appeared there overnight and has become a fixture since as the city has been unable to remove it, rumoured to be a prank played by a band of bards",
		"A fireworks factory with one too few walls",
		"This city has powerful wards from a time of legends.",
		"This city is built around the tower of a powerful wizard, no one knows if he is still alive.",
		"This city is at the intersection of several waylines, grating it a greet magical potential.",
		"This city was founded around a spring with powerful healing abilities.",
		"There is a monster that defends the city in exchange for food.",
		"At night the streets are lit by magical spheres.",
		"The buildings in the city centre very slowly change colour, it can take years to notice.",
		"The oldest buildings were there before the city, there architecture is alien and seamless.",
		"People buried in its graveyard sometimes comeback perfectly fine.",
		"The city is built on treetops of a large forest.",
		"The city is built on a high plateau, great bridges stretch downwards in every direction.",
		"The dead return as benevolent ghosts.",
		"The beer brewed here is praised throughout the land.",
		"The local guild of artificer is responsible for a new discovery.",
		"The city is a prosperous trade hub.",
		"The ruler has made medicine free to everyone.",
		"An ancient tree in its centre is cited in several religious texts.",
		"Bridges span between building, above the street.",
		"Metal is used heavily in construction.",
		"Most people own a swimming pool, its size is a status symbol.",
		"A fire burned down a chunk of the city town recently.",
		"The river that divides the city/town also divides a social rift between the two sides. Perhaps it's cultural, religion, economic etc.",
		"It appears to have a very angry/sad/mad/pleading wizard/nobal/child in the stocks. Why? Who knows?",
		"For one reason or another most of the populace has made insects their main source of food; the city is even renown for some of its bug infused dishes.",
		"The city has alcohol on tap",
		"This city is constantly moving. Be it by nomadic packing everything up and moving or as far as the city has been built onto massive moving machines. Think Mortal Engines but can be treads or wheels or even legs!",
		"The city has a 2 story tall, 1.5 mile long public bookshelf situated along it's southern wall.",
		"From above the city looks like a network of creeks, rivers, and swamps. That actually a complex water and sewage system for the city that lies beneath the swamp, protected from the dragons that are known to pillage the area.",
		"This dwarven city is surrounded by stone trees. each tree is actually an incredibly detailed statue created by a dwarven craftsman in order to prove their mastery.",
		"Abattoir: slaughterhouse",
		"Abbey: large religious building",
		"Alchemist: shop specializing in alchemical items",
		"Amphitheater: large open air stadium",
		"Apiary: collection of beehives for production of honey",
		"Apothecary: the business premises of a medical man",
		"Aqueduct: channel to move and deliver water",
		"Arboretum: garden for exotic plants",
		"Arena: stadium for sports and other entertainments",
		"Armory: military building housing weapons and armor",
		"Asylum: hospital for the treatment of the mentally ill",
		"Aviary: building housing rare or useful birds",
		"Baker: workroom or shop selling baked goods",
		"Bandstand: open-air stage for concerts",
		"Bank: secure building for the storage of valuables",
		"Barber: business offering haircutting and dentistry",
		"Barn: agricultural storage building",
		"Barracks: military building housing soldiers",
		"Basilica: religious meeting place",
		"Bazaar: type of market",
		"Bathhouse: building for public bathing and cleansing",
		"Blacksmith: shop for worked metal goods",
		"Brewery: building used to manufacture beer and ale",
		"Bridge: structure connecting two separate areas",
		"Brothel: building housing prostitutes",
		"Bullring: arena for bullfighting",
		"Butcher: workshop for the killing and cutting of meat",
		"Canal: man-made watercourse",
		"Carpenter: workshop where wood is worked",
		"Cartographer: shop where maps are sold",
		"Castle: large defensive structure",
		"Cathedral: huge center of worship",
		"Chapel: small religious building",
		"Church: place of worship",
		"Cistern: artificial reservoir",
		"Citadel: fortress for protecting a large settlement",
		"Coaching House: superior inn specializing in customers",
		"veling by coach",
		"Convent: religious establishment housing nuns",
		"Cottage: small residence",
		"Courthouse: official building for the judgement of law",
		"Crematorium: building for the disposal of dead bodies",
		"Distillery: building used to manufacture liquor and spirits",
		"Docks: point of embarkation and unloading for ships",
		"Dump: area for the disposal of garbage",
		"Drying Room: building used to dry fish, meat, and so on",
		"Embassy: official representative of a foreign nation",
		"Exchange: place where traders meet to buy and sell",
		"Flea Market: market specializing in secondhand goods",
		"Folly: building made purely for decorative purposes",
		"Forum: public meeting place",
		"Fortress: large fortified military building",
		"Gaol: prison or jail",
		"Garden: space for growing flowers, vegetables, and so on",
		"Gatehouse: defensive structure built around a gate",
		"Granary: storehouse for grain or animal feed",
		"Graveyard: place where the dead are buried",
		"Hippodrome: stadium for horse or chariot racing",
		"Hospice: guesthouse for travelers",
		"Hospital: place where the sick are treated",
		"Horse Mill: horse-powered mill for grinding grain",
		"Inn: house providing food and lodging",
		"Keep: defensive structure often built as part of a castle",
		"Library: building housing a collection of written texts",
		"Lighthouse: towering light used to warn ships of danger",
		"Longhouse: timber structure used as a meeting place",
		"Magic Shop: shop for the sale and trade of magic items",
		"Manor: large residential building",
		"Manse: large residential house",
		"Market Square: communal area for commerce",
		"Menagerie: collection of exotic animals",
		"Mint: building where official money is made",
		"Monastery: building where a religious community lives",
		"Museum: building housing objects of historical interest",
		"Pagoda: multi-tiered tower with overhanging eaves",
		"Palace: opulent home of rich and important local people",
		"Park: open space set aside instead of being developed, often landscaped and sometimes public",
		"Pawnbroker: shop that exchanges money for items",
		"Pigpen: agricultural building for raising pigs",
		"Plaza: open urban public space",
		"Poorhouse: place where the destitute are forced to work for room and board",
		"Pyramid: massive pyramidal tomb",
		"Rectory: home of a religious minister or cleric",
		"Shanty/Slum: a badly built or maintained structure",
		"Smokehouse: building for smoking meats",
		"Souk: market and neutral ground",
		"Square: open public space",
		"Stable: shelter for horses and mounts",
		"Tannery: workshop where leather is made",
		"Tavern: premises selling alcohol",
		"Temple: place of religious worship",
		"Tenement: building made up of several smaller residential units",
		"Theater: building used for the performance of plays",
		"Tower: tall structure with multiple levels",
		"Town Hall: administrative center of a district or town",
		"Townhouse: superior urban residence",
		"University: center for education",
		"Vomitorium: passage from an amphitheater or stadium",
		"Warehouse: large building used for bulk storage",
		"Water Mill: mill powered by flowing water",
		"Windmill: wind-powered mill, often for making flour"
	]
	
var uselessPerson = [
"A teenaged ne'er-do-well tried to sell you a narcotic herb. It turned out to be oregano. There's no law against selling oregano.",
"You met a very friendly puppy. The owner let you pet it.",
"Two old women insisted that whatever you're asking about, that's what's wrong with kids these days, asking questions like that.",
"A little boy said he was lost. His mother was literally right across the street. She apologizes to you for the trouble he's caused.",
"You saw someone with a really cool-looking jacket. Nothing matching the description of anyone you're looking for, you just thought it looked really nice.",
"A street artist was drawing and selling caricatures of people, but when you described what you were looking for, she said she hadn't seen anything like that.",
"A man selling sausages in buns said he hadn't seen anything and grumbled 'Idle questions don't pay the bills- sausages do'.",
"An old man recognized you as a fellow adventurer. He told you his life story and promised he'll get to the good part soon. He never got to the good part. It was barely even a story, just a list of things he killed and treasure he found. You learned nothing from it.",
"An old woman was having a serious discussion with a dog. It was strange, but it didn't help your investigation.",
"An old man claimed to have seen what/who you're looking for. You followed him for nearly an hour. When you finally asked him how long to get to the thing. He couldn't remember what you were looking for or where you were going.",
"A small child asked you why you were 'dressed funny'. Then she asked you 'Why?'. And then asked you 'Why?'. This continued until her mother dragged her away.",
"You are pretty sure you saw a middle-aged lady squat and relieve herself in an alleyway.",
"You didn't find anyone with information, but you did spot a newspaper headline where the word 'nebulousness' spelled incorrectly.",
"You found someone with a hooded cloak drawn down over their face, writing on a wall. They ran off before you could ask them any questions. They left behind a drawing that is … inappropriate.",
"A woman was handing out samples of a new cultivar of apple. It's not great. It's not terrible. Sweet but a little mealy.",
"You found a group of guards on smoke break. They didn't see whatever it was you were looking for and they suggest you move along quickly.",
"You saw a little old lady playing chess with her great-granddaughter, though she was blind and she had the girl move her pieces for her. This was heartwarming, but it didn't solve your current problem.",
"You saw a cat playing with a dead mouse- it ran away before you got close.",
"You saw a cat playing with a live bird- the cat paused to look at you and the bird flew away. The cat glared at you angrily.",
"You met a merchant from a foreign land selling exotic spices. He didn't seem to have heard of anything- he barely knows the language, and constantly turned the conversation back to what spices you'll buy. You think.",
"A woman selling ointments and perfumes from a cart blocked your path and badgered you to buy something. She spritzed you with a free sample and you now smell like lavender.",
"A street cleaner offered to let you search the contents of his bin for anything useful. After an hour, you found nothing and now you smell like rotten fruit.",
"You asked a bartender for information. He said they do trivia on Tuesdays, live music on Fridays and ale is half-priced on Mondays. And that's pretty much it.",
"A group of drunk old men waved you over to their table at the local pub, claiming they had information. Each of them gave contradicting stories. As you walked away, they argued over who hoodwinked you the most.",
"A well-dressed woman says that she had the object of your search in her shop right now. Once you get in, she began a presentation about how her patented liniment of castor oil, camphor, and 7 secret herbs and resins will cure all your ailments and change your life.",
"You asked a monk if he's seen what you're looking for. He hasn't, and you interrupted his prayers.",
"Three old women were discussing possibilities of marriage for their grandchildren. They went quiet and glared at you when you walked past; when they thought you were out of earshot, agreed amongst themselves that you were an example of the type of suitor they hoped to avoid.",
"A group of children were roughhousing, pretending to be adventurers. They stared open-mouthed as you approached them, as if seeing a celebrity, but acted shy when you came too close.",
"You heard a group of girls discussing peoples' outfits as they observed passers-by. They agreed amongst themselves that they don't completely hate your outfit. Your mood is significantly brightened, but you didn't collect any useful information.",
"An old woman said she's sure her nephew knows, but you had to remind her several times why you approached her in the first place. When you arrived at her nephew's home, he thanked you for bringing the old lady back but didn't know anything that could help you solve your problem.",
"You passed a bard with limp black hair and thick eyeliner. His voice was barely audible above his sad guitar. When you asked him if he's seen anything he told you that no one sees anything, we are all puppets with our strings cut, washing downstream, waiting to drown.",
"An excitable elderly man gave you specific and detailed instructions to a building. They sell jars of maraschino cherries, and they didn't have any information.",
"You saw an old man yelling at a cloud. There are just some regular clouds floating by. He wore an onion tied to his belt and yelled at you for looking at him funny.",
"A man claimed to have been be abducted by fairies, but the more he revealed the more it's clear he was just blackout drunk and spent the night in jail.",
"A toddler insisted on telling you about the snail he found today. Unfortunately, you could only understand about one word in five, and everything you said or did seemed to encourage him.",
"You saw an elven woman was yelling at a food kart. She wanted her money back because her meat kebab contained meat. Eventually the town guard had to be called in to settle the dispute.",
"A handsome young man waved to you. When you waved back and approached him, he seemed confused. He was waving at his friend, who was standing several feet behind you.",
"Someone pointed out a flyer for a laundry service with a clever pun name. When you try telling your companions about it, you can't remember the name. You feel foolish.",
"A man was trying to sell eyeglasses on a street corner and he insisted that you needed a pair. You did not need a pair, especially not ones with a great big scratch on the left lens.",
"You saw someone with the worst haircut you've ever encountered. You briefly forgot what you were looking for as you marveled at just how bad this haircut was. You couldn't even put into words just how unflattering it was and you become exasperated trying to explain to the rest of the party how deeply disturbed you are that someone left the house looking like that.",
"You met another party of adventurers. They asked you about answers to their own quest first, and then you asked them about your own. You couldn't help each other, so they wished you luck on your quest and bid you a sincere goodbye.",
"You spotted a group of youths who tried to look as innocent as possible as you walked past. You're not even sure what they were guilty of, they just looked like trouble-makers, but definitely not worth the hassle.",
"A gnome in the tavern swore he knew all about what you're looking for but can't remember anything of use for less than 3 top-shelf drinks. He talked about many things before he fell asleep, none of them pertaining to your questions.",
"You asked a normal-looking gentleman if he knew anything, he looked at you wide-eyed, and gasped. 'You can see me? You can really see me?!' Before you can answer he'd run away, lost in the crowd. That was the last time you saw him.",
"A man with a sock puppet introduces it as his wife and talks through her in a falsetto 'female' voice. Neither the sock or the man had information relevant to your situation.",
"A dwarf was picking lice out of his beard and eating them. He noticed you noticing him and pretended he was just scratching his chin instead.",
"You saw two sweet-looking old people holding hands. It almost made you believe in true love again. Almost.",
"A citizen claimed to have the all of the answers and went on to explain a conspiracy theory that the government is suppressing the 'truth' that the world is cube-shaped for reasons that remain unclear. You left before he could finish.",
"As you posed questions to a local merchant, you notice a woman, her hood pulled up against the sun, staring at you unblinkingly. On confronting this suspicious behavior, it is revealed that she was simply staring into space, contemplating dinner.",
"A child said he knows a very bad secret, but none of the grownups would listen to him. He showed you his father's cache of wood relief carvings, each crudely carved with images of improbably-proportioned women performing lewd acts. This was a waste of time, they weren't even carved very well.",
"A six-year-old girl told you she knows something very important, then sagely informs you on the anatomical differences between boys and girls. She wandered off before you could react.",
"A street urchin said he had some inside information, but he couldn't remember properly until you gave him a few coins. He said loudly that you're a creep for trying to pay him off, and smugly walked away as people stopped what they were doing to stare. When they went back to what they were doing without questioning you, you suspected that you weren't the first one to fall for this trick. The boy was long gone by then.",
"You felt like the locals were viewing you strangely. Like they knew something you didn't. When you finally cornered one into an admission, they informed you that your waterskin had been leaking, making it look like you wet your trousers.",
"A man smiled at you knowingly but refused to answer any of your questions. A helpful passerby told you that this man is the village idiot, and that he always smiles like that.",
"An enterprising street entertainer had no information to share, but for a silver piece he will do a whistle, a tumble, and a fart — all at the same time.",
"A heavyset woman boldly stated that she doesn't know and doesn't care, but if you'd like to earn a copper piece she has four large pots that need to be scraped clean.",
"A foreigner didn't know anything but dammit, they wanted to be helpful. So they just filled in their gaps of knowledge with anything they could think up.",
"A woman was walking strangely, changing her course for no apparent reason. She didn't appear to be drunk. Turns out she compulsively avoids cracks in the pavement and didn't have any information for you.",
"One of the commoners had a really nice butt. Really nice. What were you looking for again?",
"Vincent Tallman, three gnomes wearing a large overcoat, were trying to pass as a human. It doesn't seem very convincing but no else seemed to notice. You're not even sure why they were doing it but they never broke character, insisting that they were, in fact, a perfectly normal human adult. Even when one of the gnomes sneezed and the whole lot of them nearly toppled over.",
"A shadowy figure lurking in the darkest corner of the shadiest pub in town turned out to be a hat and coat hung up on a rack. That was the closest you got to any useful information.",
"A young man was sitting in a pillory, a broken lute at his feet. 'Tasteless Scatological Jokester' was written on a sign next to him. He did not look repentant. Perhaps even a little proud of himself. He did not know anything.",
"You find a dead body. You must stay as a witness for the local law enforcement, for 2 d6 X 10 min. Relatives eventually show up. The person died of perfectly ordinary natural causes related to a pre-existing medical condition.",
"A watchman follows you around acting like he thinks you're a criminal, and frightening off your contacts. When you confront him, he says he's bored and you looked suspicious, and then wanders off.",
"An old man in a tavern who declares that he will lead you to the local tavern with the best gossip so you can ask around there. He takes you out back, walks around to the front, and reenters through the main door. He got a laugh from the regulars.",
"“Marv the Magnificent”, a street performer who very loudly and extravagantly boasts to be the most mind-bogglingly talented juggler in all the land. You put off your investigation to watch for a few minutes. He's ok.",
"A young girl is throwing pebbles at you. She will follow you for a good ways and will continue to pick up pebbles. The adults who recognize her tell you that you look like the neighbor she doesn't like. The neighbor happens to be totally ordinary but does look a bit like you.",
"Three kenkus are following each other and mimicking each other with different accents and personalities. They are now mimicking you because you tried to ask them some questions.",
"Two people leafing through a manuscript in complex code with elaborate artwork of maps, exotic places, and mysterious artifacts. Each page has a different font, layout, and art style. After eavesdropping, you discover they are a scribe and author picking out a format and font. The manuscript is the scribe's stylebook filled with nonsense.",
"There is a pair of little girls ahead of you selling flowers for a copper each. They're just local wildflowers but they're pretty and they smell nice.",
"You discover the barkeep at one of the taverns cheats their patrons by pouring them cheaper wine and beer after they have already had a few. You advise your party not to stay at that tavern.",
"An elderly woman who said a relevant keyword to her younger friend. You tried to talk with her, but only got more and more confused as the lady rambled incoherently. Her caretaker explains the lady is a stroke survivor with mild aphasia and uses the wrong words without realizing it.",
"A gaggle of homemakers gossiping about property laws, taxes, and which of their acquaintances they suspect of having extramarital affairs while doing laundry.",
"You find a child playing hide and seek. They roped you into the game, so you had to find all of the rest.",
"You follow a sparse trail of blood and gore to an abandoned shed. The butcher had given their favorite stray dog some offal, and the dog carried it here to eat.",
"A group of three philosophers sitting on a street corner debating an obscure moral quandary with great energy and enthusiasm. None of them seem to notice that they all actually agree with each other.",
"What looks like some rags tossed into a corner of an alleyway is in fact a poorly dressed beggar sleeping. He's upset you woke him up.",
"A man standing outside a building, staring up at the window as a woman throws clothes and other personal items down at him with great vigor. He shouts up at her, demanding that she give him another chance.",
"A morose man hiding his drinking habits from his wife. None of his problems are helpful to your quest.",
"A tall elf walks through the street, accompanied by two half-elf bodyguards. He refuses to speak in Common, and even if addressed in Elvish, wants nothing to do with you. The elf happens to be both dreadfully boring and standoffish.",
"A cart with boxes marked with warnings to stay away in several languages. When approached, a halfling woman in a bee keeper's outfit appears. She's very annoyed you are disturbing her hives and tells you to buzz off.",
"Two crossdressers wanted you to judge whose outfit is better. You found a way to say nice things about both their choices and slipped off when they got distracted.",
"You see an amorphous cloud of dark smoke coming out of a fireplace. In the smoke you find a dirty chimney sweep, not understanding what is going on.",
"You meet a blind gnome who gives you incredibly specific and confident directions. He is lying, but you don't notice. When you go to the wrong place, someone helpfully informs you that the gnome is a pathological liar.",
"A wizard appears in a puff of smoke, he approaches you and starts to speak, then looks around confused. He looks back at you, mumbles an apology about being in the wrong place, and disappears.",
"A mediocre busker.",
"An old woman who makes a horrible grimace at you, but then scuttles away unexpectedly. She thought you were her child and was about to chew you out for your clothes and skipping work, but realized you were someone else when she got a closer look.",
"A pigeon with unusual coloring. You kept trying to get closer to see better, but the flock kept flying away. Eventually the flock mingled with another and you noticed several similarly unusual birds. It must be a common local mutation.",
"A pair of children who accidentally threw a small toy in your direction, which lands at your feet. One runs up to you and snatches it back, calling you a singsong name. His friend, standing behind him, mouths a silent apology to you.",
"Upon investigation, a citizen claims to have the information you're looking for, though they can't go into detail in public. They try to take you to their 'hideout' but you decide to give him/her the slip. The person turns out to be an innocent weirdo whose only goal is to convince you of a hairbrained conspiracy that is provably untrue.",
"A halfling who does nothing but brag about his hat.",
"A young man crying by the side of the road. They are crying because they accidentally got sand in their eyes a few hours ago and it still hurts.",
"A young gnome that keeps making egg-cellent egg jokes. I'm not egg-saggerating, he knows and egg-cessive amount of yolks.",
"A person walked by you who smelled incredibly odd. The NPC denies s/he smells at all and tries to leave quickly. You pressed the NPC and discovered that he/she knocked over a bottle of perfume and that s/he has no sense of smell.",
"While conversing with a far-traveled merchant of antiquities, you notice some guards watching you intently, their eyes narrowed, money changing hands. You conclude your business with the merchant and challenge the guards. It is revealed they were betting on whether you'd waste money on the merchant's junk.",
"A loud preacher in the nearby town courtyard who was denouncing what he believes to be evils in society for everyone to hear. There was a small crowd listening, some of whom were hecklers. You didn't learn anything.",
"Three young women gossiping and fawning over a handsome local.",
"A young woman ignores your questions as she is too interested in her book.",
"A man who only likes to talk about his hobbies and shrugs off your attempts to leave the conversation.",
"A farmer observing a hole in his fence where an amorous bull broke through. The bull introduced himself to the cows."
]	