var roomAccentMundane = [
"Slopes (up or down)",
"Dampness on walls/floor",
"Steady drip from ceiling",
"Puddles on floor",
"Covered in bite marks",
"Slippery",
"Chocked with webs",
"Open crevice or pit",
"Littered with bones",
"Full of strange echoes",
"Bridge or plank",
"Littered with broken pottery",
"Curtain",
"Lots of dried blood",
"Filled with droppings",
"Wreathed in strange black ivy",
"Full of unsettling fungi",
"Filthy",
"Infested with vermin",
"Pipes drip slimy brackish water onto floor",
"Covered in lichens",
"Small, rusty-iron section of wall",
"Covered in mold",
"Walls made of curious hexagonal stones",
"Cobbled floor made of gravestones",
"Slimy",
"Very slimy",
"Has butcher’s hooks hanging from ceiling",
"Wall exude yellowish, foul smelling discharge",
"Scratches on walls",
"Covered in graffiti",
"Water can be heard rushing immediately below",
"Chalk warnings appear on walls",
"Half filled with water",
"Full of rusty weapons and skeletons",
"Secret door behind fireplace",
"Burned",
"Cracks across floor",
"Cracks across ceiling",
"Cracks along walls",
"Held up by pit-props that look very weak",
"Has an overbearing smell of rotting fruit",
"Strange tapping sounds heard behind walls",
"Weeping heard occasionally",
"Full of empty gibbets",
"Iron maidens that line the walls are rusted shut",
"Floor moves in one direction",
"Floor drops suddenly by 5 feet for no obvious reason",
"Totally submerged",
"Full of flames",
"Slippery - water, ice, slime, or blood"
    ]

var roomAccentExotic =[
    "Fresco depicts grisly death of viewer",
    "Filled with the sound of sobbing, coming from a crypt",
    "Carved with faces depicting different alignments",
    "Candelabrum sheds black light from violet candles",
    "Statue on rotating pedestal",
    "Is a huge trap",
    "Walls like a rib cage",
    "Crammed with mummified frogs",
    "Iron spears rise randomly from a sieve-like floor",
    "Fire bursts randomly from a floor covered in holes",
    "Covered in pictures of evil peacock eyes",
    "Has a huge violet eye fresco in its center",
    "Appears to be the roots of some vast tree",
    "Boiling mud crossed by very narrow stone bridges",
    "Filled with giant spider husks of increasing size",
    "Is filled with a huge cage",
    "Has doors in the ceiling",
    "Fountains carved to resemble hydras",
    "Floor appears like a black lake but is actually glass",
    "Raised terraces lead to central carving of bat-god",
    "Slips sharply into a black pit of nothingness",
    "Filled with the sounds of thunder",
    "Is a huge shaft crossed by boughs of trees",
    "Faceless statues point at one PC upon entry",
    "Roof is a stained glass window depicting spiders",
    "Black fog appears suddenly",
    "Iron weights drop from roof at random times",
    "Endless stairway descends in room’s center",
    "Waterfall in room’s center powers waterwheel",
    "Magical voices sing hymns as the PCs enter",
    "Is filled with explosive gas that is otherwise harmless",
    "Is completely covered in tentacle carvings",
    "Has eight huge bells suspended above the floor",
    "Has a carving of a black devil-headed elephant",
    "Every inch covered in angels",
    "Iron devil statue speaks",
    "Goes up and down",
    "Entire floor pivots, dropping those who enter",
    "Ceiling begins to sink upon entry",
    "Archways lead to other places",
    "Sculptures of gargoyles tearing apart angels",
    "The walls are covered in mirrors that reflect nothing",
    "Rotates faster and faster once entered",
    "Gargoyles along ceiling shout abuse",
    "Randomly dimension doors those that cross it",
    "Altar attacks characters with magic",
    "Has a magic pool",
    "Is the stomach of a creature",
    "Weeps to itself",
    "Is alive",
    "Transparent floor",
    "Transparent floor"
]

var minorRoomItems = [
    "Abacus",
    "Ashtray",
    "Astrolabe",
    "Barrel",
    "Basin",
    "Basket",
    "Bellows",
    "Blanket",
    "Bloodstain",
    "Bones",
    "Books",
    "Boots",
    "Bottle",
    "Box",
    "Broken weapons",
    "Brush",
    "Bucket",
    "Calendar",
    "Candle",
    "Cane",
    "Cards",
    "Carrying case",
    "Chamber pot",
    "Clothing",
    "Cobwebs",
    "Cosmetics",
    "Dice",
    "Dishes",
    "Dried blood",
    "Dust",
    "Fan",
    "Fire starting kit",
    "Fishing",
    "Flask",
    "Food edible",
    "Food rotton",
    "Fungus",
    "Game board",
    "Glass",
    "Globe",
    "Gloves",
    "Hair",
    "Hammer",
    "Hand mirror",
    "Hat",
    "Helm",
    "Horseshoe",
    "Hourglass",
    "Ink",
    "Insects",
    "Key",
    "Knife",
    "Kettle",
    "Lamp",
    "Lantern",
    "Letter-opener",
    "Leash",
    "Lock",
    "Manacles",
    "Model-ship",
    "Mop",
    "Mud",
    "Nest",
    "Oil-block",
    "Paint",
    "Pen/paper",
    "Pipe/pouch",
    "Plate",
    "Pole",
    "Portable-instrument",
    "Pots-and-pans",
    "Pottery-fragments",
    "Papers",
    "Parasol",
    "Pouch",
    "Prosthetic-limb",
    "Rope",
    "Rusty-chain",
    "Rusty-nails",
    "Sack/bag",
    "Scissors",
    "Scale",
    "Shaving-kit",
    "Shovel",
    "Spent-torch",
    "Straw-bedding",
    "Ruler",
    "Tray",
    "Tongs",
    "Torch",
    "Toy",
    "Tuning-fork",
    "Urn",
    "Utensil",
    "Vase",
    "Wall",
    "Wall",
    "Wax",
    "Wheelbarrow",
    "Whistle-bench",
    "Rusty knives",
    "Dull knives",
    "Mismatched armor",
    "Shattered shields",
    "Tattered leather armor",
    "Wooden practice swords",
    "Broken swords",
    "Axe handles",
    "Arrowheads",
    "Goose feathers",
    "Turkey feathers",
    "Dulled spear points",
    "Worn-out hammers",
    "Steel nails",
    "Rusted hinges",
    "Broken doorknobs",
    "Assorted keys",
    "Empty glass bottles",
    "Broken glass",
    "Empty cans",
    "Blank parchment",
    "Lists and inventories",
    "Legal case files",
    "Decaying books",
    "Extra copies of a useless book",
    "Dried-up ink wells",
    "Used quills",
    "Empty glass vials",
    "Cork vial stoppers",
    "Discarded alchemical laboratory equipment",
    "Incomprehensible notes on alchemy",
    "Grocery lists and recipes",
    "Hand-written memoir of an ineffective bureaucrat",
    "Collection of of sappy love letters",
    "Crumbling sheet music",
    "Broken musical instruments",
    "Spare brass parts",
    "Scrap copper",
    "Old dried fish",
    "Human bones",
    "Some unidentifiable bones",
    "Teeth",
    "Blood-soaked rags",
    "Oily rags",
    "Tattered banners",
    "Tattered sails",
    "Winches and pulleys",
    "Some frayed rope",
    "A length of chain in an impossible knot",
    "Dented helms",
    "Assorted strips of leather",
    "Wood chips",
    "Iron filings",
    "Steel slag",
    "Ant-ridden flour",
    "Maggot-ridden meat",
    "Mold-covered cheese",
    "Bottles of over-ripe wine",
    "Ceramic mugs",
    "Glass mugs",
    "Plates and bowls",
    "Low-end steel cutlery",
    "Some old children's clothes",
    "Worn-out children's shoes",
    "Boots with holes",
    "Well-worn men's clothes",
    "Moth-eaten dresses",
    "Broken jars of pickled foodstuffs",
    "Empty gunnysacks",
    "Cured meat that is hard as a rock",
    "Bits of broken furniture",
    "Some tattered blankets",
    "Leaky oil lanterns",
    "Worms",
    "Mice",
    "Roaches",
    "Beetles",
    "A mysterious powder",
    "A mysterious crystalline substance",
    "A mysterious viscous liquid",
    "Cat toys",
    "Leashes, collars, and whips",
    "Horseshoes",
    "A heavy apron",
    "Rag dolls",
    "Wicker dolls",
    "Ripped and broken baskets",
    "Undyed wool",
    "Thin cotton cloth",
    "Needles, threads, and spare bits of cloth",
    "Vials of brightly colored powders",
    "Vials of brightly colored liquids",
    "Paintings of poor quality",
    "Sculptures and figurines of middling quality",
    "Incomplete chess sets",
    "Playing cards and betting chips",
    "Bent and broken wands",
    "Cracked and broken orbs",
    "Saintly relics and pungent incense",
    "Brushes of various sorts",
    "Water and Waste Bucket"
]

var majorRoomItems = [
    "Alcove",
    "Altar",
    "Anvil",
    "Archway",
    "Balcony",
    "Bar",
    "Bed",
    "Bell/gong",
    "Bench",
    "Bookcase",
    "Brazier",
    "Bridge",
    "Bunk",
    "Cabinet",
    "Cage",
    "Candelabrum",
    "Carpet",
    "Casket",
    "Cauldron",
    "Chair/stool",
    "Chair with straps",
    "Chandelier",
    "Chariot/wagon",
    "Chest",
    "Chimes",
    "Clock",
    "Cot",
    "Couch",
    "Crate",
    "Crib",
    "Crucible",
    "Cupboard",
    "Curtain/tapestry",
    "Dais",
    "Dome",
    "Door",
    "Divan",
    "Dresser",
    "Drysink",
    "Fetters",
    "cabinet",
    "Fireplace/pit",
    "Font",
    "Forge",
    "Fountain",
    "Fresco",
    "Furnace",
    "Gallows/guillotine",
    "Gibbet",
    "Grindstone",
    "Hogshead",
    "Hookah",
    "Horn",
    "Idol",
    "Instrument-(large)",
    "Iron-maiden",
    "Keg",
    "Ladder",
    "Loom",
    "Model-Mat",
    "Millwheel",
    "Mirror",
    "Mosaics",
    "Mounting-block",
    "Pallet",
    "Pedestal",
    "Pentagram",
    "Pew",
    "Pillar",
    "Pillory",
    "Pit",
    "Podium",
    "Pool",
    "Rack",
    "Rubble",
    "Saddle",
    "Safe",
    "Sconce",
    "Screen",
    "Sack/Shelf",
    "Shrine",
    "Sideboard",
    "Spiral-stair",
    "Stand",
    "Statue",
    "Steeple",
    "Stool",
    "Stove",
    "Table",
    "Tapestry",
    "Throne",
    "Torture-equipment",
    "Trunk",
    "Tub",
    "Tun",
    "fixtures-Urn",
    "markings-Washstand",
    "Well",
    "Winch",
    "Wood-bench"
]