var inn_noun = [
    "Boot",
    "Adder",
    "Ant",
    "Axe",
    "Barrel",
    "Bear",
    "Beaver",
    "Beetle",
    "Bell",
    "Boar",
    "Bone",
    "Boot",
    "Bowl",
    "Bucket",
    "Bull",
    "Candle",
    "Cat",
    "Claw",
    "Cloak",
    "Cock",
    "Coin",
    "Comb",
    "Cow",
    "Crow",
    "Crown",
    "Cup",
    "Door",
    "Dragon",
    "Eagle",
    "Egg",
    "Elephant",
    "Fang",
    "Fish",
    "Flea",
    "Fork",
    "Giant",
    "Griffin",
    "Gristle",
    "Hare",
    "Hart",
    "Hawk",
    "Hen",
    "Hog",
    "Hole",
    "Horse",
    "Hound",
    "Jar",
    "Kettle",
    "Key",
    "Knife",
    "Lamb",
    "Lamp",
    "Lantern",
    "Lion",
    "Lute",
    "Mackerel",
    "Maid",
    "Mermaid",
    "Mole",
    "Monk",
    "Moon",
    "Mule",
    "Needle",
    "Noose",
    "Orb",
    "Pearl",
    "Pig",
    "Pipe",
    "Plow",
    "Post",
    "Prince",
    "Queen",
    "Rat",
    "Rose",
    "Saint",
    "Serpent",
    "Shoe",
    "Shovel",
    "Skull",
    "Snout",
    "Sow",
    "Spoon",
    "Staff",
    "Star",
    "Stone",
    "Sun",
    "Sword",
    "Thistle",
    "Thorn",
    "Thread",
    "Throne",
    "Torch",
    "Tower",
    "Unicorn",
    "Vulture",
    "Weasel",
    "Whale",
    "Wheel",
    "Whistle",
    "Wife",
    "Worm",
    "ocean",
    "price",
    "seed",
    "string",
    "rat",
    "nation",
    "company",
    "cub",
    "veil",
    "quilt",
    "canvas",
    "finger",
    "current",
    "moon",
    "sleet",
    "purpose",
    "believe",
    "dinosaurs",
    "mitten",
    "recess",
    "pie",
    "ants",
    "self",
    "finger",
    "train",
    "zebra",
    "blood",
    "volleyball",
    "poison",
    "ink",
    "magic",
    "slave",
    "shock",
    "insect",
    "business",
    "coil",
    "part",
    "door",
    "sense",
    "picture",
    "hospital",
    "hammer",
    "bit",
    "neck",
    "theory",
    "pan",
    "order",
    "farm",
    "touch",
    "approval",
    "channel",
    "driving",
    "bells",
    "hour",
    "friend",
    "join",
    "doctor",
    "wheel",
    "attack",
    "nut",
    "sofa",
    "stick",
    "house",
    "scissors",
    "food",
    "copper",
    "detail",
    "wrench",
    "cakes",
    "letters",
    "wilderness",
    "turn",
    "women",
    "beds",
    "sock",
    "plastic",
    "sort",
    "work",
    "deer",
    "grape",
    "engine",
    "zinc",
    "activity",
    "brother",
    "swing",
    "earth",
    "voyage",
    "juice",
    "truck",
    "arithmetic",
    "trick",
    "snow",
    "sneeze",
    "interest",
    "flower",
    "maid",
    "tin",
    "profit",
    "ship",
    "creature",
    "button",
    "calendar",
    "shoes",
    "meal",
    "flight",
    "group",
    "humor",
    "icicle",
    "stretch",
    "plantation",
    "range",
    "tank",
    "toothpaste",
    "kitty",
    "downtown",
    "air",
    "rose",
    "reason",
    "vein",
    "uncle",
    "caption",
    "friends",
    "pizzas",
    "condition",
    "view",
    "airport",
    "field",
    "quince",
    "hair",
    "society",
    "eyes",
    "territory",
    "bath",
    "government",
    "committee",
    "bomb",
    "cellar",
    "chickens",
    "swim",
    "party",
    "boat",
    "heat",
    "shoe",
    "crack",
    "muscle",
    "birthday",
    "watch",
    "pets",
    "coach",
    "ice",
    "grass",
    "wash",
    "wave",
    "cast",
    "direction",
    "trousers",
    "decision",
    "tongue",
    "request",
    "hands",
    "home",
    "stop",
    "motion",
    "root",
    "cushion",
    "dock",
    "pig",
    "seat",
    "lunchroom",
    "adjustment",
    "voice",
    "account",
    "statement",
    "liquid",
    "vase",
    "railway",
    "knowledge",
    "nest",
    "pancake",
    "coast",
    "weather",
    "spark",
    "rod",
    "time",
    "chicken",
    "observation",
    "ball",
    "flesh",
    "dust",
    "amount",
    "title",
    "bell",
    "religion",
    "hat",
    "fork",
    "brick",
    "eggnog",
    "bee",
    "dog",
    "frog",
    "underwear",
    "twig",
    "discovery",
    "cover",
    "tendency",
    "health",
    "fog",
    "straw",
    "morning",
    "scene",
    "shake",
    "year",
    "girls",
    "quiet",
    "cobweb",
    "toes",
    "sky",
    "bait",
    "cheese",
    "boy",
    "month",
    "suit",
    "camp",
    "cracker",
    "winter",
    "dinner",
    "aftermath",
    "need",
    "page",
    "pail",
    "basin",
    "rhythm",
    "camera",
    "leather",
    "plants",
    "run",
    "bite",
    "harbor",
    "potato",
    "amusement",
    "wrist",
    "zephyr",
    "pin",
    "mark",
    "songs",
    "story",
    "system",
    "partner",
    "grain",
    "top",
    "cart",
    "cherries",
    "shape",
    "knot",
    "wish",
    "form",
    "monkey",
    "peace",
    "wool",
    "collar",
    "army",
    "hill",
    "bear",
    "move",
    "sleep",
    "night",
    "twist",
    "zoo",
    "offer",
    "base",
    "nose",
    "island",
    "plough",
    "silver",
    "book",
    "teaching",
    "wax",
    "ghost",
    "grandfather",
    "salt",
    "note",
    "property",
    "key",
    "advice",
    "cave",
    "paper",
    "quiver",
    "fold",
    "industry",
    "fowl",
    "kiss",
    "effect",
    "basket",
    "color",
    "pull",
    "exchange",
    "care",
    "sisters",
    "things",
    "lake",
    "turkey",
    "wine",
    "sail",
    "education",
    "regret",
    "holiday",
    "boot",
    "temper",
    "mass",
    "wall",
    "science",
    "line",
    "worm",
    "north",
    "addition",
    "acoustics",
    "design",
    "kick",
    "whip",
    "elbow",
    "stem",
    "development",
    "spade",
    "expert",
    "actor",
    "letter",
    "board",
    "notebook",
    "creator",
    "crowd",
    "weight",
    "birth",
    "cream",
    "cable",
    "experience",
    "scarf",
    "ear",
    "card",
    "squirrel",
    "yam",
    "death",
    "pen",
    "mother",
    "pump",
    "minute",
    "bulb",
    "hole",
    "baseball",
    "star",
    "hope",
    "planes",
    "drop",
    "stage",
    "action",
    "beef",
    "sun",
    "tax",
    "flag",
    "border",
    "appliance",
    "waste",
    "popcorn",
    "bird",
    "kittens",
    "crib",
    "snails",
    "robin",
    "van",
    "match",
    "mind",
    "thrill",
    "celery",
    "credit",
    "afterthought",
    "spot",
    "apparel",
    "sea",
    "thought",
    "hose",
    "church",
    "sound",
    "fear",
    "clam",
    "spy",
    "chalk",
    "tooth",
    "angle",
    "powder",
    "river",
    "quarter",
    "steam",
    "back",
    "stomach",
    "mine",
    "respect",
    "destruction",
    "curve",
    "aunt",
    "linen",
    "desire",
    "pencil",
    "oil",
    "orange",
    "flame",
    "plate",
    "belief",
    "argument",
    "question",
    "punishment",
    "country",
    "wealth",
    "eggs",
    "skin",
    "calculator",
    "passenger",
    "low",
    "visitor",
    "crook",
    "doll",
    "discussion",
    "ticket",
    "marble",
    "plot",
    "spring",
    "toad",
    "jar",
    "tree",
    "flavor",
    "jam",
    "glove",
    "crime",
    "crate",
    "mom",
    "honey",
    "cannon",
    "number",
    "throne",
    "oatmeal",
    "size",
    "pickle",
    "scent",
    "transport",
    "sink",
    "rub",
    "cook",
    "wire",
    "bucket",
    "secretary",
    "airplane",
    "connection",
    "locket",
    "soda",
    "books",
    "lock",
    "loss",
    "selection",
    "cap",
    "space",
    "head",
    "smell",
    "hall",
    "earthquake",
    "yak",
    "agreement",
    "girl",
    "blow",
    "meeting",
    "vegetable",
    "look",
    "trip",
    "route",
    "breath",
    "yoke",
    "mailbox",
    "tail",
    "bedroom",
    "pigs",
    "chin",
    "whistle",
    "bat",
    "smile",
    "tiger",
    "geese",
    "grade",
    "roof",
    "duck",
    "way",
    "beginner",
    "face",
    "support",
    "grandmother",
    "writing",
    "bed",
    "rail",
    "horses",
    "queen",
    "crow",
    "thing",
    "fairies",
    "limit",
    "window",
    "oven",
    "grip",
    "knee",
    "plane",
    "fireman",
    "bead",
    "quartz",
    "building",
    "tub",
    "stove",
    "drink",
    "battle",
    "wind",
    "person",
    "silk",
    "zipper",
    "taste",
    "increase",
    "stone",
    "corn",
    "station",
    "clover",
    "week",
    "achiever",
    "toothbrush",
    "fall",
    "glass",
    "gate",
    "foot",
    "jewel",
    "reading",
    "milk",
    "club",
    "car",
    "lunch",
    "baby",
    "unit",
    "sugar",
    "jellyfish",
    "thumb",
    "act",
    "lamp",
    "name",
    "middle",
    "thread",
    "brake",
    "fly",
    "smoke",
    "cow",
    "front",
    "lumber",
    "coat",
    "pear",
    "wing",
    "fish",
    "sponge",
    "box",
    "bikes",
    "income",
    "square",
    "men",
    "language",
    "fact",
    "cows",
    "treatment",
    "harmony",
    "word",
    "skate",
    "bottle",
    "toe",
    "table",
    "hand",
    "receipt",
    "room",
    "burst",
    "wound",
    "play",
    "library",
    "rest",
    "invention",
    "yarn",
    "leg",
    "quicksand",
    "lettuce",
    "ring",
    "talk",
    "pet",
    "payment",
    "spiders",
    "playground",
    "school",
    "riddle",
    "rate",
    "friction",
    "growth",
    "cherry",
    "hydrant",
    "ducks",
    "authority",
    "prose",
    "shade",
    "produce",
    "stamp",
    "scarecrow",
    "writer",
    "tent",
    "idea",
    "haircut",
    "frogs",
    "fang",
    "sheep",
    "show",
    "mice",
    "pollution",
    "rainstorm",
    "animal",
    "berry",
    "servant",
    "relation",
    "distance",
    "bike",
    "cloth",
    "rake",
    "fuel",
    "sand",
    "degree",
    "walk",
    "soup",
    "waves",
    "behavior",
    "cactus",
    "pot",
    "place",
    "pleasure",
    "curtain",
    "step",
    "toy",
    "start",
    "competition",
    "cough",
    "bridge",
    "can",
    "judge",
    "ladybug",
    "slip",
    "steel",
    "iron",
    "rabbit",
    "giants",
    "bubble",
    "cat",
    "thunder",
    "surprise",
    "brass",
    "sign",
    "trains",
    "war",
    "feeling",
    "frame",
    "minister",
    "store",
    "furniture",
    "shelf",
    "governor",
    "cabbage",
    "floor",
    "meat",
    "cars",
    "branch",
    "vessel",
    "stitch",
    "edge",
    "needle",
    "chance",
    "lip",
    "road",
    "cent",
    "bone",
    "example",
    "dad",
    "carpenter",
    "love",
    "texture",
    "mint",
    "jeans",
    "land",
    "tramp",
    "song",
    "sheet",
    "throat",
    "cause",
    "dogs",
    "guitar",
    "balance",
    "sticks",
    "gun",
    "teeth",
    "mountain",
    "cup",
    "office",
    "rock",
    "legs",
    "egg",
    "houses",
    "dirt",
    "cattle",
    "seashore",
    "spoon",
    "market",
    "record",
    "class",
    "existence",
    "comparison",
    "mask",
    "laugh",
    "memory",
    "flock",
    "suggestion",
    "dime",
    "hot",
    "apparatus",
    "wren",
    "reaction",
    "quill",
    "badge",
    "nerve",
    "money",
    "snakes",
    "hook",
    "son",
    "trees",
    "drawer",
    "stocking",
    "street",
    "basketball",
    "blade",
    "horse",
    "flowers",
    "metal",
    "shirt",
    "plant",
    "fire",
    "art",
    "crayon",
    "hate",
    "coal",
    "arm",
    "stream",
    "rabbits",
    "wood",
    "trucks",
    "dolls",
    "point",
    "parcel",
    "horn",
    "pipe",
    "control",
    "protest",
    "ray",
    "water",
    "circle",
    "instrument",
    "skirt",
    "alarm",
    "division",
    "jump",
    "oranges",
    "rain",
    "screw",
    "impulse",
    "pest",
    "tomatoes",
    "rings",
    "sidewalk",
    "stew",
    "reward",
    "ground",
    "drain",
    "porter",
    "town",
    "day",
    "toys",
    "kettle",
    "lace",
    "birds",
    "woman",
    "rifle",
    "guide",
    "error",
    "vest",
    "sister",
    "cats",
    "verse",
    "summer",
    "jelly",
    "mouth",
    "distribution",
    "umbrella",
    "debt",
    "man",
    "soap",
    "team",
    "test",
    "giraffe",
    "attraction",
    "laborer",
    "structure",
    "crown",
    "expansion",
    "digestion",
    "volcano",
    "snail",
    "shop",
    "force",
    "chess",
    "power",
    "gold",
    "value",
    "anger",
    "measure",
    "rice",
    "end",
    "side",
    "dress",
    "history",
    "knife",
    "representative",
    "scale",
    "arch",
    "slope",
    "stranger",
    "babies",
    "noise",
    "snake",
    "loaf",
    "machine",
    "trouble",
    "roll",
    "afternoon",
    "yard",
    "event",
    "sack",
    "mist",
    "cake",
    "daughter",
    "vacation",
    "bag",
    "bushes",
    "trade",
    "level",
    "shame",
    "butter",
    "pies",
    "substance",
    "eye",
    "jail",
    "desk",
    "position",
    "children",
    "rule",
    "insurance",
    "fruit",
    "push",
    "change",
    "donkey",
    "sweater",
    "carriage",
    "smash",
    "cemetery",
    "tray",
    "pocket",
    "advertisement",
    "boundary",
    "trail",
    "hobbies"
    ]

    var inn_encounter = [
    "The inn's pet cat is taking a nap on your bed.",
    "A hand-sized spider is on your pillow. Before you can take action, it scurries out of sight.",
    "The last guest experimented with magic here: the whole room (and furniture) is under a Reverse Gravity spell. It wears off in the morning, maybe.",
    "There's a stranger sleeping in your bed. If roused, they will say they got into the wrong room.",
    "You hear footsteps in the corridor. It's a streaker that quickly gets into the last room of the corridor.",
    "A candle left on the bedside table fell and it started a fire.",
    "The room smells of: (roll d6): weed/incense/grease/dust/candle wax/smoke.",
    "A former guest forgot a bag.",
    "A former guest left a plush doll.",
    "Someone forgot a change of clothes here.",
    "Your window was left open. Now a pigeon has made its nest on the window frame.",
    "The room smells rotten. Further investigation reveals a corpse hidden in the closet, mattress, etc.",
    "The tip for room service from the previous guest is still here. It's 1d4 silver pieces and a note that says: 'Good luck with your studies!'",
    "There is a family inside your room. They claim it's their room and it's impossible to convince them otherwise.",
    "There's a postal card with a picture of a distant place, such as the Nine Hells, the Feywild or Mount Celestia.",
    "Room service knocks on your door with a tray with a small feast on it. It's up to the DM if it was intended for you or not.",
    "There is an extra pillow on your bed. One is a mimic. It has much less hp than a regular mimic and explodes into teeth and feathers and blood when you kill it. [/u/AwkwardTRexHug]",
    "You hear someone weeping in the middle of the night. The staff says it's from a ghost.",
    "A killmoulis or another well-intentioned creature scurries out of sight when it sees you.",
    "The view from the window doesn't match the location: it could be the view of a tropical beach in the middle of the city, and so on.",
    "You see someone jumping from your window, landing gracefully on the ground, and darting away.",
    "A Halfling tied to a rope is cleaning the window glasses from outside.",
    "You find a peephole in the wall.The innkeep is actually a peeping tom and watching the party. [/u/SeaPen333]",
    "The old bed breaks under your weight.",
    "The paint on a wall is chipped. If inspected, it shows it was covering a blood stain.",
    "Someone knocks on your door: it's a cultist asking for some spare bone and blood powder.",
    "Someone knocks on your door: it's the city watch looking for dangerous cultists.",
    "The scales/feathers/fur/nail clippings from the last guest are still scattered on the floor.",
    "You hear knocking on your door. When you open it, there's nobody around, but you hear giggles from the corridor.",
    "There is a huge party outside/on the lower floor of the inn. Because of the noise, you won't sleep soundly.",
    "You hear a serenade outside. It's up to the DM if it's intended for you or not.",
    "Rats eat half your food overnight.",
    "There is a small shelf in your room stocked with fine wine, aged cheese and dried fruit. Taking/eating anything from it cost extra 20 gold pieces, but it grants you 10 temporary hit points.",
    "Your room's furniture and architecture doesn't match at all with the rest of the inn design.",
    "There is a sign near the window that reads: 'Jumping from the window is forbidden.'",
    "A guest in the other room is snoring loudly. Roll a DC 13 perception check, and on a success you sleep poorly. [/u/_solounwnmas]",
    "There is a sign on your bed table that reads: 'do not leave the candle unattended.'",
    "You find out that you are allergic to whatever fabric the bed sheets are made of.",
    "You discover an improvised rope hanging from an upper floor. It wasn't there a minute ago. [/u/FunkyGeneFlow]",
    "The innkeeper knocks on your door and asks if you or another party member knows an exorcist.",
    "There's a doll on the bed. If you try to get rid of it, it reappears after an hour when you are not looking.",
    "A rookie bard is practicing playing the bagpipes in the next room.",
    "Some odd mushrooms are growing in the corner of your room. They may be poisonous, hallucinogenic or Campestris.",
    "There is a potted plant left by a former guest. Further inspection reveals it's a mantrap sapling.",
    "There is a lump inside your pillow. You find a small box with a trinket and a note.",
    "You hear plenty of footsteps coming from the upper floor, then you remember there are no other floors upstairs. [/u/FunkyGeneFlow]",
    "There are tally marks on a wall. Next morning, you find that another tally was added.",
    "You are pretty sure the furniture was facing the other way last night.",
    "Someone did a short sheet prank in your bed.",
    "A HIGHLY UNSUAL creature sits at the bar, eating. No one seems to pay it any mind. (Gnoll, Zombie, archdevil, etc). [/u/snakebite262]",
    "A Necromantic Fish is posted on the wall. At random intervals, it will sing a song, jeer at the audience, or otherwise crack a 'humerous' joke. [/u/snakebite262]",
    "A dragonborn, with a bad cold, accidently catches a small part of the tavern on fire. It is quickly put out and the dragonborn is escorted from the building. [/u/snakebite262]",
    "A drinking contest seems to be going on between a group of idiots. [/u/snakebite262]",
    "It's trivia night! Several groups are spread out throughout the bar, answering random trivia for a small prize. [/u/snakebite262]",
    "A small group of imps are performing a comedic ballad as a warlock watches, ready to banish them if they're too rowdy. [/u/snakebite262]",
    "Everyone here seems to, ahem, recognize the bard/other character. [/u/ButtonholePhotophile]",
    "Another patron repays a character an old debt of 5 gold. [/u/ButtonholePhotophile]",
    "The fire in the fireplace is where the mysterious singing is coming from - it’s an elemental! [/u/ButtonholePhotophile]",
    "The overnight rooms are actually tents out back.[/u/ButtonholePhotophile]",
    "The only furniture in the room is a giant blanket, but it is beyond ridiculously huge. Everyone who sleeps here gets a +1d4 to their choice of rolls in the next 24 hours.[/u/ButtonholePhotophile]",
    "The toilet is jammed/the latrine is filled. [/u/ButtonholePhotophile]",
    "They forgot to clean up the last body, revealing their scheme to rob/murder the party. [/u/ButtonholePhotophile]",
    "A young dwarf knocks on the door, trying to find the dealer of something illegal.[/u/photonfiend]",
    "News comes of a nearby fire. It's dangerous, but not threatening this building yet.[/u/photonfiend]",
    "The furniture is dirty, stained, much more than other rooms. That explains the discount...[/u/photonfiend]",
    "See a few shooting stars outside the window.[/u/photonfiend]",
    "The previous occupant - a halfling woman - knocks on your door in the middle of the night. If you don't wake up, they enter and look for something they left behind.[/u/SpringPfeiffer]",
    "There's a random potion under the bed.[/u/SpringPfeiffer]",
    "A book of erotica is wedged under the mattress.[/u/SpringPfeiffer]",
    "A ransom letter is under the pillow. The meeting is tonight in one hour on the other side of town. [/u/SpringPfeiffer]",
    "A complimentary bowl of fruit is delivered. The note is addressed to someone else. [/u/SpringPfeiffer]",
    "A beggar outside on the street keeps using Thamaturgy to open your window (there's no lock to keep to window shut) until you toss them a coin [/u/SpringPfeiffer]",
    "The closet is a secret entrance to a night market. There is no lock on the door. A few people will walk into the room and disappear into the closet without acknowledging the PCs. [/u/SpringPfeiffer]",
    "You walk in on a dwarf tied up to the bed posts, when questioned he is evasive and unclear as to why he was tied up. [/u/_solounwnmas]",
    "An individual of the PC's preferred gender and race cuddles up to them in the middle of the night. If they are allowed to sleep there you feel like you had a great night's sleep but gain a level of exhaustion and can't find your money (it was a succubus/incubus). [/u/_solounwnmas]",
    "Guests in the room next door are having a noisy argument in the middle of the night. [/u/gnurdette]",
    "A traveling bard is singing for her supper in the common room. She's amazingly good.[/u/gnurdette]",
    "A horse runs off while the stableboy is trying to get him put away. There's a lot of angry yelling.[/u/gnurdette]",
    "It's raining, and the roof leaks. [/u/gnurdette]",
    "The inkeeper knocks to check that everything is satisfactory, but really, he wants to natter on about his life story. [/u/gnurdette]",
    "A local making a delivery whispers a warning that the inkeeper is known to steal from guests. [/u/gnurdette]",
    "A guest is rushing from room to room looking for help for her abruptly ill husband. [/u/gnurdette]",
    "The hotel is raided by local authorities as it is operating as a illegal brothel. Either because prostitution is illegal, this establishment is dodging taxes or something more sinister. You are believed to be a customer and treated as such by the authorities. [/u/Equivalent_North710]",
    "A religious book for a cult to a Great Old God, some Lovecraftian monster, can be found in the bedside table. It’s been placed there by the in-world equivalent of the Gideonites. If mentioned to the Tavern Owner they get upset and launch into a litany of profanity about the group that keeps placing the books in the rooms. [/u/MyEvilTwin47]",
    "A visiting group of dancers from a faraway land are in the city to perform their traditional clog dance, and they rehearse the performance into the early morning hours. [/u/MyEvilTwin47]",
    "You catch a thief ransacking the room, looking for a valuable item. They are armed with a dagger but have poor fighting skills. They’re also not only looking in the wrong room, but the wrong tavern. [/u/MyEvilTwin47]",
    "A teenage boy is in the room, hiding from the City Watch, who claim he broke into the local lord’s/king’s castle. The boy claims he was there invited by the heir apparent, his lover. DM determines which is true. [/u/MyEvilTwin47]",
    "A really terrible bard has set up in the lobby and is playing only cover songs of modern (earth) music, but in a style inappropriate to the songs. [/u/JoshSamBob]",
    "Two huge dogs - the size of small horses - sleep by the hearth fire and growl if anyone comes near. [/u/JoshSamBob]",
    "The room is significantly colder than the hallway. Like, 30°F/16°C colder. [/u/JoshSamBob]",
    "There's a goblin under the bed. When you see it, it smiles, puts a finger to its lips, and silently makes a 'Shush'ing face.[/u/JoshSamBob]",
    "The inn offers free room service, but it comes with a nefarious cost. [/u/JoshSamBob]",
    "Another guest begs you to swaps rooms, but won't say the reason (you may roll again).",
    "You walk into the wrong room. You may find another guest, a staff member or whatever the DM fancies.",
    "You room (or maybe the whole inn) is infested with fleas/bedbugs/mosquitoes...",
    "The city watch/clergy/sanitary authority have cordoned around the inn, with all its guests and staff stuck inside.",
    "Someone famous/popular/important is lodging in the inn. Their bodyguards won't let anyone close to their room, let alone get close to them.",
    "A gnome ask the party to participate in a study as a focus group about what it's their worst/hardest enemy to engage in battle. The gnome is the BBEG's minion.",
    "A tiny servant or another similar construct in cleaning the corridors. If obstructed or harmed in any way the Innkeeper will demand the perpetrator to stop/pay a fine/leave the inn.",
    "Surprise! you are the 100th! guest. The staff throws a small party for you and your friends."

    ]

    var inn_patron = [

    "Sartorin is a mysterious-looking half-elf man who sits in the corner of the bar wearing temple robes. He looks worried. If asked why, he will tell you that he saw an omen this morning that signifies the end of the world.",
    "Tharbuck Silvertale is a popular local bard who just got done playing on the stage. He is surrounded by beautiful women and is having the time of his life.",
    "A figure sits in a more shadowy part of the bar, slowly sipping their drink and keeping a close eye on everyone in the room. When the players ask about them, they’re given a different name from every person they ask.",
    "Hesjing is a kobold bard with a strange-looking lute that is WAY too big for him. He can be found near the bar, humming a familiar song while tuning it.",
    "James “Jimmy” Ravendown is a human wizard with a deep southern accent. He can be found talking and giggling to himself at one of the bar tables.",
    "Britches the goblin, a purveyor of minor magic items and other knickknacks. Would anyone care for a two-headed arrow? Perhaps a few grains of dust of dryness? Who knows what's in his small satchel of holding besides him?",
    "Dave, the depressed gnome wizard is not sitting in a chair but constantly hovering a few feet off the ground. You can see in his eyes he is an overworked man struggling with motivation. When approached for conversation he teleports himself to the other end of the bar, evidently too lazy to walk. Intriguingly powerful and highly in need of some excitement in his life, you approach him again...",
    "Spitter the Half-Orc, so called by the tavern keeper, only ever sits by the bar, but is willing to talk if someone else initiates. If he feels unobserved, he sneaks behind the bar and cleans some dishes, sometimes by spitting on it.",
    "Claudius, a self declared 'local hero', tells everyone about his brave accomplishments, despite provable lies. After a closer look at his gear you can assure, he never even left the town or has drawn his weapon.",
    "Helinda the experienced dwarf ranger that offers her support to anyone looking for adventures. Talking bores her immensely, so don't expect a long discussion or long answers on questions to the surroundings.",
    "Richard the old adventurer is eager to listen to the stories of the heroes. His tired eyes seem to dream of the events told, but when asked he says he is too old to wander out and he would miss his wife and children.",
    "Lufty the Gnome Magician is happy to show his mostly bad card and magic tricks to anyone looking sad. He seems to enjoy every smile he earns with his tricks. Despite that he secretly is a quite powerful wizard.",
    "Lestat the melancholic bard sings mostly sad songs while playing his unique looking guitar. When asked he tells about how he lost the love of his life for his ambitions to become great. This guitar is 'what his love has now become', whatever that means.",
    "A young couple sitting in the corner, one a half-elf and the other a human woman giggling to each other as they bounce their shoulders and pour over a map. The half-elf's clothes are of common quality, but upon closer inspection his accessories are of fine gold and gems. The human girl's hair is dry and face looks clearly malnourished, the only fine accessory on her is a single golden ring that matches the half-elf. Upon eavesdropping, they have eloped and are plotting their new home away from the eyes of his wealthy family.",
    "A bard is playing in the corner of the tavern, singing the praises of the current [Duke/Lord/Owner of this land]. Glorifying all the improvements to the roads and all the awesome promises of stuff that tax money has been spent on. Everyone is apathetic to the bard, and the party recalls the roads in this fief were all dirt and full of potholes. After his set, the bard buys a round of drinks, courtesy of his paycheck.",
    "Geraldine the Widow - She is dressed in all black and is seen nursing one glass of the finest wine in this establishment all evening. (To be fair, it's probably not that fine.) If spoken to, she is firm but graceful and talks about her poor dear Horace. (May he rest in Peace.) If asked about, she may have killed him off 8 years ago and claimed his small title and farm, ran it all herself.",
    "Peter the Handsy - Dressed in frills and ruffles, Peter approaches the most attractive young men and is trying to woo them to his room for a 'most intimate and wonderful chat'. After a few drinks he is flinging himself onto chests saying he 'likes them manly!' When a fight breaks out, he dodges a weave beautifully between the punches and uses bystanders as cover saying 'I only wanted to be friends! What's so wrong with that?' He is a slippery fellow, who not only swipes coin purses but reagent pouches. Then leaves at an opportune moment.",
    "Thomas Auburn: A male human crying into his ale over a recent breakup. Desperate to win her back, he will buy into pretty much anything the party suggests. (For example, in the case of my home game, he joined an anti-litch army that the bard was setting up. That's how low this bar is being set.)",
    "Lei'ann Inarzee: An elvish woman who is a part of the local thieves' guild. She's pretty skeptical of the party, but knows almost everything going on in the town, and is open to giving any information that the party needs. She also recognizes any rogues in the party and speaks in thieves' cant to them throughout the conversation.",
    "Ba: A half-orc male regular to this tavern who usually replies by grumbling out one or two words. The other patrons have started taking bets on how many words they can get him to say. Highest count so far is a 6 word sentence, and the longest word was an incredibly rare 4 syllables.",
    "Dortish: An elderly tiefling woman with deep maroon skin. She works as a fortune teller, and will give palm readings out to anyone who asks. All she asks for in return is some change from when you bought your drink.",
    "Tom Tommington: A shifty looking human male trying to pass off as a half-elf by taping paper to his ears. He is very slow in telling you his name (as if he's only just making it up), is constantly looking around nervously for 'them', automatically assumes that everyone around him is out to get him, and refuses to elaborate on any of these points.",
    "Morden Soptree is the immature son of a local merchant. A fortune-teller just told him that he must marry by his twentieth birthday - the day after tomorrow - or be alone forever. He has a terrible reputation and the local girls are not interested. He's desperate.",
    "Kaye, Kern, and Dorse are three young halfling children. They sit on one bench/booth together, each passing a glass of water between them. They're noticeably dirty, and between jokes periodically glance around. If approached they tell you their mom went out and will be back any minute.",
    "Titos Tom, a pale looking human who in a shaky voice tells you all about an undead infestation on his nearby farm. He hasnt had to work in several moons as the undead come and plow his fields and tend his crops. It's handy but... unnatural. The chickens have really taken to them, too.",
    "Old Sa'lah - Sa'lah al Sadeem is a retired merchant, obese and balding, and dressed in fine clothes that have seen a lot of wear. He is a tavern regular and mostly keeps to himself. He is especially curious of strangers, and will invite them to sit at his table and hear a story of his days as a caravan merchant in the hot, sandy deserts long ago... in exchange for a mug of ale. If the party is so willing, Old Sa'lah will tell a few tall tales but is mostly just happy to have company.",
    "Britta the Beast - This monstrous human woman stands nearly seven feet tall and boasts shoulders so broad they barely fit through the doorway. She is known for challenging outsiders to an arm wrestling contest, and will forgo a bet of coin if she sees a shiny prize hanging on a party member's belt. Britta is a berserker with the following changes: proficient in Athletics (PB+3) and has the trait Master Arm Wrestler, which grants advantage on all attempts to arm wrestle. If Britta wins, she will console the losing party with a free round. If she loses, she will slam her fists into the table, break a chair, and storm out in a screaming rage.",
    "Tin-eye Glitterbloom - This rock gnome sits on an especially tall barstool and his wild shock of hair sticks straight into the air in wild, unkempt tufts. He has lost the plans for his latest invention and is busy with a piece of charcoal and parchment. He will become exasperated and angry if the players try to interrupt his train of thought.",
    "The tabaxi at the end of the bar, with a bowl of kumis (fermented milk) and eating some foul-smelling dried meat. She has an array of trinkets spread in front of her, some with arcane symbols and some planer. She is inspecting them and writing notes in a journal. When questioned, they are collected from her recent travels and she is cataloging their features and provenance. Some may be magical or a story hook, and some may be for sale.",
    "That one dude who's always so plastered, sitting on the curb outside, begging for another drink or some coin to buy one. A good thief looks at the signs though; those boots are military issue, and they lack the ever present smell of vomit, ale, and urine that marks a true drunk, despite looking filthy. Best not to discuss sensitive business here, today.",
    "That gentleman there, in the heavy travelling cloak, wide brimmed hat, and with an artfully modest silver chain and religious amulet... has been nursing the same pint for the last half hour, hasn't removed his gloves, nor loosened his cloak.. despite the warm night? He's here on business and that chain is likely mithril, to be used as a garrote.",
    "Three King's Guards ordering a pint? And two exercise-men walking in through the door? Time to leave. You don't want to be a part of what's coming... they're here to make arrests.",
    "A Paladin of the Rose and Garter, in polished breast-plate, heroic pompadour, and gleaming smile. Possibly already smashed, and looking to sin.",
    "Blind' Gillis; Near-sighted and cross-eyed; does the books for the local Thieves Guild Boss; and a known teetotaler.",
    "A Priest and two lay clergy. Looking to spare some souls, and spoil some drinks.",
    "Jin and Jace: Strong arms, strong backs, and looking to cut loose, get drunk, and then maybe secure paying work of the rough and tumble kind as wagoneers or caravan guards.",
    "The depressed one-eared artist always orders wormwood spirits with a lump of sugar, and small beer on the side. Has been in-between paying patrons for so long, is down to their last gold-piece.",
    "A scarred elf, with one eye, and wrapped in leather belts and animal skins, keeps asking for dandelion beer or apple-jack and is getting angry. The small fey they are guarding drinks only cider, and keeps their own council.",
    "Xeal is a corpulent green dragonborn wearing lavish clothing and much jewelry. He sits at a long table surrounded by food, drink, and hangers on. He is quite drunk and regaling his entourage with tales of his latest commercial success. From what the players overhear, it sounds quite lucrative, but also quite shady.",
    "Gerwin and Garmin Flinthammer are dwarven blacksmiths who've lived here their whole lives and inherited their fathers forge. Both dwarves fell in love with a beautiful woman. They had a falling out over her leaving town after they both proposed to her. Gerwin sold his half of the business to a local merchant who then swindled Garmin out of his half as well. They have been known to brawl in the tavern after a few too many pints.",
    "Cornelius Coppertop Halfling artificer/rogue made a fortune manufacturing iron cookware. 'No pot like a Coppertop' is a well known slogan in his hometown/country. Bored with his life as a magnate he went halfway across the world to look for adventure. Uses an iron pan as a melee weapon.",
    "A pair of drunk halflings are playing darts, but instead of playing for points they seek to one-up each other with the most ridiculous trick-shot that still hits the board. Currently one of them is trying to hit the board after donning a blindfold and being spun around on a barstool, they are however way off target and pointed right at the party.",
    "Larry is a Djinni who resides in vessels of alcohol. Larry LOVES his alcohol. While generally pleasant, Larry is shy, and doesn't often speak to those who are not known to him or a threat. Larry does not like being drunk (well, he likes being intoxicated, but doesn't like when others drink him.), though drinking any alcohol from a container which Larry currently resides in will grant a random magical effect to the drinker. Larry wishes to travel the world, and reside in fine alcohols of all types and descriptions. The more alcohol in his container, the happier he is! Larry, despite his good spirited nature, and clear arcane power, does not grant wishes. If you attempt to ask him for a wish, he will go on a drunken rant about why your wish is stupid and not what you want, and why he won't do it.",
    "A cute couple who call each other: 'Pumpkin' and 'Bunny'. They may or may not be secretly packing a pair of high-powered wands.",
    "Two normally well-dressed gentlemen forced to dress as peasants, escorting a portable writing desk constructed of wood, leather, and brass clasps, filled with 50 lbs of gold bars (25,000 gp), along with diabolic contracts for the eternal souls of several high ranking nobles.",
    "A lanky, shaggy ranger who favors a green tunic, and his talking great-dane. The former is asking the proprietor for something 'vegetarian'. The latter is begging for bar-snacks from nearby patrons.",
    "A young, well-endowed red-headed female cleric of Sune, wearing purple and lavender robes.",
    "A young, brunette, spectacled, female scholar wearing robes of brown and orange.",
    "A young blond paladin wearing a white tunic, blue pants, and an orange ascot. They are currently advising their friends that 'They should split up and search for clues'.",
    "A green-robed young wizard with spectacles and a rumpled, green, pointed wizard hat. If asked about magic, they will reach into their hat and pull out something, and then be amazed by it actually working! 'I was trying for a rabbit, but this works too, I guess.'",
    "Two dark clothed bards wearing dark smoked-lensed glasses indoors. They are brothers, and are 'On a mission from the gods.'",
    "A foppish gnome with a wire-stiffened top-hat taller than themselves, and a pair of waxed handlebar mustaches. They seem quite particular about everything, and are demanding their tea be exactly a certain way.",
    "A sweaty, muscled, bigoted oaf with a handlebar mustache, who smells of meat; complaining about immigrants, while attempting to pass themselves off as an erudite gentleman. They are wickedly vicious with a dagger, and can throw a meat-cleaver like no-one's business. His top-hat has a torn top-flap and looks to have been run-over by a wagon.",
    "A dim-witted brute with ashy gray skin, holding a large crystalline bowl of water and two beautiful koi. The koi can speak telepathically, and command the brute to do various things. Currently the brute is feeding one of the fish peanuts.",
    "Dave, the depressed gnome wizard is not sitting in a chair but constantly hovering a few feet off the ground. You can see in his eyes he is an overworked man struggling with motivation. When approached for conversation he teleports himself to the other end of the bar, evidently too lazy to walk. Intriguingly powerful and highly in need of some excitement in his life, you approach him again.",
    "Jack Marris - A surly middle-aged human that works the stable at the local farm and moonlights as a smuggler.",
    "Bleak Zazz - A pale lizardman that is rarely seen during the day, some believe him to be a vampire and the strange rituals he performs at night don't help his reputation.",
    "Merill Millstone - A beautiful elven woman who manipulates lecherous men using enchantment and illusion magic to empty their wallets before their heads hit the pillow.",
    "Glen Goodwill - A merchant that collects and sells donated items and equipment, most of it is second hand junk.",
    "Jerry Baritone - A charismatic bard that runs organized crime in the local town. He never travels alone and owns the tavern you're in now. You probably won't get a meeting with him without reason.",
    "Vylwin Qinolor: Surrounded by fawning sycophants a loquacious elf dressed in wine stained finery holds court in one corner of the room. Vylwin Qinolor is insufferably arrogant, unfortunately deservedly so. An oracle savant, everything they say is actually right! However it is at best a fruitless task to turn the conversation toward a useful topic. At worst one earns a brutal haranguing exposing their darkest secrets and deepest fears.",
    "A tiefling who's left horn is broken and the same side of her face has a burn scar. She sits in a corner with her good eye casually watching the other patrons and enjoying a drink. Three drinks sit on the table at the empty seats around her and no one seems to be joining her.",
    "A minstrel sings a tale of heroes that sound eerily similar to the party, but in a battle or situation that they haven't experienced. (Yet?)",
    "A happy couple of Elves sit in a booth side by side. Every time you glance toward them it seems like they've switched places. You could have sworn the woman was sitting on the right just a second ago...(they are shapeshifters playing a harmless prank on the inebriated patrons. If confronted they will flee.)",
    "Brother Tondbert: A mendicant who preaches the benefits of sobriety and a fibrous diet during the day. At night he can be found sulking at a shadowed table supping on tepid broth and nursing a small beer as these are the only lodgings he can afford and the water here is more likely to poison you. Wisely, he does not espouse his beliefs in this neighborhood.",
    "Stinky Pete: A local swampy druid man that comes to the tavern round the evening, he's too nice for people to ask him to leave, but he's kinda smelly and covered in gunk.",
    "Murrian Markimer: an old adventurer who complains about how adventuring was better in his day and how every adventuring party gets it so easy with these 'exotic races' and 'easier options'.",
    "Morra and the fantastic Jimminy: a wood elf lady and her ventriloquist dummy who argue with each other and make jokes at the expense of other patrons. The puppet resembles a wood elf wearing a pink tunic.",
    "Stefan Shacklemann: a loyal bar patron who drank till he died, his corpse is on display and his ghost still sits on the same barstool everyday.",
    "Groton Rumpleskins: a hag who accidentally turned herself into a talking frog, she occasionally tells desperate men that she is a princess that'll turn back once kissed.",
    "Manny: a completely normal seeming guy that shows up and leaves the tavern everyday at the same exact time. In reality he is a time wizard that has nothing better to do between 12 and 4.",
    "Chad Ironbelly: the man who can drink you under the table, getting into a drinking contest with him is risky business, if you somehow make it past 10 shots and then fail you will wake up somewhere else within 2 miles of the tavern.",
    "A half elf bard who looks like a dwarf. They were a former adventurer and will tell tales of their journeys to other patrons.",
    "Brenk Stillwall: A mul (half-dwarf) who, despite his short and stocky stature, vehemently denies having any dwarven blood in him for whatever reason. Gets angry if anyone keeps asking or suggesting it.",
    "Merrvin: A tiefling who loudly berates and insults the tavern staff while telling his clearly uncomfortable friends that this is how one gets good service from taverns.",
    "A nameless monk sitting alone with a large bottle of snake liquor, willing to challenge anyone to a drinking competition (of which he’s never lost).",
    "Tanis: a young, trendy elven bard with a magical sitar. She’s traveling to meet “an old friend” although a successful insight check implies her tone reflects something sinister (From House Thurianni in an Eberron campaign).",
    "Leona and Jacques: Human siblings, adolescent to young adult in appearance. They are convinced that there is a deadly specter haunting the tavern and that it will strike again soon. Alas due to their age the tavern proprietor does not care for their disruptions nor their presence and dismisses any evidence of the 'specter' as rowdy patrons, pranksters or incompetence of his own staff. The two kids however are committed to eliminating the otherworldly threat and saving lives.",
    "Two unnamed young ladies, attractive and dressed provocatively in matching dress, are walking around the tavern, all smiles. One carries a tray of small goblets and the other is handing out small pamphlets. They're promoting a new brewery that's started delivering in the area. Although innocuous at first, the two are searching for someone. One of the goblets contains a slow acting agent that can cause adverse effects to anyone that ingests it. They are certain their target is a patron in the tavern that night.",
    "Tiffania: A smiley woman in ruffled skirts that jingle from the coins sewn onto them and the many bangles on her wrists. Her long black, curly hair cascades down her back. She has a striking, but knowing look. Never giving anyone an unfriendly glance. She'll tell the party their fortune, for a coin. She may warn them of dangers, friends or forked roads ahead or the cards may hold inspiration for the lucky few.",
    "Zed: A loxodon dressed in black leather. He's very, very tall and trying hard to slink into the shadows. It's not working great. With some persuasion and alcohol it will be revealed he's a master rogue and has some excellent sleight of hand skills. What may not be clear to the party immediately is that the loxodon is a highly wanted criminal for numerous heists and robberies where items were stolen without so much as a trace of evidence. He's the best in the business.",
    "Bork: A dwarf in mismatching religious garb. He has several religious insignias attached to him around his neck, to his belt, to his pack and wherever he could squeeze one. He looks like a cleric and if spoken to will claim to be one. If the party ever sees him heal, he will be shown to be an eldritch knight. He has no healing spells. His only castable spells are burning hands and ray of frost depending on how much 'holy power' is used. He blames everyone but himself for the healing spells failure.",
    "A tired looking gnome comes into the bar and requests one and a half pint of the cheapest alcohol. When he enters, the room hushes for just a second. If the party asks around, the most they get is his name, Solomon Grundy, and a warning to never fall in love with him. If the party speaks to him directly, he's a very affable fellow, and generally quite lovable. A shame he only has a week to live.",
    "An almost strangely pale human woman with a green ribbon wrapped around her neck sits at the corner of the bar (or, if it's occupied, alone). She smiles too slowly, her movements are gentle and languid, and unnerving. She introduces herself as Jenny, and at some point excuses herself and tells the party she needs to go back home to her husband, Arthur.",
    "Alfred Talos—Halfling scribe who sits at the bar with his massive pack and always furtively scribbling something. He wants to be a writer (he currently has a book out, Talos' Guide to the World, an untrustworthy and ramshackle travel guide with many insights into the man himself, for 5gp) but currently he's stuck balancing books for various thieves' guilds, stores, governments. Despite his terrible travel guide, he does actually travel quite a bit and would serve as a good pot of plot hooks or worldbuilding.",
    "A human in almost garishly expensive-looking clothes sits at a booth (or, if the tavern doesn't have booths, the least-gross bar chair) with a massive sack of gold at his side. His name, if you talk to him, is Darvin Helder, and proclaims he's drinking because he just got paid (hence the heavy bag). If you tell him that's not a good idea or warn him about thieves, he comes in close and whispers to you that it isn't actually full of gold, but that the barkeep treats you better if it looks like you're wealthy. Later, when Darvin is gone, other patrons come to ask you if he tried to sell you insurance; turns out Darvin is a notorious insurance conman, and that he's so ridiculously well-insured that stealing from him is both pointless and will just get you into trouble with the local thieves' guild. Still, many townspeople hold a grudge towards Darvin, including the mayor (or other community leader)...",
    "Horgrum Guldentoothe: Boisterous, bald and bare-chinned yet sporting an impressive pair of friendly mutton chops, Horgrum Guldentoothe is a heavily tattooed dwarf of prodigious girth and an even bigger grin. Horgrum does, in fact, have at least one golden tooth as well as several golden piercings, rings and bracelets. The bosun of The Bashful Rose ambles around the room promising that 'The Sea, She'll make a man o'ya.' and offering to 'Buy a pint o'rum for the lads here.' Many a 'lad' has awoken sea-sick and far from home to find Horgrum a stern, but fair taskmaster.",
    "Shtoggle, a half-orc man who pretends he is just a stocky human. Paints his face tan and wears a beard. If mad, he will slip to more orcish behavior, but otherwise picture a person poorly imitating Shakespearean plays.",
    "Glorhock, a half-orc man, pig farmer and expert butcher. He wears grimy overalls and muck-stained boots, and will drink you under the table.",
    "Zagan – An elderly human man sits alone in a corner, sometimes with a mug of ale in front of him. If he doesn’t have a mug and one of the PCs gives him money, he will perk up and tell his story to the party. He claims to be an adventurer from a distant land, who got stranded in this city after the rest of his adventuring party died in a nearby dungeon. Other tavern patrons will tell the PCs that Zagan is a liar and a fraud, his “accent” is fake and that he grew up on a farm outside town, and his real name is Will. The story can be somewhat outrageous and over the top.",
    "Xanthiss: A dark green Dragonborn man sits at a table in the shadows. Half his face is covered by a porcelain mask. Underneath the mask, he bears horrible scars from a tussle with a displacer beast. He keeps mumbling to himself and clicking his claws together in a neurotic fashion, drawing stares from the other patrons. A little bit of a nutjob.",
    "Two rival groups of theatrical players, the Strolling Players of the Dukes' Pleasance and the Earnest and Complete Company of Summer Gentlemen. John Truewand, the leading player of the Strolling Players, has very recently left the Strolling Players and joined the Complete Company. The members of the Strolling Players are very, very upset about this betrayal, financial, personal and to the Muse.",
    "Strakx Hummingblade - A commoner trying to drink away her sorrows, expressing how her parents want her to marry some handsome noble, while in reality, all she wants to do is join the church and tend to the wounded, with or without magic.",
    "Splitz (the Unfortunate) Herald - A man who is notorious in nearby cities for his great gambling streak, rivalling the wealth of the towns' nobles, only to lose it all when trying to bet all-or-nothing. To this day he still begs on the streets, becoming a street performer moving from city to city and gambling all of his money away time and time again, hoping to one day have another great win streak.",
    "A fey creature nicknamed Herb Robert, and amongst the Thieves' Guild as 'Death-Comes-Quickly', known for their herbal-teas (and medicine), as well as selling Halfling Tobacco, all of which they grow behind their establishment elsewhere in town. A well dressed, foppish, sociable creature; well connected, is enjoying a fine brandy while apparently waiting for someone. In the guild, they are viewed as a neutral intermediary involving assassinations, making 'house-calls' to establish business, under cover of social calls to the well-heeled or nobility. They are known for wearing a sprig of Geranium Robertianum (It actually grows from their body) and favoring a strange perfume or scent matching that of the aforementioned plant.",
    "Doctor Flugel: A gnomish medical professional, and known (or at least rumored to be) resurrectionist (corpse-stealer) along with two rough looking associates and a highly inebriated but distraught young peasant. The associates are plying the young peasant with drinks.",
    "A cloaked figure sits in a shadowed corner, hood up, flanked by two bulky male bodyguards. The serving wench comes by with refills and as she turns to leave, her foot gets caught on the cloak's hem, pulling it open for a brief second. The ornate basket guard of a rapier is noticed on the figure's hip, which is completely out of place for this dive bar.",
    "Three Gravediggers toasting one of their own, who has recently passed.",
    "A silent, brooding undertaker (in dark clothes and tophat) who is bald and extremely tall, along with six pall-bearers (in dark clothing), and an ornate but empty coffin which the pallbearers and undertaker are using as a seat. All but one of the pall-bearers are silent, one speaks freely and is ordering for their fellows. It seems a local noble's funeral was called off because the family bribed the local cleric to resurrect the dead.",
    "Three bards getting uproariously drunk. Each has a unique, broken musical instrument, and torn costume. They give their name as High, Higher, and Highest. The one named Highest is the shortest."

    ]