var curious_items = [
"Telescopic Pole – a three foot bamboo rod that telescopes to ten feet.",
"Umash Teeth – the upper sixteen teeth of one of the baboon-like Umash in a leather bag, a divinatory aid.",
"Red Fireflies – glass bottle of the red light-casting waste fireflies, their light is capable of revealing certain invisible creatures.",
"Heavy Tinted Glasses – goggles made from darkened glass, excellent eye protection from bright lights.",
"Prizing Knife – short curved blade designed to open shellfish and hook out their meat.",
"Tuning Tines – twelve inch amask steel acoustic resonator.",
"Hrassacock Feather – the uniquely beautiful red, blue, green, and yellow tail plume of the hrassacock, a much desired hat decoration and magical component.",
"Small Accurate Map – very detailed map of a random nearby location.",
"Umash Kakuluk – medium sized bongo instrument.",
"Fasinaa Reed Flute – nimble instrument that produces flute and kazoo type sounds.",
"Goboda Bwamanna – three-stringed gourd instrument.",
"Spidersilk Rope – fifty foot length of excellent quality weave.",
"Flask of Jen Jandy – plain flask full of highly alcoholic spirits, has a flavor similar to spicy root beer.",
"Bottle of Lo Plum Wine – sweet soporific wine made from the fruit of the Lo plum trees that grow in the southeastern delta land.",
"Bag of Blue Herbs – one eighth of an ounce of smokeable herbage, analgesic, promotes feelings of well-being.",
"Fasinaa Machete – finely built steel machete, perfectly suited to hacking through the sticky eastern jungles.",
"Plush Peeper Doll – a child's wool-stuffed toy made to (poorly) resemble one of fluffy mountain prosimians called Peak Peepers.",
"Agate Marbles – fifteen blue, brown, and orange marbles, one slightly larger than the rest.",
"Vuus Hair Thread – spool of incredibly fine thread made from the hair of the Vuus tribe of iele, strong enough to fish with.",
"Violet Lady Mushroom – single fast-acting psychotropic mushroom, maintains potency if carefully dried.",
"Dried Spirit Pepper – a pungent chili spicy enough to burn in the ethereal plane.",
"Animal Pheromone – the concentrated musk of a random animal from a nearby environment.",
"Sea Salt – leather bag of crystallized sea salt, about two cups worth.",
"Umash Crackle Sticks – three somewhat dangerous “sparklers”.",
"Female Hensnake – two foot long tubby-bodied domesticated snake, lays one delicious unfertilized egg once each morning.",
"Cuttle Ink – blue-black writing ink harvested from a coastal cuttlefish.",
"Finely Carved Walking Cane – cane made from rare wood and carved with tiny scenes of decadent city life.",
"Shard of Cursed Glass – radioactive material from the Glass Waste, only dangerous if held over the course of years.",
"Lodestone – fist-sized rock with a powerful magnetic force.",
"Merchant's Scale – portable bronze scale with a selection of weights, all contained in a ten inch wooden box.",
"Large Inaccurate Map – poorly detailed or scaled map of a random nearby location.",
"Ceramic Pot of Lolsanthi Honey – quality honey harvested from the bees pollen-maddened by Lolsanthi nectar.",
"Crystallized Sugar – small packet of sugar crystals, attracts insects.",
"Fetish Doll – crude humanoid figure with a set of pins, currently unattached to a victim.",
"Barbed Fishing Net – thrown fishing net with barbed iron hooks.",
"Ara Leaf Oil – insect repellent made from the Ara bush.",
"Set of Gaming Dice – three six sided bone dice.",
"Seeing Tube – primitive telescope, one end makes things look smaller, one end makes things look bigger.",
"Solidified Amber – an insect trapped within hardened resin.",
"Resin Incense – a small wooden box of rich-scented incense with a heavy languorous smoke.",
"Colored Chalk – set of five different colors.",
"Fur Blanket – heavy blanket made from woolly rhinoceros hide.",
"Oyeb Seeds – pouch of the incredibly fast growing oyeb vine, a strangling gourd.",
"Nuncia Bird – tiny message carrying bird.",
"Puzzle Box – small simple release wooden puzzle box.",
"Hollow Bracelet – copper bracelet with a secret compartment.",
"Oiled Hooded Cloak – nearly waterproof cloth outer covering.",
"Lye Soap – large bar of harsh soap for serious washing up.",
"Pallenseil Poppy Seeds – from the eastern plains and hills, can be planted or eaten as a pain reliever.",
"Minor Noble Finery – association with a random noble wizard house.",
"Sachet of Scouring Sand – razor sharp particulate, good for permanently damaging eyes or lungs.",
"Cloud Lotus Powder – when made into tea or a paste for the chest brings a heavy, restful sleep impossible to resist.",
"Tapping Spile – a steel tap that can be pounded or drilled into liquid storing vegetation.",
"Heavy Heat Resistant Gloves – insulated hand wear able to resist heat and open flames.",
"Wooden Yoyo – carved wooden toy, useful as a diversion or an improvised weapon.",
"Quartz Prism – five inches of clear, faceted quartz crystal.",
"Low Quality Rickshaw – foot powered conveyance for a single passenger.",
"Presis Conch Shell – beautiful pastel colored sea snail shell, nearly as large as a man's head.",
"Vial Necklace – chain necklace with a metal vial that can be filled with a small amount of powder or liquid.",
"Clay Funerary Mask – placid and nearly featureless white clay funerary mask.",
"Deck of Divining Cards – most decks contain only the prime arca, the face cards.",
"Loppett Shears – wool cutting scissors used to shear herds of loppetts.",
"Three Small Colored Bean Bags – good for juggling or kicking about.",
"Raku Tea Set – simple but beautiful teapot and cups for two.",
"Back Strap Loom – personal and portable loom.",
"Idol of Se'vensaera / Immacula – lapis or jade idol of one of the more hopeful of the eight goddesses.",
"Dry Compass – sensitive portable compass.",
"Pack of Dominoes – twenty eight gaming bones.",
"Skywatch Pamphlet – detailing the threat of the Shem and the city's complacency.",
"Stegotetrabelodon Ivory – six inch piece of uncarved elephant kin ivory.",
"Shrunken Iele Head – the dried and shrunken head of an iele man, created by a remote tribe to trap the soul.",
"Bronze Oil Lamp – oil burning decorative lamp in the Form of Naude, goddess of mysteries.",
"Abacus – stone beads in a wooden frame.",
"Bronze Hookah – decorative bronze personal hookah with snake skin hose.",
"Stuffed Tree Shrew – taxidermy of a fearsomely posed omnivorous tree shrew.",
"Tinderbox – flint, pyrite, and amadou.",
"Wax Tablet with Iron Stylus – re-writable surface and implement.",
"Iron Choke Collar with Leash – good for medium and some large size animals or people.",
"Sack of Sponges – large cloth bag full of dried natural sea sponges.",
"Tin of Bitumen – small container of viscous tar.",
"Song of Hours – carved, words and music, into a wooden cylinder.",
"Cipher Key – simple code based on the iele common language.",
"Barbed Iron Arrowheads – five wickedly hooked arrowheads.",
"Bag of Snake Vertebrae – nine of the bones in a felt bag, used for divining.",
"Performance Cosmetics Kit – bold makeup including face white, rouge, and kohl.",
"Leg Irons – reinforced steel leg restraints, able to fit any medium sized humanoid.",
"Mamun Coin – a large gold coin from an ancient civilization, one side shows the sun, the other a man's face.",
"Fief Farm Bell – small but loud bronze bell commonly used to keep track of domesticated animals like loppetts or crenchies.",
"Medicinal Leeches – glass jar of “polite” leeches, applying one to a fresh wound will drain venom.",
"Stone-working Chisels – four chisels in various sizes with various heads.",
"Jeweler's Loupe – low quality single eye magnification device.",
"Steel Crampons – sharp and sturdy steel crampons.",
"Rolling Stone – an insect larva encased in stone, rolls the stone around when hot enough.",
"Bird Cage – finely woven wicker animal cage, capable of holding up to three tiny creatures.",
"Container of Grease – oily animal fat grease.",
"Pamphlet of Minor Sigils – protections for the common man.",
"Goboda Relic – a tarsal bone of a minor saint, a blessed traveler who fell while walking the great wheel.",
"Skeleton Key – generic key that will unlock a family of simple locks.",
"1. A miniature crystal – small enough to lie upon the outstretched finger of a halfling child – glowssoftly, and pulses whenever an object colored red is brought near.",
"An ancient, leather-bound volume written in an archaic script describes the composition andarrangement of the Outer Planes. Strangely, a rather substantial section of text – consisting of anentire chapter if you are translating the numbering correctly – has been torn out of the book. Despite this fact, you can detect no obvious gaps in the volume’s coverage of its subject matter. What unknown plane did that chapter describe?",
"A tattered, and sadly unusable, scroll fragment, inscribed with a spell unknown to any living mage.",
"A plain, and otherwise unremarkable, stone room contains one remarkable feature: Upon the floorshattered, multi-colored shards of glass have been carefully arranged into a perfect circle.",
"A weatherworn wooden board, inscribed with patterns which make it clear that it was once used fora game whose rules have long since been lost to time.",
"A clock which regularly keeps time… just not the time of this world. Although it is clear that theclock works to a clear pattern and purpose, attempts to decipher the method of its madness fail – as ifit had been crafted upon rules of logic which no human mind can comprehend.",
"A blood-stained dress which, despite being found in ruins which have lain undisturbed for centuries,is still a vibrant, stunning blue.",
"An elegantly carved comb of oak, engraved with the name Aethelren and decorated with twindragons. Elsewhere, a similar comb of ash, engraved with the name Ilthorien and decorated withtwin unicorns, can be found.",
"What appears to be the original, handwritten manuscript of the Saga of the Warrior Prince Augustin – aclassic ballad composed by the legendary bard Dathorn, famous for its lyrical quality and epicsubject matter. A careful perusal of the text, however, reveals strange differences from the version ofAugustin known to the bards of today…",
"A broken holy sword, inscribed with the name of a legendary Paladin.",
"A ruby the size of a man’s fist which sparkles and gleams with the promise of untold wealth in thefaintest of lights, but which crumbles to dust upon the lightest touch.",
"A child’s poppet which is normal in all respects, except for the third eye to be found upon itsforehead.",
"A long, black lock of woman’s hair, tied with a scarlet ribbon. When touched by human or elf,however, it changes color to match the holder’s own hair color. When touched by a dwarf, a screamof utter agony and anguish fills the air.",
"The holy symbol of a god long thought dead and gone. Although wrought in iron, it resists anynormal attempts to damage it.",
"A map of a city which claims to be of a city the PCs know well, although the pattern of streets andnames on the map are utterly different from the city of today.",
"A collection case holding fifty spent wands – crafted by the finest craftsman and enchanted by themightiest wizards of a bygone age, but now reduced to mere wood, bone, and glass.",
"A small, granite pebble which registers faintly to detect magic and similar spells, but which isotherwise wholly unremarkable.",
"A cane of the purest white ivory, decorated with ruins unknown to modern scholars, and toppedwith a handle of polished amber. Trapped within the amber is a strange creature unlike any the PCshave ever seen before.",
"A miniature, mechanical model of a city. When properly wound, its complex mechanisms set its tinyinhabitants into motion, simulating for them a rotating cycle of activities which last for seven daysbefore seamlessly repeating.",
"A telescope of jade and banded with bloodstone. A character looking through the telescope sees notthe world around them, but a strange, alien vista which – nonetheless – follows the motions of thetelescope.",
"A large snow globe, with a sturdy base of polished oak, depicting a small farmhouse in the midst of aforest clearing. Shaking the globe causes the snow to gently fall, and as it does miniature figures exitthe house and begin performing chores about the farmyard. The figures return to the house as thelast flake falls.",
"A wood chip which acts as a magnet, despite its non-metallic nature.",
"A broken music box which still plays a hauntingly familiar, but unrecognizable, tune if it is woundbeneath the rays of the full moon.",
"A complex set of interlocking gears which, if followed by the eye, seem to… twist at some point, as ifthey were not strictly bound by the geometry of this world. Although the device functions as aperpetual motion machine, it is not magical in any way.",
"A finely crafted compass of gold and silver, decorated and labelled with ornate, dwarven anddraconic runes. Once every 1d4 hours it randomly changes the cardinal direction to which its arrowpoints.",
"A small ball of white marble – roughly three inches across – which hovers in the air until it is touchedor disturbed, at which point it falls to the floor and ceases to exhibit any supernatural properties.",
"A sundial which runs backward.",
"A bowl full of golden apples found in the midst of ruins which have long been left desolate anduninhabited. They are quite edible and unspoiled. If they are taken beyond the ruins, they will losetheir golden sheen and appear – in all respects – as normal, red apples. So long as they remain withinthe ruins, however, they are golden, and will not age or rot.",
"Within an elegant hinged case of black onyx, the characters find a set of masterwork gaming darts.Although useless for combat, the darts will give a +2 skill check bonus to anyone using them to playa game of darts (due to their superb balance and construction).",
"A lucky rabbit’s foot which hangs from a golden chain. Although separated from the rest of therabbit, the foot magically lives on: It will respond to touch, bleed if injured, and so forth.",
"A decorative fountain, crafted elegantly from a single block of jade and decorated with gold leaf, inwhich the water flows in the wrong direction.",
"A plain mirror with a frame of pale ashwood. Whenever someone looks in the mirror, however, theyperceive an elven face in place of their own.",
"A ring composed of a simple gold band, inscribed with a complex set of blackened runes, whichappear to signify nothing at all.",
"A large tome, bound in leather and clasped with gold. A closer inspection of this volume will revealthat each page is a perfectly preserved dragon scale, which has been inscribed with the black blood ofa fiend. The book describes the four spirits (quicksilver, orpiment, sal ammoniac, sulfur) and sevenbodies (gold, silver, iron, quicksilver, lead, tin, copper) of traditional alchemy.",
"A large spectacle, designed for a creature possessed of only a single eye in the middle of their head.",
"A peg leg inscribed with a pirate’s treasure map. The map is either false or its treasure has long sincebeen plundered. If you wish to provide the PCs with a true map, then one may be found in thehollow compartment within the leg.",
"A small ivory case, filled to the brim with the wings of fairies.",
"A delicately carved hope chest of polished cherry wood. The box contains nothing but a remarkablyfine, gray sand drawn from some unknown locale. Beneath the new moon, this sand glows a faintblue.",
"A small, heart-shaped token carved out of rose-colored sandstone, holding the mad soul of a princesswho was trapped there by a sorcerer many centuries ago. Her body remains in the hidden royalsepulchers of her homeland, perfectly preserved by ancient magic.",
"A prismatic crystal which echoes back – in a deep, melodious voice – every word which is saidaround it two seconds after it has been said.",
"Within the ruined remnants of a ruined fireplace, an everburning flame still flickers with eternal life.At night, the light of this flame dances across the ghostly forms of those who once lived in the roomthis fireplace once warmed.",
"A disk of finely polished stone. On one side, the elvish rune for death is inscribed in blackestobsidian. Upon the other, the dwarven rune for life is inscribed into the palest ivory.",
"An ancient waterwheel which rests within a dry riverbed, but which still turns with a creakingmemory of its ancient motion.",
"Deep in ruins which predate the characters by generations, they uncover a forgotten account ofhistory. Anyone familiar with the kingdom’s history who studies this text will find references to aking who has apparently been excised from the modern records.",
"Two disks of hardened quicksilver laying atop one another. If they are separated, a tornado springsup between them – anchored on each end to a disk.",
"Only a few crumbling bricks standing in the midst of a grassy plain stand as testament to what oncemust have been a mighty wall. Looking through a small chink in this wall, however, reveals not theplain which sweeps away upon the other side, but, instead, a strange desert with dunes of multicoloredsands.",
"A mask carved to look like the face of a man, but which has been fitted for something wholly other.",
"Coming to a door which has long been sealed, the PCs find a tiny toy soldier which marchesceaselessly back and forth – eternally vigilant against those who would disturb his portal.",
"A statuette of a dragon, forged from the finest mithril, which responds to yes or no questions whichare posed to it in draconic. The answers given may appear prophetic or oracular, but are actuallyrandom.",
"The Erian Tapestry. A famous (or forgotten) tapestry depicting the Fall of Erian. The figures upon thetapestry move and change, re-enacting – in an artistically abstracted form – the legendary battle overthe course of half an hour.",
"A miniature model of a pyramid, which glows a faint blue. If a deceased creature of Diminutive orFine size is placed beneath the pyramid, they will be reincarnated in 1d20 hours. The pyramid canmanifest this ability once per lunar month.",
"The tiny figurine of a fertility goddess, carved from a rare, fist-sized pearl. Found deep beneath thesurface of the earth, for two weeks after it is brought to the surface any woman touching the figurinewill become pregnant. After the two week period has expired, the figurine will never work again.",
"A coil of rope spun from the black hair of an elven maid.",
"A door which, when opened, reveals nothing except a bare wall of stone.",
"In the depths of the forest, the characters stumble across an ancient, weather-worn jade statuedepicting a desert beast known only to the people of the far south.",
"A jet of flame, tapped from some primal source beneath the earth. Only that which is good can passthrough this flame unharmed. All others are dealt 15d6 points of damage as per a flame strike spell.Non-aligned items and equipment are left unharmed.",
"An obsidian figurine of a dolphin which is always wet to the touch.",
"A hard, roughly cut piece of basalt rock which bleeds when pressure is applied to it.",
"Two six-fingered gloves, along with a matching seven-fingered glove. The set is made of suppleblack leather, and stitched with fine, silver thread.",
"A horn fashioned from the translucent bone of a storm giant. Those who put their ear to the hornhear it whisper the sounds of an unknown village square. Whether the village which they hear is – orwas – a real place is a mystery which may never be solved.",
"The silver hilt of a sword with a grip of black leather. The blade is missing, or never existed to beginwith. One night per year, however, on the eve of the new year, the hilt is possessed of a ghostly blade– allowing it to perform its duties as a sword once more.",
"An elegant puppet theater. Although its wood is brightly polished and the red of its satin curtains isbright and fresh, the hand-painted sign upon its front (reading The Wondrous Shows of Punch and Judy in carnival lettering) is chipped and faded. If the curtains are opened (using a set of finely woven pulley ropes which lie inside the theater), the puppets – stored in a concealed compartment backstage – will come to life and perform elaborate shows of their own volition.",
"A plain, unadorned black obelisk. If brought above ground and into the open, the obelisk will drawdown a near-constant barrage of lightning to itself – even if the sky is clear.",
"The remnants of a massive door of stone which has been smashed into rubble. A magic mouth whichhad once adorned the door remains intact. As the PCs draw near it will issue its warning: Disturbnot this chamber, lest the world suffer. Whatever the mouth was set to guard is gone – the chamberbeyond the broken door is empty.",
"An astrologer’s chart, inscribed with the finest instruments and the greatest precision upon a vellumwhich is both supple and expensive. Close inspection by those with the proper knowledge, however,reveals that these charts were constructed around an entirely different night sky – and, possibly, acalendrical system and length of year unlike anything known upon this world.",
"A large signet ring of gold, worked with a unicorn crest. Any commoner who dons the ring willsuddenly discover its metal heated to unbearable levels – causing one hit point of damage per round.However, anyone with noble blood (however slight), or destined to become a noble at some point inthe future, who does the same will suffer only a momentary flash of pain (with an accompanying 1hp of damage): They will find that the unicorn crest has reshaped itself to their own heraldry, whichhas also been branded in miniature form upon the back of their finger. From this point forward, theycan put on or remove the ring at will without any further ill effects.",
"A pen made from a raven’s feather. Through some magical means it writes continuously from aninexhaustible supply of golden ink upon whatever piece of parchment may be near by.",
"Mechanical mice which run through the walls of an ancient keep. They have done so for longer thanwritten record can attest. They seem to be a benign presence – lacking even the slightest pestilentqualities of their flesh-and-blood counterparts – and have become an accepted presence here. Whotheir creator was, how they are fueled, and what purpose they serve (if any) are mysteries which maynever be solved.",
"A clairseach harp in the style of the northern barbarians, but crafted with an elegance which suggeststhe decadence of a great civilization. Its strings are almost too fine to be perceived with the nakedeye, and when they are played they resonate with the force of a full orchestra.",
"In a worn and decaying wall of mud bricks, a single black brick – polished and perfectly preserved –stands out in stark contrast. If the brick is pried out and broken open, it will reveal a quicksilver core.",
"A tome whose pages have been yellowed with age and used to press metallic leaves of gold, silver,platinum, brass, copper, and bronze.",
"An ancient deck of cards with five suits – clovers, swords, clubs, hearts, and dragons.",
"Within a rotten pouch found upon the body of a long dead soldier is a parchment with an unbrokenseal. If the seal is broken and the message read, it warns its would-be recipient to guard against aneminent betrayal.",
"The sapling of a young tree. Within a few minutes it will have grown into a wizened oak. A fewmoments more and the tree slowly fades from existence as a young seedling pushes up from theground and begins the cycle anew.",
"A stone table in the midst of the wilderness which is, nevertheless, always filled with a fresh mealwhenever travelers come across it.",
"Carved into a natural rock face is an elaborately decorated arch. When first seen it appears to bemerely decorative, with the supposed doorway leading into solid, unfinished rock. If the arch isapproached by sentients, however, it will suddenly burst into life with a scintillating array of light.Anyone entering this magical portal will disappear for several seconds before being returned to thevery spot from which they left.",
"A small, leather-bound book filled with prophecies. All of them will be found to be true, but the lastof them is dated just a few weeks ago.",
"The mounted head of a deer, its impossibly massive horns possessed of a thousand and one points.",
"A hollow glass sphere of surprising proportions – nearly three meters across. If it is broken thosenearby will catch the barest scent of alien perfumes, hinting at strange lands belonging to the ancienttime when the sphere was first forged and air trapped within it.",
"A sword of truly mammoth proportions. Resting within a chamber more than thirty meters long, thesword stretches from one end to the other. Whatever creature was meant to wield this mightyweapon would truly stagger the imagination of a dragon.",
"Poison drips – steadily and continuously – from the tip of a stalagmite which stands alone within anatural cavern deep beneath the surface of the earth.",
"Within a wooden box carved with pastoral scenes lies a leather purse, and within the purse are ahandful of seeds. If these seeds are planted, they will take root and grow into plants of unnaturalshape, hue, and life unlike anything seen upon this world, and operating by utterly alien principles.",
"A scabbard stained the dark color of rust. Any blade which is placed within the scabbard will emergecovered in a sheen of blood.",
"A cursed fishing pole made of blackened ash. It will never catch a fish – although, if one attempts touse it unbaited, they will succeed in catching skeleton fish.",
"A bouquet of cut roses which will successively bloom and wilt over the course of a few moments.",
"A disc of gold upon a chain of similar material. It appears, in almost all respects, to be a talisman ofpure good (DMG, pg. 239) – but, in fact, it is a fake. At the DM’s discretion its creators may haveenchanted it as a periapt of health or amulet of health in order to perpetrate their hoax more effectively.",
"A tablet of pure gold, inscribed with the core rites and beliefs of a venerable religion. Careful studyof this tablet, however, will reveal subtle – but important – differences between these ancientpractices and the current practices of the religion in question.",
"An age-worn ivory figurine, which, nonetheless, bears an uncanny resemblance to a young womanthe characters have just met.",
"A tiny diorama made of oak and silver, depicting a prophecy of the last days of the world in vividdetail.",
"A diamond of incredible beauty which slowly shifts its color from the purest white to canary to blueto black and back again.",
"An ancient mummy which was given full burial rites and laid within a stately sarcophagus.Arranged on five pedestals around the sarcophagus are the canopic jars in which the mummy’s vitalorgans were placed. Although the mummy is not of the undead, opening these jars will reveal that itsorgans continue to function: The heart beats, the lungs fill with air and empty again, and so forth.",
"A quiver of golden arrows. They are devoid of supernatural properties, but despite their unusualcomposition will perform as normal arrows would.",
"A leaf from the great tree Yggdrasil.",
"A set of wooden wind chimes which plays a different tune depending upon the direction of the windwhich disturbs it.",
"A charm of twisted black obsidian. Touching the charm unleashes strange, ghostly visions from astrange and alien world – utterly different in every particular, but eerily similar to our own world inits broad scope and form.",
"The neverburning torch. A jet black torch, with an inscription in gold upon its side: Only in your hourof darkest need will I light. All attempts – magical or otherwise – to light the torch will fail, but if thecharacter carrying the torch ever finds himself upon the brink of death, the neverburning torch willflare to life. In the face of a mountain, an ancient stone stairway has been cut. Each step has been meticulouslycarved with stunningly detailed mosaics, but upon reaching the top of the stairs a climber findsnothing but a sheer wall of stone – as if the stair’s makers had been stopped before their work couldbe completed.",
"A set of pan pipes carved from the bones of a unicorn. When played, they do not make the slightestsound.",
"A cache of ancient coins left from the elder days of the world and made by a civilization utterlyalien to the values of today: They are carved from bloodstone, moonstone, and jacinth – withunknown faces and unreadable runes decorating their surface",
"A silver dragon scale that glows in the moonlight. It seems almost as if the scale is trying to get back to it's TRUE owner.",
"A key to a bankbox in a large prestigious bank in a large city far away, and paperwork indicating it has been paid for the next 100 years.",
"A small leather drawstring bag filled with sixteen beautiful turquoise fetishes. There is a note inside from someone hoping to 'meet up for another game soon'.",
"A 3 x 4 x 2 wooden box within which is an ink soaked sponge. Touching the sponge causes inky hand prints to appear on whatever that person has touched for the last hour. The inky prints fade in an hour and can't be washed away. The sponge dries out after one use and must then be refilled with a full vial of ink before it can again be used.",
"A spool of string, glimmering in the most astounding colours. String becomes invisible as long as music is audible.",
"A musical instrument. It's music gets louder everytime you play it.",
"A pair of boots. They're exceptionally easy to put on, but you need to use all of your strenght to take them off. When you are not wearing them, you have an increasing impulse to put them back on. They leave tracks of a random creature, within 1 size class of the wearer.",
"A 4in high wireframe model of a humanoid figure, made out of solder. The figure has an exquisitly detailed copper heart inside the dull ribcage.",
"A feather quill. Anything written with this quill will appear in a distinct and unknown handwriting. This unknown handwriting remains the same, regardless of who is writing with the quill.",
"A large decorative candle. When lit, it gives off an alluring scent which, while impossible to identify, evokes a feeling of nostalgia in anyone who smells it.",
"A nail molded into the shape of a sword with pommel in the shape of a wolf's head.",
"A cup carved from horn which swallows any magical potion or poison poured into it. Once per day the cup can be drunk or from and it will produce the last thing that it swallowed, except for 1 percent of the time it will produce a random other liquid it swallowed sometime in the past.",
"A flute that can either [1 on d6] emit no audible sound (makes the nearest animal hostile), [2 on d6] an extremely high-pitched one, [3 on d6] bass strong enough to cause 1d4 damage in a d6 metre area or [4,5,6 on d6] sound like a regular flute. Hide the rolls.",
"A coin pouch. It sounds, weighs, looks and feels like it's filled with coins, but upon opening it you discover that it is empty.",
"A single arrow. It cannot be snapped, dulled or broken. Other than that, it acts like a regular arrow. The person who found it always manages to find it after firing it.",
"A small bottle of clear liquid labeled Knowledge, only use in an emergency.",
"An blue orb that when shaken causes a light snowfall 15 feet around the player who shook it.",
"An elaborate fountain pen that turns into a snake and slithered around when not being used.",
"A needle that becomes immovable when the command word is spoken. (You don't know the command word.)",
"A horn made of ivory, instead of sound it produces wind",
"A pair of stone sandals, they are more comfortable than any shoes you've worn thus far.",
"A small flat stone that sticks to whatever it touches.",
"A piece of twine that when plucked produces a low tone.",
"A pair of leather gloves, when worn you can not touch anything with them.",
"A obsidian comb that makes hair curlier when used.",
"A marble that rolls towards the closest female/male of your species.",
"A small mouse that can talk to you with telepathy. (Dc 10 animal handling to befriend it, or it shouts obscenities in your mind.)",
"A thimble that cannot be crushed by any means.",
"A flaggon that constantly sweats ale.",
"A flask that can capture any scent when the command word is spoken, and the release it when it's spoken again. (You know the command word.)",
"A pair of goggles that look stylish on only you.",
"A set of small metal balls that vibrate when touched together.",
"A glass bottle with two openings. Things can only go through on end and out the other.",
"A small drum that when held slowly beats with your heart.",
"A glass finger that causes painful headaches when in your possession for more than 24 hours.",
"A beret that when worn causes peseants to refer to you as colonel.",
"A loin cloth that constantly blows gentle as if it was in wind.",
"A coin purse that sounds, and feels like it's filled, but is not.",
"A quill pen that can write in the air. (Requires ink and lasts 24 hours.)",
"A piece of paper that writes back to you when you ask it questions.",
"A roc talon that grips objects and never lets go until the command word is spoken. (You don't know the command word.)",
"A leaf that is perpetually on fire, the flame cannot spread and illuminates an area of 10ft.",
"A locket with a picture of a person you vaguely remember, each time you close it the picture changes.",
"A glass orb with a tiny dragon in it. The glass orb can not be broken in any manner, and the dragon connot die. The dragon does react to stimuli and can speak.",
"A feather that is hot to the touch.",
"A vial of viscous blue liquid, when poured out the liquid slowly creeps back into the vial.",
"A potion that changes your gender for 24 hours. (You don't know what it does, and no one can identify it.)",
"A cotton ball that laughs when no one is around.",
"A ring that always feels cold to the touch. When you wear it you can hear whispers from a distant being.",
"a scale from a wyvern that when thrown always returns to you.",
"The feather of a angel, when shaken it produces a brilliant gold dust, this dust is highly addictive.",
"A small tree in a pot. Each day the tree grows a single fruit, each tenday the fruit is different.",
"A stool that follows you where ever you go.",
"A gear that slowly spins of it's own accord.",
"A wooden carving that is shaped like your mother, it changes shape for whomever holds it.",
"A holy symbol made from a strange bone, it makes no sound, and you cannot identify which god it's the symbol of. (Mask)",
"A mask made of oak, when it is worn your voice becomes 2 octaves deeper. It can be worn backwards, this makes your voice two octaves higher.",
"A ball of twine that cannot be untangled.",
"A piece of glass that constantly refelects a rainbow.",
"A small crab that loves you unconditionally, the crab is immortal and follows you everywhere.",
"A silver rod that changes color with your mood.",
"A sponge that can absorbed much more liquid than it should be able to. (10 gallons)",
"A skull that mumbles racist slurs whenever it sees an elf. It's drawven in shape.",
"A fork that will pierce anything.",
"A foggy mirror, when cleaned it always returns to being foggy.",
"A red earring that when worn allows you to speak Abyssal, but only say 'I don't speak Abyssal. I only know that sentance, and this one explaining it.'",
"A mushroom that tastes of strawberry, and when planted grows to fifteen feet tall.",
"A brass ball that constantly smells horrible, when sleeping near it you always have pleasant dreams.",
"A drawing of a manatee, the manatee moves withing the frame.",
"The eye of a beholder, it blinks and looks around of its own accord. (It has 'Beauty' carved in it's pupil.)",
"A flute that sounds different for everyone that hears it.",
"A necklace that always fits anyone who wears it perfectly.",
"A bamboo straw that when blown into produces water (Up to ten gallons a day.)",
"A stone that bounces off anything. It have jagged edges.",
"A monocle that increases your sight in that eye by 10ft.",
"A dull sword that cannot be sharpened. It produces musical notes when you swing it.",
"A crown made from reeds that lets you talk to amphibians.",
"A golden finch, when the command word is spoken it becomes alive. (You don't know the command word.)",
"A letter from a fiance you didn't know you had. If you drop it it'll always reappear on your person.",
"A small vial with an insect inside, it seems very angry.",
"A sea shell that a girl sold you on the shore. It was overpriced, but when you look at it you always smile.",
"A box that holds the heart of the faerie queen.",
"A bottle of black sand that is flammable.",
"A signet ring with draconic symbols. When used to seal something in wax the symbols move.",
"A cowl made of raven feathers. It makes you appear edgy, and you gain the personality of a loner.",
"A statue of a zebra, no one can tell if it's black with white stripes or white with black stripes.",
"An invitation to visit an amazonian tribe, there is a map burned with arcane magic into the letter. It's painful to read.",
"A vial that constantly leaks honey.",
"A fishing hook that cannot be bent.",
"A stone shaped like a heart that makes common folk like you. If it is broken you become depressed for 1d10 days.",
"Drift wood that smells of salt, it can be bent by hand.",
"A teleportation circle diagram. You don't know how to use it, or where it will take you.",
"A whistle that when blow causes you to fly 5ft backwards. (3 uses a day)",
"A belt with a pocket that has more room than it should. (Holds up to a five foot cube worth of items.)",
"A pouch of white sand that always refills itself each day.",
"A tiny statue of a praying mantis. Staring at it for one minute causes horrible visions of an impending disaster.",
"Hand wraps that glow softly when rubbed together.",
"The hilt of a sword that feels heavier than it should. When the command word is spoken a blade shoots from the hilt and becomes a shortsword. (You don't know the command word.)",
"A glass bottle that holds a small storm. (Rain, lightning, thunder, and dark clouds. When opened the storm dissipates, but comes back each day.)",
"A faerie trapped in a bottle. She/he gazes at you seductively (It's only friendly towards you and other fae.)",
"A book of elven text, when read it makes you sleepy.",
"A scroll that bleeds when you open it.",
"A small stone with a hole in the center, smoke constantly bellows out of the hole.",
"A venus fly trap that will eat anything that fits in it's mouth.",
"A wand that when held moves about on its own accord. (This movement is a different classical song each time it's held.)",
"A marble that hovers three inches above your hand.",
"A paper fan that when used produces no breeze, but will put out any non-magical fire.",
"A crystal ball that shows you the person you love the most.",
"A vial filled with fine white hair. In moonlight they glow brightly.",
"A section of leather that growls when you pick it up.",
"A king from a chess set. He gives a helpful point of view when asked a question",
"A hair broach that makes you unable to speak.",
"A wooden doll that makes whoever looks at it uncomfortable.",
"A small hat that changes style every day.",
"A bottle that can capture a sound when the command word is spoken, when opened it repeats this sound until another is recorded. (You don't know the command word.)",
"An egg of unknown origin. You can tell it's alive, but don't know what will hatch.",
"A puzzle box that when opened (Dc 15 int) contains two items on this list.",
"Hitting this rod against a metal object will cause someone within earshot to have an accident, probably fatal. After being struck, the rod will continue to softly vibrate and may not be used again for d12 hours",
"A 1 foot tall ceramic pot that will make a loud announcement when something moves too close it it. Usually used to announce visitors to a household.",
"This gem normally looks like quartz, but if left out in the sun for one day turns yellow like a topaz. Smacking it against something creates a blinding light and drains it of color.",
"Bag of Infinite Muffins. Exactly what it says on the tin: there's always exactly one muffin inside the bag, no matter how many you pull out. A variety of flavors, though it was a bit biased towards banana nut.",
"A small magical candle that burns without being consumed.",
"A spool that causes the thread wound on it to match the color of any fabric that it is touched to.",
"A small gold ring set with a magical stone that dimly glows any color the wearer desires.",
"A leaf from a Silveroak Tree that never wilts. While you hold the leaf you can speak Sylvan.",
"A heart shaped locket that allows you to mentally send up to thirteen words once per day to the person whose name is engraved in the locket. They can immediately respond back with thirteen words.",
"A hat that keeps you magically dry in any rain.",
"A tent big enough for two people that folds, with its poles, into a 4 inch cube.",
"A pair of shoes or boots that never get dirty.",
"An egg sized stone that grows wet, cold, hot, or dry depending on the weather in 24 hours. If hung from a string the rock swings or hangs depending on the wind in 24 hours.",
"A small herb pot that can be used to cast prestidigitation on up to 1lb of food 3/day to flavor the food.",
"A vase that keeps any flowers placed in it from wilting.",
"A silver broach that can change into the shape of any flower the wearer is familiar with.",
"A pea sized crystal and a compass that always points toward the crystal.",
"A small copper feather that negates the first 20 feet of falling damage.",
"A fishing hook that wriggles like a worm negating the need for bait.",
"A magical stone hawk that can be set to attack any tiny or small beasts that approach within 300 feet.",
"A small box that opens on the top and bottom. Each side of the box opens into a separate extradimensional space the size of the box.",
"A stone mug carved with images of feasting dwarves. Any water put in the mug turns into dwarven ale. If you drink the ale you must make a constitution save DC 13 or become drunk for the next 1d4 hours. While drunk you are poisoned and can speak Dwarven.",
"A rose from the Shrine of Roses that never wilts. Once per day the rose can cause a flowering plant to sprout flowers and bloom.",
"A Sun Sphere from the Empire of the Sun. When activated the Sun Sphere looks like a miniature sun six inches across and provides light equal to a light spell.",
"A gemstone with a bloodshot and constantly roving beholder eye visible deep inside it. Once per day the owner can gain 1d4 to a saving throw against a spell.",
"A flat iron rod with a button on one end. When the button is pressed the rod becomes magically fixed in place until the button is pressed again. The rod can hold up to 80 lbs of weight. A DC 8 strength check allows the rod to be moved up to 10 feet.",
"A horn that when blown can clearly be heard by everyone within 300 feet. After blowing the horn the users’ words are amplified for the next minute and can also be heard by everyone within 300 feet.",
"An ancient and unbreakable ring.",
"A necklace or circlet woven of meadow flowers that never wilt.",
"A key that opens any lock you locked.",
"A water skin that can hold a barrels worth of water (59 gallons).",
"A bell that awakens anyone within 30 feet when rung.",
"A torc engraved with horses that allows you to march an extra hour a day without having to make an exhaustion check.",
"A pair of glasses that gives you 10’ darkvision.",
"A sewing needle that will finish sewing any seam you started on its own.",
"A wood cutters axe or adze (treat as a hand axe) that deals double damage to wooden objects.",
"A small raven carved out of stone or wood. When activated the raven will count any humanoids it sees other than your allies. The raven can tell you if it has seen one, two, three, or many humanoids since it was activated.",
"A dragonfly carved out of jade that, when active, flies around you killing mosquitos and flies.",
"A tiny platinum figurine of Bahatmut that gives the bearer advantage on diplomacy checks with good dragons.",
"A preserved and shrunken eye set in a ring. While worn the bearer has advantage on deception checks to mimic animal sounds.",
"A pound of troll flesh that constantly regenerates providing enough meat every day for two humans. The flavor is disgusting.",
"An outfit of clothing that never gets dirty and magically mends any rips or tears.",
"A chamber pot that disintegrates any excrement put in it.",
"A comb made of bone that causes your hair to grow 1 inch for every minute you brush it. Your hair stops growing when it is as long as you are tall.",
"A pin with clear glass beads that keeps natural smoke at least 1 foot away from you.",
"A glowing rod that drives away dampness and moisture in a 10 foot radius.",
"A set of seven glowing magical gems that can be set swirling around you.",
"A two inch tall animal spirit that is friendly and always remains within 5 feet of you.",
"A small blank book. As an action you can copy another book or other document into your book. The copy remains until you will it to be erased or copy another document.",
"A staff that can be turned into a tree or back into a staff.",
"A fish mask that lets you hold your breath twice as long as normal.",
"A petrified rat brain that lets you cast dominate monster once per long rest on a small or tiny rat or mouse.",
"A gold coin that you can summon back to your hand as long as it’s within 20 feet.",
"A small red gem that is warm to the touch. When the gem is placed on inanimate flammable material the material catches on fire in 1d4 rounds.",
"A small magical snake that can take the form of a tattoo on one of your arms. Once per day while the snake is a tattoo you may add 1d4 to a diplomacy check. You also have advantage on diplomacy checks with Lamia.",
"A holy symbol of Chauntea that you can activate once per day to weed, water, and care for a field of crops no larger than half an acre.",
"A holy symbol of Helm that you can activate once per day to gain 1d4 to an initiative roll.",
"A holy symbol of Waukeen that gives you 1d4 on checks to run a business.",
"A holy symbol of Myrkul once per day you can use it to animate a tiny beast. The tiny skeleton or zombie remains under your control until it is destroyed or you animate a new undead. (AC 10, 1hp and unable to deal damage)",
"A holy symbol of Yeenoghu that once per day you can activate as a bonus action to allow a gnoll within 30 feet to make an attack as a reaction.",
"A holy symbol of Amaunator that makes you immune to the exhaustion effects from hot weather.",
"A holy symbol of Moradin that makes you immune to the poisoning effects of alcohol.",
"A holy symbol of Eilistraee that allows you to sing beautifully.",
"A holy symbol of Grumbar that allows you to speak Terran.",
"A jar containing an aboleth mucus gland. If you breathe in the mucus you are able to breathe through your skin underwater for thirty minutes. The gland refills the jar with mucus in 24 hours.",
"A whistle that can only be heard by your allies.",
"A cup or plate that change color when they come in contact with poison.",
"A brass pitcher and a silver fly. As long as the fly is within 15 feet of the pitcher it whispers anything the pitcher hears.",
"A musical instrument that magically plays simple tunes and songs.",
"A small doll that mimics your movements.",
"A halter that when placed on a cow, donkey, mule, horse, or camel gives you advantage on animal handling checks for that beast.",
"A pack saddle that doubles the weight the beast wearing it can carry.",
"A necklace of animal teeth. Once per long rest as a bonus action you can cause the necklace to bite you dealing 2 points of piercing damage.",
"A pair of silver bars twisted together. Once per day when you use Bardic Inspiration you may designate two individuals. Either can use the Bardic Inspiration die but once it has been used it’s gone.",
"A set of sheep’s knucklebones that allow you to cast the ritual Augury in 1 minute if you can normally cast it as a ritual.",
"A fetish made of bone and feathers that lets you cast the ritual Speak With Animals in 1 minute if you can normally cast it as a ritual.",
"A gem that adheres to your forehead like a third eye. If you spend a Ki point your speed increases by 5 feet for that round.",
"A vial of holy water (fiends) or glowing crystal (undead) that focuses your divine senses. When you use Divine Sense you can choose to only detect fiends or undead, depending on your trinket, and the range of your senses extends to 90 feet.",
"A mummified body part of a creature. If this creature’s type is your favored enemy selection than once per day you can reroll a 1 on a Survival or Intelligence check related to the creature type.",
"An elemental gem (pick cold, fire, thunder, electricity) that once per day can act as a focus for a metamagic spell. The gem changes half the spells damage type to match the gem.",
"A token of a fey (electricity), far realm (psychic), or fiendish (fire) power. Once per day if you cast eldritch blast the token changes the damage type of the blast.",
"A ritual book that lets you cast arcane rituals half the normal time.",
"An obsidian ring that allows one individual you can see who can’t speak in Thieves’ Cant to understand you when you speak in Thieves’ Cant.",
"A steel torc engraved with the image of boars. If you roll a 1 to recover hit points when you use your second wind you may reroll the die. You must use the results of the second roll.",
"A mirror that can grow and shrink from hand sized to full length.",
"A ring that turns a willing wearer to stone until the ring is removed.",
"A nightcap that, when worn, gives you pleasant dreams.",
"A small fan with a humming bird painted on it that will hover near you and fan you.",
"A glass orb filled with smoke. If you concentrate on it an image of the person you are thinking about appears.",
"A stone orb that half lit and half dark. The dark and light halves rotate around the orb once per day.",
"A 6 inch long crystal coffin. When empty if touched to a dead body the body is shrunken and placed inside the coffin. The body can be released from the coffin by opening it. While in the coffin the body is under the effects of a gentle repose spell.",
"A brass key that burns you when you hold it (1pt per round) if you aren’t resistant to fire and allows you to speak Ignan.",
"An iron pot or pan who’s handle never gets hot.",
"The feather of a Solar that is always immaculate. While holding it you can speak Celestial.",
"A horn from a Devil or Demon that allows you to speak Infernal or Abyssal respectively.",
"A spirit in the shape of a gear. The spirit can instantly count anything you can see or let you know when a specific amount of time has passed.",
"A dowsing rod that points to any water within 20 feet.",
"A wooden wand that lets you magically move unattended objects weight less than a pound that are within 15 feet.",
"A statue of a cricket that chirps softly in the dark. The cricket stops chirping if an invisible or incorporeal creature comes within 10 feet.",
"A collar that lets a dog or cat speak in common. It doesn’t change the animal’s intelligence.",
"An acorn that prevents you from being hit by natural lightning.",
"A finger bone from an executed man in a small wooden box. You have +1 on death saving throws while it’s in your possession.",
"A book of very short stories. Reading a story from the book (an action) acts like using a healer’s kit.",
"A ring that will detect fire without fail. Range touch.",
"An ace of spades from a standard card deck. No matter where you store it on your body, you will always be able to find it in your right sleeve afterwards."
    ]

var treasure_items = [
"An iron-strapped oaken coffer holding 12 trade bars of silver from “Manham’s Trading Cartel”. (25gp each)",
"A huge (14 ft.), basalt statue of an armored knight with spear and shield. (340gp)",
"A beautifully crafted, masterwork mandolin with electrum frets and silver inlay. (460gp)",
"A finely detailed, life-sized granite statue of an ancient warrior bearing ring mail, shield and spear. (290gp as art, however this warrior was petrified by a medusa, and can be brought back to life with a ‘stone to flesh’ spell)",
"A rug made of winter wolf hide. (150gp)",
"A leather bag containing 13 black candles, a flint & tinderbox, and 13 platinum coins bearing an image of flames on one side and various demons’ faces on the other. (140gp)",
"A mithril-headed pickaxe. (450gp)",
"A newly-sprouted, potted treant. (800gp to a sage or university)",
"A golden disk with nine small gems inset (diamond, emerald, sapphire, ruby, onyx, pearl, moonstone, jacinth, and jet). Disks such as this are used in the Wizards’ Guild to identify someone as an archmage. (1,000gp)",
"A deed to a tract of 40 acres of farmland and low hills near the border of the gnoll lands. (200gp)",
"A well-crafted marble chessboard with electrum pieces as white and gold pieces as black. (Chessboard: 35gp, 16 electrum pieces: 10gp each, 16 gold pieces: 20gp each or the entire set for 580gp)",
"A ballista on the back of a wheeled wagon that also carries 12 spears. The ballista is fired toward the rear, to protect the single horse or mule that pulls it. The wagon has a bronze-covered wooden shield near the back that provides 75% cover for up to two operators that sit in the wagon. (370gp)",
"A large, locked bronze chest (DC: 28 Open Locks) in which rests a breastplate, gauntlets, a full-helm, and a light steel shield, all of masterwork quality and enameled in white. (Breastplate: 400gp, Helm: 160gp, Gauntlets: 160gp, Shield: 160)",
"A large (24”x36”) tome of 400 vellum pages bound in leather with a silver cover in the likeness of a dragon’s head with two small green-flecked black opals as eyes. The contents, written in draconic, detail the early history of three distinct clans of silver dragons, the interior politics of each clan, and the rumored locations of the three clans’ hordes. This tome was written by the red dragon historian Pyrokorius, known to humankind as “Inferno”, some two hundred years ago and may be out of date. (Value: 950gp)",
"An intricately carved, elven-manufactured masterwork composite longbow of ash and decorated with ivory and silver. The carvings depict a great oak tree surrounded by dancing elves. (625gp)",
"A silver orb roughly the size of an apple, polished to mirror-like shine. Half of the orb is decorated with three key-like projections of steel, while the other half has been etched with the symbol of the Kalister family, a six-armed demon. The orb was crafted to be a key to the burial vaults of the Kalister Necropolis. The Kalisters were wealthy sorcerers whose burial vaults have been lost for centuries. The orb has been enchanted to resist tarnishing. (340gp)",
"A small, locked (DC 18 Open Lock; DC 22 Strength Check; hardness 10, HP 25) steel canister which holds a twenty pinches of powdered pearl. (Canister: 90gp if intact; powdered pearl: 200gp)",
"A copper and mahogany divan with crimson silk cushions. (160gp)",
"A pair of worn black leather boots sized for an ogre, mostly dry-rotted. The heel of the right boot is hollow and holds a tourmaline of good quality. (Tourmaline: 300gp)",
"A broad manticore-leather belt containing six steel flasks for containing potions. Four of the flasks are currently empty, one contains a Potion of Mage Armor (50gp), and the last a Potion of Cat’s Grace (300gp). Belt value: 35gp",
"A magical statuette of white marble, roughly a meter tall that shapes its form to the last sentient being that touched it. It currently has the form of a Dark Naga (or whatever person or creature the DM would like to be the owner…). Should a PC touch it, it takes only a round for their image to be transferred to the statuette, which may alert someone that they are nearby. The statuette weighs nearly 200 pounds. (Hardness 15, HP 50). (500gp)",
"An ore cart filled with coal and spider webs. Hidden in the coal are six rough diamonds (DC 24 Search check or DC 18 Profession: Jeweler check to find). (Cart: 25gp, Coal: 1gp, Diamonds: 25gp, 20gp, 40gp, 30gp, 25gp, 55gp). Also in the coal cart is hidden a colony of Tiny Monstrous Spiders (8 spiders). They attack if the coal is disturbed.",
"A tortoise-shell shield; banded in iron and decorated with electrum inlay. (Treat as a Masterwork Heavy Wooden Shield that weighs 6 pounds, 220gp)",
"A locked steel coffer (DC 28 Open Lock check; Inflict Light Wounds trap: CR 2; magic device; touch trigger; automatic reset; spell effect (inflict light wounds, 1st-level cleric, 1d8+1, DC 11 Will save half damage); Search DC 26; Disable Device DC 26.) containing six rare books on magical theory: “Finding Familiars” by Thaddeus Hornkeep (45gp), “Planar Bindings: keeping your demons held securely” by Teona Kell (90gp), “Magical Matrices and Their Power in Dwoemercraft” by Mikyl Demaj (120gp), “Conjuring the Elemental” by Pierce Blackhand (65gp), “Countermagics” by Simon Felstar (40gp), and “Enchanting Solutions” by Helena Barwight (95gp). (Coffer value: 250gp) 25- A simple wand of elm wood, decorated with three red hawk feathers. (A fully-charged Wand of Darts: This wand can be used to fire up to two darts per round as if hurled by the caster (no strength bonus applied, but dexterity bonuses/penalties do). Once fired, the darts become non-magical. A new wand of this sort will have 100 charges. A wand can be recharged by someone with the “Craft Magical Arms and Armor” feat for 2gp of raw material per charge.) (450gp)",
"A three hundred-twenty year old bottle of elven wine. Called rose wine, the bottle is of Goldenbough wood, crafted by a ‘Shape Wood’ spell and appearing as a delicately crafted rose, with the date and winery listed in elvish runes along the stem. Rose wine is a brilliant red in color, delicate and dry, with the flavors and scents reminiscent of spring and life. The grapes for rose wine are grown only in a remote wood, and recent disease has destroyed many of the vines. Only a few dozen bottles of rose wine are crafted each year, and most of these are held close by the clan of elves that create it. (Intact: 600gp, bottle only: 185gp)",
"A platinum scarab, inlaid with gold and four emeralds. (920gp)",
"A leather sack containing 3 vials of antitoxin (50gp each), a tanglefoot bag (50gp), and a flask of acid (10gp).",
"A mounted moose head. The head has a bag in the skull, placed by the taxidermist, which contains a thick gold ring set with a ruby (350gp).",
"A scroll in a leather tube containing schematics on the design of a repeating light crossbow. The design allows someone a +4 circumstance bonus to their Knowledge: Engineering check when crafting a repeating light crossbow and reduces the cost of crafting the item by 5%. (850gp)",
"A wall display of captured weapons and armor, all kept in useable condition, consisting of: 3 long swords, a greatsword, 5 spears, a light mace, a heavy flail, a falchion, a dented breastplate, 3 wicker shields, a tower shield, and a set of scale mail. (Total value: 430gp)",
"A plain, beaten platinum diadem set with a large oval-shaped lapis lazuli. (275gp)",
"A portable battering ram of iron-bound oak with the head of a bear as the ram. The bear has blue onyx eyes. (Value: 225, Onyx eyes: 50 each)",
"A small painting of the Battle of Seymond Run, depicting knights with lances battling frost giants some 300 years ago. The painter, Sir Rens Palto, painted it from memory soon after the battle. Palto became one of the most well-known artists of the time, and this work was mentioned in some famous writings, but its whereabouts went unknown until now. The painting is framed in a simple wooden frame. (640gp)",
"A silver flask with a holy-symbol runed stopper, extremely cold to the touch. The flask contains wraith essence. If the flask is opened outside of a Protection from Evil or Law Circle, the advanced wraith (8 hit dice) regains its form in three rounds and attacks. (Flask: 25gp, wraith essence: 620gp)",
"An intricately carved ivory rapier scabbard trimmed in electrum and set with three red garnets along its length. There is a small opening at the terminus end to allow the scabbard to be used as a breathing tube, if needed. (445gp)",
"A ring of platinum, shaped as intertwining grape vines. An inscription on the interior reads: “When life fades and darkness falls, there is still the final hope.” (110gp)",
"A mechanical songbird in a wire cage. The bird is of copper and brass and when a small crank is turned, the bird can sing one of five birdsongs: canary, warbler, cardinal, nightingale, or barn owl. The contraption is fragile (0 hardness, 5 hit points). (185gp)",
"An eye-patch of gold, set with three red spinels, on a black leather cord. The back of the eye-patch bears a stylized shadow in black lacquer, the symbol of The Dark, a large criminal organization that has hands in everything from drugs and prostitution to assassinations. (310gp)",
"A scroll of birch bark covered in tree resin for strength and found in a bear-hide scroll case, which contains druidic spells: Barkskin, Heat Metal, and Hold Animal? It appears that two other spells have already been used off of this scroll. (Caster level: 3rd, Value: 450gp)",
"A beautifully crafted steel breastplate sized for a halfling or gnome, with gold and silver enameling depicting seven mountaintops; the holy symbol of Yondalla, the halfling goddess. (380gp)",
"A leather satchel containing a dozen bottles of various inks and twenty needles of assorted sizes that makes up a masterwork tattooist’s kit. (105gp)",
"A life-sized sculpture of a two-horse chariot and rider done in white granite. The sculpture is immovable without the help of magic. (875gp)",
"A small coin purse that holds a sling and 4 adamantine sling bullets, 12 cold iron sling bullets, and 12 alchemical silver sling bullets. (Adamantine: 60gp each, Cold Iron: 2gp each, Alchemical Silver: 2gp each)",
"A large saddle with several extra straps and buckles (suitable for a winged mount), which includes a long sword scabbard and a masterwork long sword. (Saddle: 60gp, mw long sword: 315gp)",
"A massive key, roughly 3’ long and crafted of electrum with a piece of green jade carved into the bow in the shape of a longboat. This key is decorative, and there are no matching locks. (145gp)",
"A leather girdle (i.e. wide belt) of bear hide set with an electrum and topaz buckle (Buckle: 230gp).",
"A large ewer of silver, etched with scenes of a boar hunt. There is an inset brown garnet in the shape of the boar. (500gp)",
"A ceramic pot with two blooming blue tulips. (DC: 20 Knowledge (Nature) check to realize this is the Hanjil Tulip, a flower thought extinct for over a hundred years. The Hanjil Tulip is a vital ingredient in several potions that deal with the school of charms and enchantment. Value to an alchemist or wizard: 500gp each.)",
"A suit of black dragonhide banded mail and gauntlets (all of masterwork quality), trimmed with gold. This suit of armor is lovingly maintained and is polished to a brilliant sheen. (975gp)",
"A broad-beamed rowboat carrying three chests of iron-bound oak. The first chest is locked (DC: 24 Open Lock) and contains 1150 silver coins. The second is unlocked and contains four formal dresses for a petite woman. The third chest is unlocked and holds a lute and a lyre, both wrapped in bundles of cloth. (Rowboat: 50gp; Dresses: 15gp each; Lute & Lyre: 5gp each)",
"A deed granting the bearer the rights to the Whispering Shallows Silver Mine; which produces a profit of 3d4x 10gp per month when fully operational, with a decent site manager… Unfortunately, the mine is currently inhabited by monstrous spiders and the equipment is rotted and needs to be replaced. Oh, and that back tunnel leads to the troglodyte clans... who work for duergar, who are trying to keep the drow from expanding, on orders from the mind flayers… (Equipment costs are 500gp to get production going). The deed can be sold for 750gp.",
"A set of three small, geometric stones; each about two inches long with runes carved upon them. The first is red marble in the shape of a sphere. The second is white jade in the form of a spindle. The third is a purple crystal prism. These are Ioun Stones awaiting enchantment. (Deep Red, Pearly White, and Purple Prism; each valued at 170gp)",
"A stuffed green and black-banded giant constrictor snake, some thirty-feet long. The skin can be salvaged (with a DC: 14 Profession Leatherworking check or something similar) and is worth 300gp.",
"An orcish throne; a large seat of heavy wood with sheets of gold, etched with scenes of warfare and violence. Two gnoll skulls with just a bit of sinew left on them sit atop the back of the throne, as well as a pair of crossed halberds that rise above the back of the piece. (Total value: 480gp)",
"A sculpture done in silver wire that creates the life-sized image of a bull on a thick granite base. (740gp)",
"A large turquoise bowl, roughly eighteen inches in diameter. The rim is edged in silver. (175gp)",
"Six identical wax-sealed clay pots. All appear to be the same weight, but five of the pots hold chemicals that will explode on contact with the air (3d6 damage in 5 foot radius; Ref Save DC: 14 for half damage. Search DC: 28, Disable Device DC: 28). Opening the clay jar while under water circumvents the explosives. The other contains a similar (non-explosive) gelatinous concoction that holds three sapphires. The clay pots can be hurled with a range increment of 10 feet. (Sapphire value: 250 each).",
"An electrum longsword scabbard set with five (100gp) jets along its length. (575gp)",
"A prism that will project a map of the kingdom (or anywhere else the DM chooses) against any flat surface provided there is a light source to refract through it. The interior of the prism can be seen to be etched in amazing detail and has dyes suspended in it to provide color to the map. (350gp)",
"A simple brass ring; a “Ring-pouch”. This simple band is a magical extra-dimensional space about the size of a pouch. When worn it seems like a normal band of brass, but when taken off, the ring can be stretched to open a space that is capable of holding about 100 coins or the equivalent (gems, spell components, etc.). This ring does not detect as magic unless the spell used is 2nd level or higher. Very useful for smuggling or ensuring you have a dagger or lock-pick handy…. (1000gp)",
"A large-sized morningstar, consisting of an oaken tree-limb imbedded with 23 pieces of obsidian. (Obsidian value: 6x5gp, 13x10gp, 4x20gp)",
"A jar containing four applications of drow poison (evaporates if exposed to sunlight). (Injury poison; Fort DC: 13 Frequency 1/minute for 2 minutes; causes Unconsciousness for 2d4 hours; value 75gp per dose).",
"A set of tarot cards etched on electrum plates. The six suits for this deck are: Caverns, Demons, Fates, Moons, Swords, and Wands. (60 plates, each worth 5gp, the entire set would sell for 350gp)",
"A ship’s bowsprit carves into the likeness of a woman warrior with drawn sword pointing forward. The blade is composed of steel, while the woman is crafted from ash wood. (240gp)",
"A large pearl in a decorative marble display case that is shaped like an oyster. (Pearl: 500gp, stand: 125gp)",
"A large yellow and blue banded egg, roughly a foot long, which rests in a pile of leather scraps. (This is a hippogriff egg, which if kept warm and safe will hatch in three months. Value: 750gp)",
"A silver-backed hand mirror set with a large zircon. (345gp)",
"A white porcelain tea set decorated with blue snowflakes. The set includes a teapot, bronze brazier, and 6 cups. (125gp)",
"A long-lost battle scene involving a small dragon’s skeleton with brittle bones and eight sets of rusted armor and weapons. Hidden within the ribcage of the dragon (Search DC: 18) lies a grime-encrusted set of three sealed bronze flasks. The first holds a milky liquid that smells of cotton (a Potion of Bless Weapon. 100gp), the second a clear syrup that smells like butter (a Potion of Protection from Evil. 50gp), and the last a dark gray, viscous concoction with a sandy-grit consistency smelling of lemon (a Potion of Bear’s Endurance. 300gp)",
"An iron maiden set with 50 slender silver blades; perhaps for use in torturing lycanthropes or undead? (900gp)",
"A mountaineering set including 200 feet of silken rope (40gp), two grappling hooks (1gp each), six sets of crampons (5gp each), twelve tindertwigs (1gp each), two small tents (10gp each), a miner’s pick (3gp), 60 pitons (1sp each), two hammers (5sp each), and six heavy bedrolls (1gp each) in a large, unlocked wooden chest (2gp).",
"A beautifully crafted, life-sized marble statue of a middle-aged man in fine clothing and hat, painted in vibrant colors. The man depicted is a famous city mayor that disappeared ten years ago. (400gp)",
"A miniature platinum sword with a grip and pommel of copper and zinc. This is a material component for the spell “Mage’s Sword”. (250gp)",
"A large, oval plate crafted of gold and decorated with a scene of men wrestling. Inscribed along the lower edge of the plate is the inscription: To the victor, the spoils”. This plate is a trophy for winning the wrestling tournament in an Olympics-like competition. (500gp)",
"A scroll written on a piece of demon-skin containing two arcane spells: Arcane Sight and Ghoul Touch. The scroll is bound with a carved jade ring shaped into the likeness of a demon’s face. (Scroll: 525gp, Ring: 230gp)",
"A handheld court seal for a local land composed of silver and carved lapis lazuli. This item grants a +2 circumstance bonus to Forgery Checks on items created that are based from this land when using the seal. (Value: 200gp, Value to criminal organizations or the government: 650gp)",
"A giant beetle carapace of iridescent blues, purples, and greens. An armorer could make this into a masterwork large shield or breastplate. (120gp)",
"A shirt of black elven silk. This silk has the unusual property of resisting cuts and blunt force trauma, acting as masterwork padded armor without the bulk, and allowing arcane spell casters to benefit from it with no chance of arcane spell failure (Armor bonus: +1, Max. Dex bonus: 8, Armor Check Penalty: 0, Arcane Spell Failure Chance: 0, Weight, 1 pound). This is a masterwork item and can be enchanted. (650gp)",
"A mannequin, slightly smaller than a life-sized woman, crafted of steel, wood, and leather and dressed in a blue dress. Levers on the mannequin can adjust the size of hips, waist and chest and the legs can be lengthened or shortened as needed. (Dressmaker’s mannequin and dress: 145gp)",
"An unlocked coffer holding eighteen gold bricks stamped with the symbol of an evil god. (50gp each)",
"A set of masterwork steel manacles covered in alchemical silver, with a key attached. (220gp)",
"A weathered black leather quiver with eight rotted arrows within. A false bottom within the quiver holds five pink pearls wrapped in linen cloth. (Pearls: 3x100gp, 2x250gp)",
"A carved wooden throne (actually an aggressive Mimic with 60 hit points), against which rests a greataxe of steel, trimmed in silver and decorated with feathers dyed blue and red, with a black onyx set in the bottom of the pommel. The greataxe is glued to the mimic until the mimic is killed. Strong alcohol dissolves the adhesive, but the mimic still can grapple normally. A mimic can dissolve its adhesive at will, and the substance breaks down 5 rounds after the creature dies. The mimic is willing to give up the axe in exchange for its life if brought below 15 hit points. (A masterwork greataxe: 975gp)",
"A round granite door carved with ancient symbols. The door weighs almost a ton. (The symbols are actually in three languages and would be worth 800gp to a university or sage specializing in history or ancient cultures. The inscription reads: “Herein lies the plight of the barrow warden; dressed for eternity. Lower thine eyes from the glorious radiance. Raise thy voice in supplication.”)",
"A dagger of masterwork quality carved from a single blue-crystal shard that has the hardness of steel. The hilt is wrapped in snow-serpent skin. (540gp)",
"Four ancient coins crafted from mithril. They are triangular in shape, with a hole in the middle. On one side is a chariot and driver and the on the other is the face of an ancient king of unknown lands. They are roughly fourteen hundred years old, but due to their construction appear as they did when newly minted. (Coins: 160gp each) 88- An ermine cap with an electrum brooch set with a small jacinth. (875gp)",
"An alchemist’s notebook, consisting of sixty-three loose-leaf pages rolled up and shoved into a wooden tube with a cork stopper. The rough handwriting is cramped, but contains the recipes for potions of Reduce Person, Enlarge Person, Darkvision, and Jump. The skill of the research allows for the user of the notebook to spend only 75% of the normally required experience points when crafting these potions (Though the Brew Potion feat is still required). (750gp)",
"A perfectly preserved wyvern in a massive, sealed jar filled with embalming fluid. (1000gp)",
"A small silver pendant in the shape of the holy symbol of the sun god. Twice per day, the wearer can call forth the power of the pendant, creating Light (as the 0-level cleric spell) for ten minutes. (850gp)",
"A small pouch with 12 Goodberries. Each transmuted berry provides nourishment as if it were a normal meal for a Medium creature. The berry also cures 1 point of damage when eaten, subject to a maximum of 8 points of such curing in any 24-hour period. (As per the druid spell, “Goodberry”, except that they will last indefinitely until consumed.) (Value: 20gp each)",
"A jacket of blue silk embroidered with golden roses and secured with seven gold buttons. (145gp)",
"A herd of 86 black sheep. (Value 1d3+1gp each)",
"A bracelet of seven gold medallions, each etched with the symbol of a good god and set with one of seven different stone: Bloodstone, Carnelian. Jasper, Amethyst, Green Spinel, Violet Garnet, and Moonstone. (900gp)",
"A masterwork dire-flail with a cold-iron head on one end and an alchemical silver head on the other. The shaft is of iron-bound ash wood that has been carved into the likeness of gnolls in battle. (770gp)",
"A set of archer’s bracers made of electrum and set with seven small jade discs set in a circle on the back of each bracer. (Value: 300gp each, 675gp for both)",
"A stone eye symbol, long since disconnected to the wall that it was carved into, covered in gold leaf and then freshly painted in red, black, white, and blue. The entire piece is roughly the size of a watermelon and weighs a hundred pounds. (180gp)",
"A dire bear pelt fashioned into a cloak fit for an ogre or ettin. A large, crude silver clasp is attached. (175gp)",
"A set of six quill nibs used for scroll making. (Silver nib: 2gp, Gold nib: 18gp, Platinum nib: 75gp, Adamantine Nib: 190gp, Dragon Bone nib: 200gp, Oak nib: 1sp)"
]

var mundane_items = [
    
"Velvet Purse",
"Shrunken Head",
"Cornhusk Doll",
"Bottle of Perfume",
"Glass Jar with a preserved animal",
"Necklace Pouch",
"Loin-Cloth",
"Smokepipe",
"Bag of Shell Bits",
"Bronze Chime",
"Shiny Stone",
"Bag with multi-colored chalk",
"Miniature Copper Bell",
"Iron Whistle",
"Rusty Nose Ring",
"Purple Dyed Pebble ",
"Dried Scalp with semi-precious stones sewn in.",
"Hookah",
"Tome of Substance Most Toxic",
"Unicorn Shaped Earring",
"Serrated Knife",
"Windfan with a Dragon Image",
"Vial of Urine",
"Gold-Plated Shackles",
"Clay Pot with Rainbow Colored Mold",
"Fish Net",
"Journal of a Toymaker",
"Glass Eye",
"Pitchfork",
"10ft Pole with a Mirror on end.",
"Tar Paper",
"Skeleton Key",
"Libram of 'Things that shall not be said'",
"Charcoal Bar",
"Feather Headband",
"Set of Wooden Soldiers",
"Pot of Lard",
"Vial with Peppermint Oil",
"Stained Glass Window with Butterflies",
"Taxidermied Fox",
"Leather Corset",
"Grinning Idol",
"Box of Chocolate Eggs",
"Baby Carriage made of Bones",
"Cart filled with Seaweed",
"Abacus",
"Statue of a Porcelain Elephant",
"Box of Gray Stone Tiles",
"Wooden Plank engraved with words of love",
"Book of Children's Names",
"Crystal Goblet",
"Box of Firecrackers",
"Pairing Knife",
"Rusty Cleaver",
"Thumbscrews",
"Snow globe",
"Ornate Letter Opener",
"Jar of Wax",
"Ceremonial Breastplate",
"Plumed Helm",
"Skull Mask",
"Mirror Shield",
"Small Box of Toothpicks",
"Vial of Peppermint Oil",
"Tin Bucket",
"Rusty Iron Spikes",
"Box of Tea Leaves",
"Case of Tobacco Chew",
"Dusty Turban",
"Ceramic Imp Statue",
"Silver Urn with Ashes",
"Empty Spice Shaker",
"Brass Periscope",
"Bundle of Barbwire",
"Bar of Cold Iron",
"Bag with half dozen scented soap bars.",
"Gold Candle Holder",
"Cast Iron Pot",
"Scroll Case with a Treasure Map",
"Copper Broach",
"Broken Bear Trap",
"Deck of Tarot Cards",
"Basket with several Balls of Yarn",
"Journal with Love Poems",
"Snowshoes",
"Giant Iron Fishhook",
"Tome of Gruesome Insights",
"Steel Tiara",
"Pair of Leather Slippers",
"Porcelain Doll",
"Book of Recipes",
"Medallion with a Snake Motif",
"Straw Hat infested with fleas",
"Prayer Bread of the Dwarven God of Misery",
"Manual of Ocular Visions",
"Lead Necklace",
"Eel Skin Cloak",
"Copper Offering Bowl",
"Bag of Goose Feathers",
"Vial of Dragon Blood Ink",
"Purple Crystal with a Wooden Soldier Inside",
"Grimoire of Divine Words",
"Parasol with floral designs",
"Rusty Scalpel",
"Sharp Bonesaw",
"Flask of Strawberry Liquor",
"Ornate Pipe",
"Set of Clay Pots",
"Shirt Soaked in Alcohol",
"Hollow Silver Ball",
"Sack with a Severed Head",
"Jar with Preserved Eyeballs",
"Tombstone (Has Birth date, but no date of death)",
"Ornate Copper Key",
"Wooden Training Sword",
"Miniature Orrery with gems as planets",
"Mammoth Tusk",
"Box of Pickled Beef",
"White Pearl Earrings",
"Wooden Toy Rattle",
"Silver Heart Shaped Pendant",
"Bone Hair Clasp",
"Container of Raw Honey",
"Gold Horseshoe",
"Bamboo Tube",
"Canopic Jar with Eagle Head",
"Reed Basket with Rotten Fruit",
"Spool of Silver Wire",
"Box inlaid with Cold Iron",
"Cracked Vase",
"Backpack filled with Charcoal",
"Silk Corset",
"Greatclub with Jade Spikes",
"Glass Decanter Stagnant Water",
"Oak Chalice Scorched Marks",
"Ivory Prayer Beads",
"Bag of Empty Clam Shells",
"Lead Figure with Two Bear Heads",
"Rusty Caliper",
"Silk Gown",
"Marble Bust of a Gold Dragon",
"Ettercap Skull with Emeralds in its Eye Sockets.",
"Golden Leaf",
"Shard of Slate",
"Bronze Plaque",
"Stone Disk Dwarven Runes",
"Serpentine Stein",
"Golden Flute",
"Crimson Colored Steel Hand",
"Obsidian Statuette of a Chimera",
"Bronze Measuring Weights",
"Leather Leash",
"Empty Art Frame",
"Tin Drinking Horn",
"Irregular Freshwater Pearls",
"Timber Raft",
"Stone Tablet with Dwarven Runes",
"Block of Dried Clay",
"Bleached Drake Skull",
"Bone Scroll Case",
"Panel of Stained Glass",
"Fur Cloak with Fleas",
"Water Skin filled with Holy Water",
"Lace Wedding Dress",
"Paper Lantern",
"Crown of Brambles",
"Carriage Wheel",
"Threadbare Cloak",
"Platinum Fish Scale",
"Spirit Board",
"Container with Cured Organs",
"Glass Globe with Purple Liquid.",
"Transparent Glass Chest",
"Bag filled with Goblin Teeth",
"God Braided Necklace",
"Iron Pike with a Severed Head Skewered on it.",
"Jar of Mashed Brains",
"Spiked Leather Collar",
"Belt of Faerie Skulls",
"Crate with Black Mushrooms",
"Fist Sized Silver Cube with Runic Symbols",
"Weapon Cleaning Kit",
"Poppet Doll with Needles Inserted",
"Teddy Bear with a Bag of Coins Sewn Inside",
"Horn Crown (Headdress bearing Stag's Antlers)",
"White-handed Knife",
"Animal Skin Medicine Ball",
"Mummified House Cat",
"Ornate Music Box",
"Pair of Charcoal Pencils",
"Blank Spellbook",
"Bag with 10 Obsidian Arrowheads",
"Twelve Sticks of Incense",
"Calfskin Gloves",
"Large Golden Nugget",
"Wooden Ruler",
"Pair of Iron Tweezers",
"Hemp Sack filled with Raffle Tickets",
"Porcelain Matryoshka Doll",
"Platinum Clover Charm",
"Warped Quaterstaff",
"Rusty Manacles",
"Brass Tongs",
"Eagle-Shaped Electrum Letter Opener",
"Nigh-Blue Silk Robe",
"Block of Aged-Cheese",
"Copper Coat Button",
"Bouquet of Dead Roses",
"Mithril Key",
"Vial of Gold Dust",
"Silver and Gold Tooth",
"Zinc Rod",
"Box of Volcanic Ash",
"Dozen Silver Spoons",
"Calligraphy Kit",
"Beaver-Skin Boots",
"Bag of Malachite Powder",
"Bison Fur Cloak",
"Belt of Shriveled Halfling Hands",
"Velvet Pouch with a set of Playing Cards",
"Barrel of Olive Oil",
"Elk Thighbone",
"Solid Gold Idol",
"Dire Bear Pelt",
"Brass Peacock with Ruby Eyes.",
"Miniature Clockwork Dog",
"Pair of Drake-Skin Gloves",
"Cobra-Shaped Earrings",
"Plush Orcus Toy",
"Onyx Comb",
"Jar of Dried Seeds",
"Vial of Orc Sweat",
"Hollowed Unicorn Horn",
"War Drums made of Bamboo and Dragon-Skin",
"Deer Antlers",
"Stone Tablet etched with the True Name of a Demon",
"Severed Finger with a Jade Ring",
"Plague Doctor's Mask",
"Portrait of a Naked Elven Maiden",
"Coral Ring",
"Jagged Wooden Beam",
"Book with Lumberjack Poems",
"Dented Tin Crown",
"Tome of Goblin Art",
"Wax Sealed Jewelry Box",
"Tortoise-Shelled Snuffbox",
"10 Sheets of Vellum",
"Small Wooden Mermaid Statue",
"Ivory Finger",
"Bowl of Sugar Cubes"

]

