var rich_pocketloot = [
"fine cigars ",
"a small pocket-bottle of 100-year-old whiskey",
"a deed to land nearby",
"the combination to the safe back home",
"a very potent healing potion",
"a large [Gem]",
"Tickets to a fancy event",
"a business contract",
"expensive perfume",
"a deck of exquisite playing cards",
"a fancy pocket watch bearing a short inscription",
"an ornate brass key",
"a pouch of ruby red powder that smells potently of spices",
"a faded and well-worn love letter.",
"a small and very sharp knife",
"a tin of fine snuff",
"a gold ring with script along the outside in a strange language",
"A three-channel ink feed fountain pen",
"A pocketbook complete with calendar, memo, and maps of major cities",
"Business cards with their name and place of business written on them",
"A key with a random number written on it",
"A gold locket",
"An herbal remedy for their sick/dying loved one",
"A wedding band",
"A chit from an illegal fighting ring",
"A crumpled silk mask splashed with blood",
"A monogrammed handkerchief from a rival house that smells of fine perfume",
"A greasy scrap of parchment with the phrase 'The Maimed Goblin, midnight, three nights hence. Or else!' badly written on it",
"A pamphlet promoting a rally for workers rights",
"A gold comb",
"A small silver tin of narcotics",
"A small notebook filled with passphrases and passwords for elite clubs, facilities, guilds, etc.",
"A small notebook filled with blackmail secrets about the powerful nobles or various people of power",
"Ticket to pick up a piece of artwork that was being restored",
"Ticket to pick up a commissioned magic item or valuable piece of jewelry",
"A small medallion for a secret society",
"A pair of opal earrings",
"A treasure map",
"A golden harmonica",
"A fancy decorated compass",
"Silver cufflinks",
"Room key for the best brothel in town",
"Several of his staff's pay packets",
"The private contact information for the owners of several high-end businesses",
"A small pen shaped object that alchemically removes stains from clothes",
"A page of a child's homework, clearly extremely advanced, with a note to the parent",
"Loaded dice",
"a double sided coin",
"A silver dog whistle",
"A couple of tickets to a theatrical production",
"A pair of fine white gloves",
"A lucky game piece of fine make",
"An exquisite, and impeccably kept dagger",
"An avocado-sized seed kept inside a handkerchief",
"An orb of black shiny stone",
"A letter from an old acquaintance",
"A couple of dried horse treats in a small bag",
"A deed to a pub he just won in a game of poker",
"A whalebone toothpick",
"A silver flask with fine spirits",
"A bit of jerky",
"The name of a contact in the seedier part of town",
"A stoppered test tube with odd purple liquid in it",
"A can of Mr. Muscles Mustache Miracle Wax, slightly used",
"A small dictionary of terms related to a specific trade or industry, e.g. shipping, magic, metalwork, etc.",
"A small translation dictionary of common words and phrases from another language",
"A diary",
"A trading logbook",
"A letter from a lover",
"A small opaline sculpture of a moth that glows softly in moonlight",
"A soft leather purse full of foreign currency",
"A chunk of topaz embedded in a piece of sticky, lint covered toffee",
"A reprint of a banned book, the last copy thought destroyed decades ago",
"An overly large coin stamped with the original owner's smiling visage on one side and their frowning face on the reverse",
"A small bag of expensive sweets/chocolates",
"An ornate broach with a broken clasp",
"A cameo with two different men depicted",
"A single gold coin with the face smoothed down from constant rubbing",
"A pair of gold-rimmed eyeglasses",
"A self-lighting pipe carved from a red dragon's fang",
"Platinum pocket change",
"A well-worn rag doll that's been lovingly cared for",
"A 'lucky' wererabbit's foot on a silver chain",
"A tarnished ring bearing the signet of deposed royalty",
"an envelope containing blackmail for a local politician",
"fancy buttons",
"an expensive chess piece",
"an invitation to a wedding",
"a note to a known assassin with a PC's name on it",
"an embroidered handkerchief with an image of a duck swimming in a pond filled with gold coins",
"a tiny framed portrait of a child",
"An envelope containing blackmail for a local politician/lord",
"A gilded rodent's skull",
"A crystal magnifying lens set in an ornate frame of black metal",
"The remnants of a hastily cut peace knot",
"A tawdry chapbook with seemingly random words underlined",
"The Last Will & Testament of Hieronymus J. Fletchster; Landgrave of Northkeep, Admiral of the Seventh Fleet & Bastion of the Realm",
"A scrimshawed scroll case sealed with gold-flecked wax",
"A sheaf of thin mithral tablets granting the 'Bearer Hereof' exclusive trading rights with The City of Brass",
"An elaborately illuminated manuscript on the nature of beholder reproduction",
"A prosthetic eye carved from amber with a sliver of obsidian shaped like a cat's pupil embedded in the center",
"A laundry ticket folded inside a piece of paper. The paper reads: 'Pick up Danny's uniform from Adelman's Tailors after 3.'",
"An iron key with a ribbon tied to it. The ribbon says 'Box 824'",
"A small packet of stimulant powder, a popular drug among merchants and financiers in this region.",
"A lit everburning match kept inside a small tube made of bone"
]
