var shop_names = [
"Gnome Depot. - Blacksmith",
"Balthar's Blunts & Blades - Blacksmith",
"Bloodbath and Beyond - Blacksmith",
"Rusty's Discount Sword Emporium - Blacksmith",
"Hammer Time - Blacksmith",
"Curious Forge - Blacksmith",
"Mr. & Mrs. Smith - Blacksmith",
"Metal Matters - Blacksmith",
"Kronk's Krushers and Kleavers (Orc Blacksmith) - Blacksmith",
"The Fancy Forge - Blacksmith",
"The Big Hammer - Blacksmith",
"The Block and Anvil - Blacksmith",
"The Iron Skillet - Blacksmith",
"Volcano Forge Services - Blacksmith",
"Magma Man - Blacksmith",
"The Snapped String - Fletcher",
"Straight Arrow Co. - Fletcher",
"Target - Fletcher",
"Aster's Winch - Fletcher",
"The Pointy End - Fletcher",
"The Oak and Sinew - Fletcher",
"The Bound Accuracy (one of my favorites) - Fletcher",
"The True Shot - Fletcher",
"The Hunter's Mark - Fletcher",
"Swish 'n' Stab - Fletcher",
"Featherfall Emporium - Fletcher",
"Straighten Arrow Path - Fletcher",
"The Crying Cow - Leatherworker",
"King's Cow Leathers - Leatherworker",
"Tan My Hide Leather Emporium - Leatherworker",
"Bracers and Bootstraps - Leatherworker",
"Now You Dye - Leatherworker",
"The Hide Hide - Leatherworker",
"Big Tanner - Leatherworker",
"What's Left of the Cow - Leatherworker",
"Octavius's Outrageous Oddities - General Store",
"Trinkets and Baubles - General Store",
"General Nonsense - General Store",
"Wild Widget's Wondrous Warehouse - General Store",
"Harkin's Dry Goods - General Store",
"The Big Deal Storehouse - General Store",
"Crow's Nest Fishing and Tackle - General Store",
"The Ration Shoppe - General Store",
"General Goode's General Goods - General Store",
"Masterwork Faster Work - General Store",
"Chimera Supplies - General Store",
"The One Stop Shock Shop - General Store",
"Every Day Elixirs - Potion Shop/Alchemist",
"Victorious Secret - Potion Shop/Alchemist",
"Bottle Shock - Potion Shop/Alchemist",
"The Secret Ingredient - Potion Shop/Alchemist",
"Rosie's Cauldron - Potion Shop/Alchemist",
"The Green Thumb Apothecary and Herbalist - Potion Shop/Alchemist",
"Spoon Full of Sugar - Potion Shop/Alchemist",
"Boils and Bubbles - Potion Shop/Alchemist",
"The Triple Titration Triage - Potion Shop/Alchemist",
"Puffery and the Magic Dragon Apothecary - Potion Shop/Alchemist",
"Wizards of the Coast - Arcane Shop",
"Discount Enchanters - Arcane Shop",
"Mages for Ages - Arcane Shop",
"Arcana Farmers - Arcane Shop",
"The Blind Witch - Arcane Shop",
"The Fair Wizard - Arcane Shop",
"The Strange Incantation - Arcane Shop",
"Arto's Arcane Assemblage - Arcane Shop",
"How do you Spell-It - Arcane Shop",
"The Magic Circle - Arcane Shop",
"Abi-Dalzim's Horny Wildlings Shoppe - Arcane Shop",
"True Resurrection Depot - Arcane Shop",
"Tomes Aplenty - Arcane Shop",
"Wall-Mart - Stonemason",
"Rocks and Rubble - Stonemason",
"Careful Carvers - Stonemason",
"Hammer and Chisel Stoneworks - Stonemason",
"GRANITES AND MALACHITE - Stonemason",
"BAM BAM'S HAMMER SHOP - Stonemason",
"ROCK DEALS: WE SELL ROCKS - Stonemason",
"Jabe, Mulwithickle, and Fayeid, Tea Merchants",
"Sacril’s Tobacconist",
"The Swordsharp Man",
"Hatter’s Halberds",
"Whittlewood’s Grocery Emporium",
"J.E. Jebs and Sons, Undertakers",
"Quottle and Partners, Quality Distillers and Alchemists",
"Urah Quell Brewers",
"H.R. Lobb and Daughter, Antiquarian Maps and Tomes",
"Jogg’s Butchers",
"Alanna’s Answers, Full Service Divination",
"Peppermint Palace Pastries",
"The Crow’s Nest Ropes and Rigging",
"Hugor’s Statuary and Memoria",
"Tuttle and Weft, Ladies’ Quality Garments",
"The Wine Warehouse",
"Dor and Totter Junkyard",
"Cakran, March, and Spade’s Spices from Far Shores",
"Dobber Cartwright’s Carts, Carriages, and Coaches",
"Milk and Dairy Farmers’ Hall",
"Elnore’s Copy Shop, Skilled in Five Languages!",
"The Shark Tooth Seller",
"Manem’s, Jewelers by Royal Appointment for 400 Years",
"Yuran’s Knife and Blade Sharpening Shop",
"Lavender and Perfumes",
"Murran’s Self-Defense Academy",
"Dorrie’s House of Discreet Delights",
"Urgin’s Hair and Tooth Removal",
"Warred’s Perfumery and Incense Emporium",
"Dokk and Gyorgi, Royal Wig Makers",
"Told’s Tannery and Leather Goods Warehouse",
"Mother Cotter’s, Seamstress",
"Trackady’s Curios and Components",
"Artham’s Runners, Linkboys, and Messenger Firm",
"Hardware, Metalware, and Household Emporium",
"The Sealing Wax Company",
"Grig’s Hourglass Bazaar",
"The Flea Market",
"J.M. Wortley’s Healer and Chirurgery Suppliers",
"Optical Objects Trading House",
"P.P. Partwill’s Weapons and Wares",
"Purple Crescent Puppet Theater",
"The Portable Ram Shop",
"The Oil and Coal Barrow",
"J. Hartlin’s Snuff Shop",
"Maps by Maurice",
"Books, Tomes, and Ledgers",
"Wood Paneling by Mennel Doorbry",
"Gentleman’s Furnishing Entrepot",
"Three Coppers Secondhand Goods",
"Brawler General Weapon Stores",
"Bloodbath and Beyond Weapon Stores",
"Maul Mart Weapon Stores",
"Maces Weapon Stores",
"Daring Queen Weapon Stores",
"U-Maul Weapon Stores",
"Gordon Feud Service Weapon Stores",
"Sam’s Clubs Weapon Stores",
"Clubway Weapon Stores",
"Slay Mart Weapon Stores",
"Star’s Buckles Armorers and Tailors",
"Crusader Joe’s Armorers and Tailors",
"Valor City Armorers and Tailors",
"Brass Pro Shop Armorers and Tailors",
"Old Bravery Armorers and Tailors",
"Shield Carnival Armorers and Tailors",
"Yankee’s Sandals Armorers and Tailors",
"Vest Buy Armorers and Tailors",
"Victorious Secret Armorers and Tailors",
"Cautious Depot Armorers and Tailors",
"Target Fletchers",
"Best Bow Fletchers",
"Shooters Fletchers",
"Aim Stop Fletchers",
"Gnome Depot General Stores",
"Little Caesar’s General Stores",
"Good Will’s General Stores",
"Gnome Goods General Stores",
"Bards N’ Nobles General Stores",
"Potsmart Alchemists/Herbalists/Magic Goods",
"Seer’s Alchemists/Herbalists/Magic Goods",
"Olive’s Garden Alchemists/Herbalists/Magic Goods",
"The North Vase Alchemists/Herbalists/Magic Goods",
"Herbs ‘n Outfitters Alchemists/Herbalists/Magic Goods",
"Jar Max Alchemists/Herbalists/Magic Goods",
"Djinni John’s Alchemists/Herbalists/Magic Goods",
"Hot Tonic Alchemists/Herbalists/Magic Goods",
"Circlet City Jewelers",
"Ruby Lobby Jewelers",
"Opal House Jewelers",
"Tuesday’s Rubies Jewelers",
"Plato’s Garnet Jewelers",
"Long John’s Silver Jewelers",
"Madame Ortho’s Oddities: A curiosity shop that sells useful (sometimes cursed) trinkets. Examples of some of her wares: a mummy hand that tries to strange it’s owner while they sleep, a compass that points to the person that hates the owner the most, and a stuffed Vargouille.",
"The Cobbler: A store that sells all kinds of horseshoes, for all kinds of reasons, but you notice, this town has no horses.",
"A Man’s Burden: A blacksmith who displays and sells exotic weapons, made using blueprints gathered from across the land.",
"Row after Row: A store specializing in boats, specifically, boats that use rowing to move.",
"Gertha’s Topography: A woman who sells maps she has found and made across the continent, from huge full continent maps to small maps of ruins and towns.",
"Fran’s fortuitous froths: potions of dubious origins and craftsmanship, they almost never work as advertised, but always help you in a way you didn’t know you need.",
"Sofie’s softies: pillows of the highest quality, stuffed with feathers of magic beasts, and enchanted with various effects.",
"All the RAGE: battle axes and fashionable shirts.",
"Wrench warfare: magic craftsman tools that can change into weapons. Great for sneaking weaponry past the border or into the castle. You can place custom orders.",
"Caesarean’s Palace – “Veni Vidi Veni”: The strip club on the bad side of town.",
"Head, Shoulders, Knees, and Toes: A store ran by a mysterious wizard, it only sells human appendages.",
"The Lotto Grotto: A store that sells magical items, but the item could be cursed or enchanted, and the buyer only knows after using it once.",
"Gertrude’s Trinkets:A dingy magic shop on a back street that sells surprisingly good (we’re talking some top notch stuff here) magic weapons and trinkets for ridiculously low prices (half the price of normal on average). At midnight anything bought from the shop returns back to the shop magically, and the shop teleports to another remote location.",
"The Satyr’s Pact: A tavern run by a satyr who offers musicians a deal. If they impress him and the crowd with a song they earn a instrument that is always in tune and free room and board for life. If they fail, they work in his tavern for a decade but can audition again for the same deal, years do add up.",
"Rock Candy: Sells and buys a wide variety of gemstones. The shopkeeper is an Oread who has a tendency to eat the product, much to the dismay of the shop owner.",
"Scrumdidilyumptious: This bakery is owned by a sorcerer whose focus is on her craft. She likes to infuse her goodies with spells, from rainbow cookies that make your tongue temporarily a new color to a slice of chili cake that makes your fire spells scarily more potent for a while.",
"Munsters R Us: A tiny Pug stands at a crate, hollering in broken common to come over. He’ll buy your scavenged monster parts (albeit at varying prices) from you. If you give him enough, he’ll turn them into an item. It’s disturbing, but how can you resist his cute lil’ face?",
"Furever Homes: Offers small and under-sized creatures as animal companions and pets. They have the basics, like rats, spiders, etc., but if you have enough money, you could adopt more exotic creatures.",
"The Mountaineer’s Bandolier: Sells survival kits, potions that help you adapt to weather, and various supplies that help explorers get through tough climate situations.",
"Fizzlesprocket’s Dairiticiary: A quirky gnome runs this ice cream stand and tries to pawn off bizarre treats. You won’t know if you like it till you try it.",
"Blood letting: general store takes payments in different kinds of blood.",
"Binxes potions: potion store run by the Sanderson sisters from hocus pocus. Don’t let kids near this place they have an unfortunate habit of disappearing.",
"Morticias morgue: will hide and remove bodies, perform autopsys etc in return for rare bodies/monster parts.",
"Tinker and sons: apocalyptic/doomsday prepper family of ghomes will fix, repaid or mod weapons in return for canned foods, junk weapons and scraps of metal.",
"Fallen from a star: A well known bar/pub can find different celebritie style characters like Worgen Freeman or Clint Westwood.",
"Seamus the Imp Peddler: A travelling peddler, riding a covered cart led by a mule, stops by the party. He explains that he specialises in the sale of imps, but so far the only ones he has been able to obtain (trade secrets and all) have limited lifespans. It’s a mixed bag in his opinion so all the imps cost the same. Imps cost [1d20/1.33] GP each, half this if it’s raining. On purchase the imp is bound to the character until the imp’s unique demise. Each imp has a craving and a fear; if the character is helpful in these regards the imp’s loyalty will improve. Each imp also holds a secret agenda of mischief.",
"Herb the Hatters: Herb makes exquisitely beautiful hats which are quite uncomfortable.",
"The Transport Tube: Any common item will fall down from a tube from above, assuming something of value has been put in the slot in the cubicle. Approx 5ft square circle room. Out the back, some creatures would be feeding the items in.",
"Murray’s Theatrics: The half-elf Murray retired from the life of a wandering bard eight years ago, but still loves the trade dearly. His shop (which is really just the anteroom to his house) stocks sheet music and scripts for the lutist looking to expand her repertoire, or the troupe seeking to get ahead of the new fashion in comedies. The texts cost next to nothing – Murray remembers what it’s like to travel on a performer’s income. The real money comes from his younger brother, Astor, whose potions create audience-dazzling special effects.",
"The Furrowed Brow: Esmeralda Turnbottom’s mother made wards, and her mother made wards, and her mother made wards… And Esme has never been one to spoil a good tradition. The wares range from mundane (a pendant against forgetfulness, carved from gingko bark) to the specialized (ground cat’s tooth to drive off harpies). Once a year, she closes up shop for a much deserved vacation, and returns with an armful of oddly specific wards. Such as “protection from a stampede of your own cattle frightened by a thunderclap on a moonless summer night”. And yet they always get bought, and they always end up useful…",
"The Sizzler: An exotic restaurant run by a very jovial, and very fat, half-ogre named Thog. They specialize in rare meats of all kinds and will pay well if what you have is fresh. From drake wings to spider legs, if it’s fresh and serviceable they’ll buy it. Their meals are renowned for being tasty and surprisingly filling, and the exotic nature of their ingredients has been known to impart certain temporary boons to the consumer. The house special is constantly changing, so get in quick before the line forms!",
"Nero’s Place: A shop run by an aging, paranoid neurotic elf that is convinced there’s a demon after him. Nero sells a wide assortment of scrying crystals, mirrors, looking glasses, and patented listening tools that he uses on a daily basis. Some of his inventions are actually helpful, like his ‘Peek-around’ that angles two mirrors inside a square tube to look around corners. Others are less helpful, like his ‘Hearing Helm’ that is basically two gramophone bells welded onto a bucket. He also sells protective charms and wards to help keep… well anything off your back, really. For the paranoid inside us all, Nero’s Place is the Place for you!",
"Goldie’s Locks: a wig shop selling enchanted wigs that are just right.",
"The “ooks” Store: A dingy store front window displays “ooks” peeling gold lettering. Inside the dimly lit shop are shelves upon shelves of musty old volumes fill up the space until only narrow paths await the adventurous customer. After searching the store you might find what you want…or need in the future.",
"The Amazing Omar’s Shop of Curiosities: Omar, a flamboyantly dressed merchant waves, you over to his display wagon to view his wears. Various charms, potions, knick-knacks, and unguents are on display for all to see. If you are a polite and interested customer he may be persuaded to showcase his more interesting items…",
"Adon’s Exceptional Reflection Collection: A good sized shop that sells mirrors of various shapes and sizes, run by a reclusive and eccentric old gnome named Adon. Mirrors hang from almost every surface, with some even dangling from the ceiling or the bottom of other mirrors. It is incredibly easy to get lost wandering the store, and the inside seems significantly bigger than its outside appearance belies. An observant customer will notice that some mirrors occasionally reflect fantastic locations with startling realism.",
"Ketterman Barley’s Stonecarving and Statuary: Ketterman is a stone carver of some renown, and does all kinds of stonework from bas-reliefs and fountains to statues and headstones. He’s expanded his business recently by offering smaller, personal busts of the client for a reasonable sum, depending on the quality of the stone. Ketterman typically sells to the upper class, but as long as you can pay he’s more than willing to work with just about any customer. But here’s the catch: Ketterman is actually an accomplished diviner as well. Every time he carves an eye into his stonework he can use those eyes to scry through at any time. Ketterman uses his vast network of eyes to spy on anyone within their gaze, and if he comes across something particularly noteworthy he sells that knowledge to the highest bidder, or uses it as leverage for blackmail under his assumed alias of ‘The Emerald Pool’ (because his eyes are green). Ketterman has been operating for almost two decades now, and his work has traveled far across the land. Odds are his stone eyes have seen something you didn’t want to be seen. So tell me friend; what are you hiding?",
"Blood Of Thy Enemies/Blood Of My Blood: Half the shop weapons & instruments of death run by tiny, aggressive woman. The other half a healing shop run by a large barbarian type man who’s gentle. They are a couple…opposites attract?",
"Rats, Bats, & Vats: Your typical cauldron witch type store. Alchemy, herbs, could be run by hag.",
"Kern The Hammer’s Hammers: Shout out to Critical Role. Half-Orc Kern The Hammer has given up on fighting in the pits after the loss to Grog the Barbarian, the shop has every kind of hammer you could ask for.",
"Maybe It’s Adamantine: A clearance type shop of magical items. Genuine as advertised Magical Items are in stock but rare. Lots of faulty or completely misidentified items. Create any additional rules, such as refund any item after purchase but at 30% of it’s value, no identify spells allowed on store premises, etc.",
"Ninth Level: Hell themed. Run by a demon or devil. Opportunity to buy existing contracts or forge a new one.",
"Mendelsen’s Magnificent Mending: Mendlesen is the most talented mender in the world. Clothes, artifacts, magic items, you name it & he/she can mend it.",
"Carts & Crafts: Every kind of vehicle for sale & rent. Can purchase passage on different methods of transportation as well. Purchases come with option to register as a transporter to provide passage & collect fares.",
"Dark Arts & Melted Hearts: Your typical “Dark Arts” type store, but complete with a tavern type meeting area that regularly provides a speed dating-esque environment for undesirables, villians, & general ne’er-do-wells. Everyone deserves a shot a love right?",
"The Dock of Many Flings: A store either on the water or with a large well inside. There are no items, only shelves and shelves of pebbles worth different tiers of gold. You buy a pebble, then stand over the designated area and cast your pebble into the water. You gain a random magical effect, item, or etc. (eg. A Mini or alternate deck of many things)",
"Whispers & Secrets: The only goods bought and sold here are rumors, secrets, other generally unknown information. You cannot pay with traditional currency, must offer hidden information of your own to barter with. Use either an unbiased magical system (such as speaking your secret into a glass jar, putting the lid on placing upon a magical scale that determines it’s weight/value), or for more interesting roleplaying opportunities have a totally biased shopkeep the players can haggle with or try and persuade.",
"Proctor & Son’s Deadly Traps: More a small dungeon than a store, the ceiling to floor to finally the basement is covered in traps. You must survive long enough to actually disarm and then purchase your chosen traps. It used to be a family business but that didn’t last for very long.",
"Impeccable Times: In a building stylized as a home befitting a cuckoo clock, the sound of ticking from countless mechanisms dominate the senses. The blind elderly craftsman shows no concern for anyone except his owl which is never far from his side. Secretly, he can hear from every watch and see from every clock he creates. The owl is also a mechanical contraption.",
"Ayesha’s Insult Emporium: The store’s name, in simple black lettering, is all that infers what lies inside. A friendly middle aged woman (presumably Ayesha) wearing a sari greets customers entering this store’s antechamber with a sharp personal insult. Anyone who takes great offense to the insult is teleported out of the shop and can’t re-enter. However, those who accept it in good spirit will be led by Ayesha to the main room which contains shelves and cabinets filled with scrolls, books and scraps of paper containing some of the most brilliant, sought-after and mind-bending insults to ever have been uttered or penned.",
"The Green Room: This inn, hidden by an entrance in the sewers, provides lodging in rooms made completely of thick glass. The floors consist of different types of soil, and beds are constructed from clay with meagre hay mattresses. Patrons that stay the night develop a slight green tinge to their skin that persists for a week. For this duration, as long as one stays in direct natural sunlight for at least 4 hours a day, they need not eat. Sleep is required as usual, and water requirements per day to survive are doubled.",
"The Potato Is Just An Illusion: A comedy club and tavern frequented by illusionists, diviners and enchanters. Patrons dine, drink and listen to wizards from the local guild tell comedy that is usually highly academic in nature and augmented by various creative illusions. STRICTLY NO IMP FAMILIARS ALLOWED.",
"Piander’s Books: A poorly lit bookshop filled with books of ancient lore. Run by a seemingly mute man in a dark cloak, he watches visitors closely from the shadows.",
"Alethra’s Tear Shop: A medium sized store with shelves full of tiny bottles of tears, the are all carefully labeled with the date the tears were shed, the name and race of the being that shed them, and the reason they were shed. Run by a middle aged woman named Alethera, an unusually cheerful woman who is as eager to buy new tears as she is to sell them. Alethera is especially interested in the tears of adventures and famous people.",
"Adventure’s Emporium: On the outside it looks abandoned and if you ask around town you will be told it is cursed or haunted, but when adventures enter the building they enter a spacious, well lit store full of ten foot poles, iron spikes, torches, and other adventuring gear. It is run by a retired adventurer.",
"Darvin’s Dandy Dolls: A shop with shelves full of dolls, many of them resemble important political figures of the region. It is rumored that some of the dolls have power over the people they represent.",
"Sprog’s Spirits: A dark shop run by a well tempered and grim half orc. It’s shelves are filled with bottles that Sprog claims hold the spirits of the dead.",
"Anton’s All-porpoise Absolutions: An office run by a cleric of a god of mercy. A place where kings and commoners alike go to repair their relationship with their gods and other extraplanar patrons.",
"Magroma’s Jewelry: A “jewelry store” run by an old woman where all of the jewelry is made out of the polished bones of various creatures, some of them quite exotic.",
"Arcadia Glass: A small shop with shelves filled with tiny and exquisitely beautiful glass statues. Run by a half elf, behind his desk he has a small collection of graphic statues that appear to depict past and future events.",
"Gulthric’s Curiosity Shoppe: A mostly nondescript store from the outside, this shop is run by an old copper dragonborn. The inside of the shop is sectioned off with all sorts of magical items for sale, and there is the slight smell of incense. The shopkeeper will sell magic items in trade for a true story. The more important the story is to the character, the more likely they are to receive a more powerful magic item (limited within DM’s reason, of course). Magic items range from a large selection of small trinkets to a rather limited selection of powerful items.",
"Fletcher’s Hunting Goods: A traveling fletcher who makes high quality bows and arrows. More likely to be seen in a frontier town or on the trails in the wilderness.",
"Clara’s Haberdashery: a half-orc woman makes and sells fashionable hats to normal patrons, but sells magical hats on the black market. Her hats are imbued with special abilities by using rare and wonderful items. She’s an artist to her core and she’ll try to accommodate your request, but at the end of the day, it’s her final word. Imagine wild versions of hats you know, precursors to hats we have now, but much more ornate and fanciful.",
"People, People!: It’s a shop where you can hire people. There’s different races and strengths of people for different prices. You can hire a commoner for 1 gold as usual, but there’s a few stronger people, or twin halflings that come as a bundle, or an old lady that’s very expensive. There’s not usually shops where you can easily hire people. Here one is.",
"The Flying Dutchmans’ Insurance Agency: A pair of brothers, The Dutchmans, enchant items to levitate back to a predetermined location after using a keyword. Useful for if an item is stolen.",
"Mounds of Masks: A disorganized store stuffed with various masks of all kinds. Owned by a retired, deranged playwright who is rumored to have fallen into the occult.",
"Dundragon Family Goods: This store appears to be an average general goods store run by a small family of three, a father, a mother, and a daughter, but any local criminal will know that “Dundragon Family Goods” is actually the best place to find illegal supplies without attracting attention, as the whole family knows thieves cant.",
"Ship Shape Ships: A shipwrights store that constantly smells of the sea. Behind the shipwright’s desk are a collection of model ships in bottles that represent real ships, and whoever owns these models owns the real ship.",
"Stiletto Emporium: Stilettos give bonuses to charisma on female characters, but reduce speed and increase noise.",
"Beets Beets Beets!: They sell Beets!",
"The Weather Station: They have bottles of weather. If you open a bottle, the weather inside comes out and fills the room.",
"The Rusty Key: Sells Keys. Sells rings of keys. Sells keys for specific areas or boxes. Simple keys, giant keys, intricate keys, one magical key. They recommend using keys for decorative purposes only.",
"Dirt’s Dirt: Sells dirt. Also small stones. sells mystery dirt and a “dirt mystery bag” that has dirt plus one item in it.",
"Balloons and darts: Every balloon purchase also comes with darts. You can get transport on a hot air balloon and tons of darts. Balloon animals and dart animals. Buy a balloon (and dart!) and get a balloon (and dart!) free! [On walking out, the dart is thrown at the balloon].",
"Rosewaters: Sells tinctures of water. Rose water, holy water, filtered water, spring water, toilet water, alcohol water, etc.",
"Lukas’ Lucky Oddities: At the start of each day, Lukas rolls twice on the trinket table and chooses one trinket. He must sell it for an exorbitant price before dusk. Such is his curse.",
"Madame Tralancet’s Veritable Shop of Disguises and Costumes for the Modern Journeyman: She has an enormous selection of suspiciously cheap costumes, disguise kits, wigs, and other fake parts. She has seven drawers bulging with moustaches alone.",
"Doctor Nehantil’s Reputable Establishment: In a rundown shack in a bad part of town, a half-orc woman runs reception. Give her your appointment card, and she’ll tear off the planks from the back wall where you can meet Dr. Nehantil, a “physician” with cheap prices and even cheaper services, no questions asked.",
"Mira’s Oozes: A pet store of sorts filled with living oozes of all colors stored in jars. Run by a young and naive sorceress who insists that the oozes are harmless when properly handled.",
"Temple of the Tiny: A quaint little store stocked with holy symbols and other religious merchandise, all marketed towards children.",
"Kesheki’s Weapon Shop: A store in the darkest corner of the town run by a curiously well mannered female gnoll, Kesheki. The shop sells all kinds of the most exotic and vicious weapons imaginable. The only currency Kesheki will accept are the scalps of humanoids, the stronger the creature the scalp was taken from the more valuable the scalp is.",
"Walters Watch/Warehouse/Witchcraft/Wizardry/Weaponry: Walter is an aged peddler who settled in a small town. He has a bit of everything, is the towns postmaster and guard. The shop’s sign says “Walter’s ” on the left side. The right side is a stack of signs he changes as needed. “Watch, Warehouse, Witchcraft (Herbs), Wizardry (mostly useless magic items) . When not selling he switches to “Walter’s Watch” and earns his wage as the only townguard.",
"Clifford’s Catastrophic Candys: a candy shop that only sells empty bags that fill with either just the treat you want or something utterly disgusting once you get hungry. You must eat what appears before it fills again.",
"Place Your Hand: An old shop, completely empty, run by and old human wizard. In the shop you can find only a table, and this old man sit on a wooden chair, behind the table. Over the table there is a Bag of Holding; for 10gp the old man let you pull out one random non-magical object, from a rusty pan to a brand new plate armor. Every thing is possibile in this shop! Are you brave enough to “Place your Hand” in the bag?",
"Tomes of Tombs: A shop specializing in information on death, undeath, and graveyards. Includes biographies of famous figures buried in local area as well as maps of some family crypts.",
"Old Elmer’s: A wooden building that walks on several insectile legs, ran by an aging half-elf with a wooden leg, a glass eye, and a fully animated brass hand. Sells prosthetics of all kinds, magical and mundane.",
"The Meat Place: A luxurious, popular tavern with really good food, mainly specializing in one kind of meat. An still living animal covered in scars is suspended from the ceiling, chains covered in glowing runes. Occasionally an employee comes in and cuts it up, carrying the meat to the kitchen as the animal heals. Neither the staff nor the patrons seem to have any issues with this. The animal is a 1: Pig 2: Sheep 3: Goat 4: Cow 5: Irrecognizable mass of scar tissue with a distinct taste that you cannot place. 6: Roll twice. Both. If a die lands on a 6 again, it’s a sapient being being kept against their will.",
"Frey’s Fresh Fish Flesh; A middle-aged female water genasi carrying a large Urn of Infinite Water, as well as various fishing supplies. Sells fresh fish, which she fishes out of the urn, as well as fishing supplies. Often found in deserts.",
"Skeleton Shop: A large underground complex selling all kinds of animate skeletal animals. The owner is a jovial skeleton who only accepts currency taken by force, without the previous owner’s consent.",
"Howard The Doe Has A Shop Now Come Check Out Howard The Doe’s Shop: A rundown house obviously built as a home and not as a shop. Staffed by a very excited yet forgetful doe, Howard, who insists on maintaining bipedal gait while the party is present despite being really terrible at it. Will attempt to sell anything not nailed down, and is surprisingly persuasive despite having obvious trouble speaking with her doe vocal chords and holding objects with her doe hooves. Has no actual grasp on what objects are worth or even what constitutes valid payment and will often overcharge or undercharge the party to ridiculous degrees.",
"The Tavernacle: a tavern run entirely by beer-making monks.",
"QIA – Questions, Information, Answers: This business buys and sells information, brokers missions, offers services. Gathered by magic means, bought from adventurers or received from distant locations a party can find the information it needs, learn about a mission offered by a trader or use the shops scrying or message service for a fee. This shop and some traveling business wagons are run by an elderly, stonefaced dwarf named “Harthos Adori Treasurebringer” in wizard robes with a nameplate saying “Hat Wizard”.",
"Wyatt’s Wandering Wares: This shop, run by a young half elf, is of a special kind. It appears in a free spot in a street, and when it appears it has always been there. Wyatt is a good natured trader, selling wares with magic properties that often are unknown, and always trying to play a little trick with his customers.",
"Kabooms and Korpses: A fireworks store that has been almost completely blackened by numerous incidents. Run by a goblin inventor who is also an amateur undertaker, offers to use some of his bigger rockets to give loved ones a glorious send off.",
"Dolores’ Café & Dispensary: – a public shop for purchasing all kinds of alchemical reagents and paramacutical goods for healing, potion making and poison brewing – Also doubles as a delightful café where patrons can drink hot brews of cocoa and indulge in their preffered choice of reality enhancing herb.",
"The Gold Chain: They sell gold. Great place to exchange currency types, trade figurines or valuables for gold. They sell a few gold coins with magical properties, like the boomerang coin and the communication coin. Sometimes they have slow sales so they have a “buy-one-get-one-free” deal on gold coins. Deals primarily in gold. Also can melt gold into shapes like rings and earrings.",
"Store Store: Sells stores. You can buy storefronts ranging from a clothing store to a hot dog stand. Not cheap! They also have an enchanting business, password protected chests, charms to prevent theft, money pockets that only the owner can withdraw from, and alarm bells. They also sell signs of various types, some with glowing lights.",
"The Prime Meridian: This store has one person inside with very, very shiny golden shoes. “These are my prime shoes” they say. They will sell you almost any item, and have it back to you within two days. However, there is a significant charge to getting the item, and some items might not come within two days. Unfortunately, before you can buy, the man tries to up sell you with a long list of items, and won’t begin getting your item until bombarding you with the other items. Things like a bard service to follow you around with music, a chef service to cook you food, an enchanted rock that you can talk to, but also tells him your preferences in case you come back, a painting delivery service that sends you paintings every week for you to look at, but the paintings are pretty bad, like a child drew them. Each service costs 2-3x the cost of the item they are going to get in 2 days.",
"Sew it seams: A textiles shop full of misleading fabrics and clothes.",
"*ALWAYS A WINNER!: A lottery outlet. To enter, you have to put a GP into above the doorknob. You walk in and bells go off – you’re a winner!! A crowd cheers around you and you see then number 10,000 person. A sash is placed on you. You’re the 10,000th customer! You win a large cash prize! Congratulations! You can either stop now, or take the chance to double or nothing your earnings!! The shop has a large prize wheel. Roll a D10 – anything other than a D10 loses! You just have to sign here and pay the deposit of 10 gold coins! If the PC does so, they earn the prize of 1,000 gold coins. They check their pouch and a faint golden vapor is leaving their pouch and moves toward the lottery. If they re-enter, they must pay another coin, but the building is empty."
    ]

var shopkeepers = [
"A tall and husky Gold Dragonborn, clad in bright colored and decorative clothing, sits on an equally ornate rug. He’s fidgeting with something in his mouth. It’s has a small garnet, chipped by his teeth and covered in spit. He has a small pouch in his vest full of these gross little gems. He sells very beautiful jewelry, thankfully with no bite marks.",
"Two very young Halfling brothers are making dumplings. The dumplings are way too big even for a normal sized person, but they taste pretty good.",
"A tiefling who’s missing a tooth smiles quite charismatically. He’s selling potions and poisons, but they’re stored in old, reused liquor bottles. Kinda weird, but mostly harmless.",
"This human-elf couple makes soap. They’re super happy because of their soap, which is always enchanted into putting anyone who uses it into a good mood.",
"This scrawny kobold is making guns. He loves his firearms to death, despite being too small to wield a majority of them. He just loves his craft.",
"A bald, female wizard doesn’t actually sell anything, but she enchants items for others. She also has a hairless cat, probably related to the same incident. She has looks that could kill, but she is super sensitive when someone brings up her lack of hair.",
"A young, quiet librarian sits behind a desk reading a book. When the player gets closer, they notice that she’s actually a centaur. She’s quite dainty and gentle for her size.",
"A disabled dwarf creates small trinkets from bed. His half human daughter takes care of him, but a network of clockwork beasts run his store front, taking care of sales and maintaining each other so they’ll sell for a pretty penny. Rumors about him creating a chair with wheels are spreading, so he’ll finally be mobile again.",
"An unlikely pair of merchants run an apothecary, alternatingly with one working on baubles while the other deals with customers. The dwarf is a grumpy old man, nearly unapproachable, and usually berates his half-orc apprentice even when in front of the customers. When asked, he typically overprices and generally shuts down any attempts at haggling. The half-orc apprentice is suspicious and intimidating in appearance, and sound threatening when replying to his dwarf master, but is actually much more cordial to the customers and is more lenient when haggling. Both, however, like their beer.",
"A gnome tinker who has all kinds of different scrounged and jury-rigged magic items. He appears on his cart every couple hours until the party buys something.",
"An aarakocra resembling a vulture who sells things he finds. By ‘finds’, he means he takes stuff off of dead bodies and whatever else he sees lying around. He’ll sell random pieces of armor, weapons, books, and food he cooks himself with scavenged meats and the like. He’s a great cook and a cynical old coot. His coyote & pepper stew is quite popular.",
"A thin man wearing a backpack seemingly too large to carry. Inside are various minor magic items which he sells as novelties to anyone with the cash to buy them. He is dressed in flamboyant clothing.",
"A homeless man gives advice on the town and strange trinkets in exchange for coin.",
"A cheerful dragonborn who runs a sandwich shop in a tavern. He is obsessed with incredibly spicy food, and tries to push spices on customers to ‘keep the fire burning in their stomachs’. Cooks all of his food with his breath weapon.",
"A young half elf alchemist selling concoctions out of a small bag. Her accessories include a bandolier that holds different vials, leaf shaped earrings, and a purple headband. She promises that her creations work, however the shakiness of her voice don’t inspire confidence. She’ll get overly excited when she makes a sale.",
"A scarred, brutish orc selling finely crafted jewelry. if engaged in conversation, he reveals that he only took up the barbaric ways of his people because of peer pressure. Eventually he went adventuring and then decided to pursue his lifelong hobby of crafting rings and necklaces and the like. His clan must believe he is long dead by now.",
"A young human wizard, yet to lose his baby fat and with no sign of facial hair can provide advanced spell scrolls, but always refers to customers as ‘youngster’ or ‘whippersnapper’. When asked about it, he becomes very upset, muttering about curses and kids not respecting their elders anymore.",
"A old human luthier with a grey mustache and coke bottle glasses. He’s always working on something and refuses to look away from what he’s working on for more than a second. His teenaged son does most of the dealing, however he spend most of his time playing with the merchandise. The son will keep playing when spoken to and will inform everyone that his band is playing at the tavern that night. Before making any deal he will walk over and ask his father if the deal is fair.",
"A slender, well-mannered man sells curiosities in a travelling carriage. He has a pet mimic that has taken the form of a small lockbox, which is somehow very well trained and obedient.",
"A female high elf with shoulder length auburn hair and named Mary Jane sells herbs, fruits and vegetables from a large wagon pulled by a pair of mechanical oxen. Many of the herbs are seasoning; some have medicinal uses and a few have ‘recreational uses’. Her partner, a shy male Halfling named Timmy who barely speaks to anyone, but, if you can befriend him, he can sell you a few herbs and roots that are useful in toxin manufacture.",
"A sphinx who sells minor magical items in exchange for new riddles.",
"A quick tongued elven female who has a reputation of being a snob. She often wears a colorful dress that’s skirt reaches down to her knees, several different pieces of jewelry, and a small leather bag that has the symbol of her merchant clan on it.",
"A halfling peddler who roams town to town selling wears from his ‘many adventures’. If the party sells him something, say a blanket, they might find it for sale in the next town over. The blanket will have some story such as how hiding below it prevents ghosts and goblins from seeing you, or maybe it had kept him warm in the snow capped mountains and was the warmest blanket ever. He will be selling for three times what he paid for it at the least. If you want to add another layer of mystery. The things he says the objects can do actually happen. Aside from the obvious abilities the goods have, they are clearly the same goods the adventures and townsfolk sell him. Down to a wierd stain or carved initial. He is smart enough not to sell goods in the places he bought them.",
"A smith, a ’90s waif who only weighs 90 pounds if she’s carrying hammer and tongs. She’s tiny, the size of a human ten-year-old. She makes big, heavy things such as plate armor, tower shields, pole arms. They’re of masterwork quality. She’s not deceptively strong, either: she can barely raise the hammer above her shoulder. There’s no enchantment or anything else involved; nobody has ever been able to figure out how she does it.",
"A kobold sells ‘Enhanced’ potions at a discount from a dingy shop sandwiched between two larger, more reputable stores. The proprietor is somewhat vague on exactly how the potions have been enhanced. They do exactly what the label implies, though (‘Ideally,’ the proprietor insists,) they frequently come with an additional effect. This ‘Enhancement’ can range from enhancing the user’s physical and mental faculties, to making the user’s skin turn blue for hours, to making the user’s tongue taste like bathwater. A particularly intelligent user may be able to determine the side-effect before using it. The rest simply have to hold their breath, drink, and pray.",
"A tall lanky shop owner who can’t seem to get warm. He wears several sets of clothes at once.",
"A very grumpy half-orc who gives customers what they want, but does not take requests. His prices are excellent, but he will only sell one item of his own choosing to each PC.",
"A toothless, vegetarian lizardfolk who sells poultices and other herbal remedies. He claims that he was cursed to have no teeth and took up a different diet out of necessity, and he grinds up his food into a puree so he can eat it properly. His scales are a sickly yellow and he’s almost always bent over his table, grinding up and boiling down various common and exotic plants, all of which he grows or buys himself.",
"A bizarrely dressed human with a strange beard and haircut. He brews coffee and spends hours perfecting it so he could find the purest, most flavorful blend. In reality, it’s just normal coffee. When being told this, he responds by saying that they aren’t cultured enough to understand the depth of the flavor. He’s incredibly cranky and pretentious for his age, so almost nobody likes him.",
"A dust genasi who sells a huge variety of cleaning supplies. Brooms, mops, soaps, various scented oils, you name it. He’s constantly leaving a trail of dust around and cleans it up as it gets made. When it’s pointed out that he’s doing a fruitless task, he becomes extremely sarcastic and thanks them for pointing out the obvious. Other than that, he’s pretty laid back.",
"A Warforged merchant that sells scrap metal, logs, wagons and parts to assemble your own Warforged bodyguard. Oh, and he has some healing potions at discounted prices because ‘What would anyone use them for?’",
"This unidentifiable person is clad in a bright blue robe and an opaline mask. Their hands and feet are bright blue as well. They sit on a pretty standard rug, cross legged and swaying side to side. His rug is NOT for sale, because he always mentions it before talking to a customer, along with a large tag that says ‘NOT FOR SALE’ on the side. He sells various items, all with some sort of minor magical effect. He doesn’t say much except for strange things like, ‘What’s your favorite color? Mine’s blue.’ and ‘I like your haircut.’ When the party leaves, he quietly hums to himself and disappears as soon as he’s out of earshot. Nobody knows who or what you’re talking about when you try to mention him.",
"A strangely happy man in a cart pulled by horses. He smiles extremely wide and creepily. He’ll offer free items to the party, like food, if they come into his cart and grab it. You probably should’ve noticed this was a highly advanced mimic, due to his mouth not moving when he talks and the walls of his carriage looking kinda fleshy.",
"A quiet woman lies lazily on the back of a smooth-shelled ankylosaurus. The anky’s name is Bailey, and she’s just a big puppy dog who likes being pet. The merchant (named Rachael) sells books, and buys books. She also gladly accepts food for her anky. Bailey likes corn a lot.",
"A triton fisherman riding the back of a colossal catfish, with a small tent on its back. He has wide variety of fish stored in small barrels in preserving salts. He and his catfish have been friends since they were both born, and he takes great offense when someone insults his fish (both the ones he’s selling and the one he’s riding).",
"A butcher who enjoys his job a little too much. He’s super creepy, but he hasn’t done anything wrong and he is well respected by those who’ve known him for a while.",
"A huge man wearing sunglasses made of red quartz claims to be the best sculptor in the world. He can prove it too, all his statues are carved from the exact same type of granite and look scarily like the real thing. They always look scared for some reason too. As it turns out, he has a gorgon held hostage in his basement, and he uses her to freeze various animals and people he captures. From raccoons and chickens to cows and people, he’s kidnapping them and petrifying them. Somebody should stop him. He sells his statues for a whole lot of money.",
"Subtle slave trader. The ‘products’ are actually transformed into animals or trinkets. Upon purchase, the trader will give the new owner a scroll or item to transform the trinket into the slave (maybe even back again). A clever way to smuggle slaves through check points and/or through lands that don’t support slavery.",
"A cowpuncher with a heavy accent. She sells common livestock, along with a few exotic things like special built saddles and animal barding. She claims to be from a place called ‘Wyoming’, which everyone knows doesn’t exist. She’s completely sane however.",
"A bearded chef who’s incredibly skinny despite the fact he’s always eating. He’s a very prestigious chef who’s famous for his dragon egg, orange, and tomato omelet. He has a pouch of granola clusters on him that he’s constantly munching on. He jokes about being cursed by a witch when he was younger, but he’s actually correct.",
"You stumble upon a giant clam shell placed near a road by the beach. Knocking on it, a sleepy man opens the lid and rubs his eyes, asking who’s there. He’ll sell you things he finds in and around the ocean before closing the clam and going back to sleep.",
"A painfully average man who sells painfully average things. Any magic items sold to him will lose their properties.",
"A wandering hunter wielding a crossbow who will sell her wares to the party, or the nearest town. She’ll seem to travel in the same path as the party, showing signs of her travels (new scars, new pelts, maybe even a new friend).",
"An older human male approximately 60 years old, hulking frame, thick biceps, bald as a bowling ball and wears a gold chain running from earring to nose-ring, nicknamed ‘Bull’ runs a shop with his wife, a delicate grey-haired human woman of medium height, but thin as a rail and speaking with a raspy voice which tells of her advanced age. In this shop, you can find the finest china service sets and tableware in the province. From platters to plates, from pitchers to spoons, from cups to cutlery, everything you need to put out the best spread is available at Bull’s China Shop.",
"A figure, roughly 5’5”, covered in heavy winter clothing. His(?) voice can be understood, but is muffled by layers of scarves. In actuality, there is nothing underneath the clothing; he’s a modified enchanted armor. They sell a huge variety of armor.",
"A half-elf wizard with a crow on his shoulder. The wizard turns his head rapidly and jerkily to look at anything that moves, but stays silent. If a customer approaches, the crow speaks to them, disgruntled by the change of bodies between him and his familiar. They sells wants and books, typical wizarding gear.",
"A vampire couple. They don’t feed off humans, instead coming out at night to hunt elk, rabbits, and other game so they can feed. They say it tastes like stale water mixed with iron shavings and beef broth, but they also say the bad taste is more than worth it so they stay in good standings with the mortals they live near. They sell timber as well as high quality furniture they make themselves. They’ll sell other things like knives, small whittled figures, and furniture polish, if you ask. The community loves them for being so helpful and not causing any problems.",
"A dwarf with insane eyes, charred hair, and a lack of eyebrows. He has an insane look in his eyes, and is attempting to sell gunpowder and explosives to all who walk by. He keeps sizing up the local buildings with his eyes, especially the wooden ones.",
"A very articulate bald man with glasses. He has an obscene amount of knowledge on the most useless things, like music and technology. He’s a comedian with a small food business on the side. He has a short and sweet wife who makes the delicious food that he sells. They have two long hair cats, who they call their sons. They use strange words and phrases that nobody else understands, like ‘acquiesce’ and ‘get dusted’.",
"Armiton, very calm minded human who sells the crops he grows on his farm. His workers are all homunculi.",
"A stout burly man with a slightly singed brown beard and tanned, scarred complexion; he’s wearing a faded motley cloak and sells a variety of odds and ends. When discussing his goods, he shows off the mundane objects at his stall as if they were exotic wonders. The magical items however, are dismissed as ‘silly pish-posh’ and he hardly acknowledges them.",
"A half-elf, half-dryad who’s mother was a willow. He has long, flowing hair with flowers scattered in it. His dryad nature shows through, as patches of his skin are textured like wood and his hair is a light green, among other things. He is always sitting down, whether it’s crisscross on the floor or on a nearby branch. Around his neck is a small heart made of amber with a tiny blue flower embedded inside. He’ll sell you various traveling provisions and other useful, mundane things, like shovels and lanterns.",
"A short haired woman with a light voice. She plays the ukulele and sings as a street performer. She’ll play any song on request, for a price. She seems to know every song imaginable by heart even when she has no possible way of knowing it, and she never falters in her performance. She NEVER lets her prized ukulele out of sight. She’s a folk hero for making an ogre run away crying after playing a song that it’s mother sang to him as a baby, among other rumors and tales.",
"Eddy and Johny’s cabinet of curios A gnome and half-orc couple who sell small nik-naks some of which give off slight magic. (They sell things off the millions of trinket tables you can find)",
"A young Goblin merchant that is constantly trying to sell the random scraps and knickknacks he finds lying around from the massive burlap sack on his back. Many of his goods tend to be in poor condition or are junk, and a good amount of them were found through more liberal interpretations of the phrase “lying around”. Despite this, he is a hard worker that is just trying to make a living in any way he can manage, and genuinely appreciates anyone who acknowledges that. Those who do usually end up with better deals on more junk, as well as the opportunity to purchase first when he truly finds something of value. Every time someone browses his wares, he proudly proclaims that he’s got the best deals anywhere, despite his tendency to slightly overprice all his goods.",
"A middle-aged Human blacksmith hawks his weapons and armor from the side of a small indoor arena that he owns. The portly man is eager to draw in customers, and is very proud of his works, inviting people in from off the streets to admire their impressive appearances. He is always eager to sell his normal merchandise, but those who wish to purchase his most ornate works must prove that they are capable of handling themselves in combat against a battered set of animated armor, and are challenged to push the construct out of the 15-foot radius arena without getting knocked prone by it. Only if you can do it will he allow a customer to purchase his masterpieces, all of which are beautifully yet practically designed, made from exotic materials that are perfect for enchanting.",
"A tottering old Halfling woman often found heavily bundled up on the corners of busy streets. Despite being nearly blind, she sews repairs to cloaks and clothing in exchange for stories and tales. She is incredibly good-hearted and refers to everyone she meets as “Dearie”. She insists that she doesn’t need money and that the stories she hears make her the wealthiest woman alive, but her customers always tend to leave her some coin anyway. The repairs she makes seem patchwork and haphazard, but are surprisingly durable in addition to making the fabric much more homey and comfortable. All of the locals consider to be a staple of the community, and are very protective of her.",
"An Earth Genasi and his cart of cabbages. Only sells cabbages and is mysteriously in every large town you visit.",
"A small iron golem smith, who exclusively crafts razor sharp longswords (crit range 18-20, cost 200 gp, otherwise same as normal longswords). His hammer is actually an intelligent magic item that gives instructions to him in a way the players can’t perceive. The golem always talks about the hammer, not himself (‘he has this for sale, he would charge you that, etc.’) Upon receiving payment the golem throws the gold in a pot in the forge and later, if the party pays attention, mixes bronze into it after hours to produce gold bars, if it doesn’t know the party is watching.",
"A blue-skinned tiefling who works as a glassblower. He has a lot of beautiful pots, jars, and bottles, all of which are made in stunning colors and dazzling designs. Aside from these, he also has glass weapons and armor. They’re really clunk, but they’re as powerful as they are beautiful. He keeps these a secret from his teenage female apprentice, named Sydney, to keep her focused on the basic craft. If asked about this, he says, ‘She needs to walk before she can run.’",
"A gangling, calm, quiet man who speaks slowly. He drags a cart full of various snails and snail shells. His clothing is adorned with many shells, but otherwise he dresses modestly and is kind-hearted. His name is Escar-Joe.",
"A halfling man who runs the printing business in town. His printing press is unlike any you’ve ever seen, about the size of a carriage and constantly clicking and whirring quietly as it prints like clockwork, and where he got it is a mystery. When asked, he’ll change the subject in an attempt to sell scribing tools, like pens, ink, and paper.",
"An orc who lives in the overgrown skeleton of a giant, sleeping in the skull. He sells game he hunts and ‘clothes’ he makes out of the bones and hides.",
"A human child, around 8-9, with long, brown pigtails. Her name is Bethany, and she claims to be a healer. She’ll cure curses, disease, and other aliments. She’ll fail sometimes, but she’s still learning. She lives in a local monastery with several other priests. They say they found her as a baby and have raised her since, and she shows great promise for her abilities.",
"A short, bald, wizened old man who runs a pet shop. None of the animals are in cages and are all free-roaming. Despite appearing to be conversing with the humans who enter his shop, he is actually talking to his real customers – the animals. When he completes a deal, the pets scratch or bite their new owners and pay him in drops of blood.",
"A shaggy, humanoid shambling mound imbued with sentience by an unknown master. They can’t speak, rather carrying around a chalkboard around to communicate. They’re wearing loose common garb, but you can barely tell. They sell various herbal teas and remedies, and they’ll give you a haircut too if you ask. They have the ashes of their master in a small vial around their neck.",
"A lizardfolk blacksmith who’s obsessed with fire. Her skin is a deep blue, and her neck and frills behind her ears are orange. She’ll cuddle up to her roaring forge at night to make sure she stays toasty.",
"A mute tailor who is a total hermit. The clothes he sells are enchanted to become as heavy as lead if someone tries to steal them. He never leaves his house above his shop, only coming down to silently stock up his wares when nobody is around to see him. Purchases are made by putting the coins into a slot build into his desk, then the enchantment will wear off, allowing you to take your clothes.",
"A well dressed woman with a veil over her face pulls you into an alley before commanding you to buy something. A shelf of potions accompanies her, all unmarked. If you try to ask a question, she pushes you out. If you don’t buy something, she pushes you out. Turning around after she pushes you away reveals that there was never an alley there to begin with.",
"A steampunk dwarf artificer with two crude tentacles crafted onto a small hydrator engine attached to his lower spine. Wears a brown trench coat, bald and grey beard and drinks copious amounts of coffee. Quite friendly and talented with a blunderbuss also runs and operates Loch & Load artificing shop.",
"A short woman who makes tea. Her tea is mostly normal, but if you ask she’ll show you all sorts of exotic plants made into tea bags. Banana leaf tea, cactus sap tea, goodberry tea, spicy honey tea, venus fly trap tea… these are getting weird.",
"A fire genasi who’s obsessed with smoke. He sells cigars, smoked meats, and tinderboxes. He smells like smoke, his eyes and skin are a dusty orange.",
"You open the door to a large shop, and it’s empty. Save for a single table, with a quiche. A singular quiche. There’s a note that says, ‘Pay what you want’ with a smiley face in crude handwriting. You can smell a goblin in here somewhere. Did she make this?",
"A man with a pet rust monster buys metal scraps and sells the chitin his pet drops. Maybe there’s a use for it. The rust monster is extremely well behaved, with little bows around its antenna. It’s kinda cute.",
"A gruff, stereotypical strongman runs a bar. A normal bar.",
"A dark skinned goliath woman who runs a daycare. She sells the arts and crafts that her children make that they don’t take home, and she’ll take care of your kids if you have any. Everyone calls her Mama.",
"A young witch who smells of alcohol. For some reason, she cursed herself to be constantly intoxicated. She only uses fire magic and anything to get her more drunk.",
"A fat man who yells a lot. He sells mead he homebrews himself. Is he deaf? Maybe he’s deaf.",
"This kid claims to have an invisible cow, and he sells the milk. When you try and prove him wrong, a long moo comes from seemingly all around you. I guess he does have an invisible cow. Drinking the milk turns you invisible for a few minutes.",
"This man sells wagons of all shapes and sizes. From wheelbarrows to horse drawn carriages, he makes them all by hand. He’s known for being very precise when he stains the wood, also by hand.",
"A tabaxi with shaggy fur sells livestock, who are all acting strange and annoyed. She swears they aren’t stolen. Stop asking.",
"A royal guard with a scrawny body and weak chin. He’ll give you the latest gossip on the town for a few coins. He’ll tell you regardless, then get annoyed when you don’t pay.",
"An aarakocra chicken who sells healing potions. The potions are contained in eggshells and look like normal eggs, if a bit larger than the usual. The merchant will fluff up and squawk indignantly if a PC wonders whether the merchant laid the eggs. She will scratch in the dirt and wave a feathered arm angrily. ‘NOT my—bawk!—CHILDREN.’ The potions all heal an extra 2 HP, but the shells are fragile.",
"Legitimate Larry. He’s so legitimate that his collection of obviously stole items obviously must have just fallen off the back of a cart.",
"A Halfling Artificer and Tinker, with a broad smile and gregarious nature. He produces intricate, ingenious mechanical devices for adventurers. The shop he operates out of is built-to-halfling-scale, though. To broaden his customer base, he has fitted every shelf, display, and even the front wall of the building with a complex system of rails and slides, allowing him to do business with anyone, and display anything, all at the customer’s eye level.",
"What appears to be an EXTREMELY tall halfling woman, but when she walks around the counter, she is simply wearing the tallest pair of platform shoes you’ve ever seen. All she sells is shoes. Some of the shoes are enchanted, but many are just ‘fashionable’.",
"A tortle that, when it approaches, it appears the shell has been carved to look like tattoos. When he speaks, he has a deep slow tone to his voice (imagine Johnny Cash). He sells books and scrolls and writing equipment. He is never in a rush to make a sale as he enjoys the act of bartering but always ensures he makes a profit. His stock often holds rare or even forbidden books. When asked, he will just shrug and say something about not knowing or forgetting the book was there. He of course houses lots of spell scrolls at different levels and will even sell a few spellbooks from wizards that gave either passed or given up that life.",
"Bobbik and Bimbeck’s Curiosities: Mr. Bobbik is a bespectacled Beholder with a friendly and inquisitive nature. A true oddity in his species and as such shunned entirely from polite underdark society. In his travels, he met Mr. Bimbeck, who was exploring caverns looking for interesting rocks and a lifelong friendship was formed. The two of them sell all manner of strange and unique things. They probably don’t have EXACTLY what you are looking for, but they certainly have something of interest. Example Inventory: A potted plant with a bell on it (So it can’t sneak up on you), a warhammer that you can fill with angry bees, Aardvark poison, Aardvark medicine, a clockwork thing you don’t know what it does that has a bell on it so it can’t sneak up on you.",
"Sister Elma: She claims to be a Nun and sells holy symbols and dubious reliquaries to travelers. Example Inventory: Martyr’s Big Toe on a string, desicrated left testicle of a legendary bard, mostly accurate holy symbols at discount prices, bag of bones from a legendary warrior (or a chicken, depending on perception checks).",
"Bob and Rob Oblah (And Hobble their Goblin assistant): An Ettin with 4 eyes for values! Not the brightest, but with a natural sense for what things are worth and if they are being cheated or short-changed. The two heads can be played off of each other in the process of haggling. Hobble the Goblin mostly just stares daggers at the customer and polishes the counter. Example Inventory: Magic Items, hand made Goblin crafts.",
"A new gnomish invention that automatically dispenses a piece of gum that works as a healing potion if the proper amount of gold is inserted. Roll a d20 when using the machine. On a 20, two pieces of gum come out. On a 1 the machine jams and no gum comes out. Has tamper resistance enchantments that destroy the gum if the machine is broken into.",
"A dwarven barber that uses magical shears. Cuts their client’s hair to be longer, not shorter.",
"A Tabaxi merchant sells beautiful glassware and fine china, things that an adventurer would probably never use. Symbols on his shop in thieves’ cant suggest he may also be a fence, although they are confusing, crossed out and re-written. The Tabaxi, a dark-coated young merchant named Many Hidden Knives, is boisterous and eager to gossip.",
"The shopkeeper is clearly two gnomes with one on the other’s shoulders, but they will never admit it. The two, Foggi Ysbeten and Grogel Grogelhome, take turns being the one on top, but never acknowledge the difference. They sell ‘human-sized’ equipment.",
"The Broad’s Boards: An extremely tall, stunningly attractive blonde woman named Nyss sells shields of different makes and models. Has some magic shields, some bucklers, and some tower shields too big for the average man.",
"A Goliath, considered large even among his own tall people, known only as ‘The Builder.’ He crafts intricate toys, gadgets, and trinkets. Working from inside a wagon pulled by two Clydesdale horses, he hunches over his desk with a lantern and a magnifying glass, working his massive fingers to build tiny, detailed devices. If he meets a child, he always gives them a toy for free. He never accepts gold as payment, only more materials for crafting, or if the need arises, a personal favor. He can be commissioned to build specific devices, but prefers not to unless he knows the person well. He sticks to rural towns and villages and defends himself with a myriad of clockwork like devices that are beyond most people’s understanding.",
"Azaeli, A devilish tradesmen. A man of true evil. Holds some of the best gear around and sells them very low as well, but they come at a cost, Azaeli gives the buyer a quest of true evil intentions. Rather it be spreading a plague, or allowing crime syndicates to florish, a seemingly useless action that has large impact on the nearby areas. Azaeli has a pair of seemingly burning eyes, is often found to be wearing a top hat and very expensive silk clothing. In his backstory Azaeli, was once a normal True neutral, human warlock, until one day Azaeli attempted to banish a powerful demon. It succeeded but as soon as he cast it he was possessed causing a merge of souls. Azaeli became a devilish sellsman who roams the globe causing mayhem.",
"Whilst walking through through the run down boroughs of a large city you spy a strange exchange down one of the numerous labyrinthine alleys. A rather large and motley crow sits upon a busted crate. At the base of the crate an alley cat, accompanied by a scraggly litter of kittens, approaches the crow and drops what looks to be a shiny piece rubbish. You look on as both the cat and the crow seem to converse, the low cawing of the crow meeting the desperate meows of the cat. Eventually some sort of accord seems to be struck, and the crow produces a large half eaten fish, dragging it from the crate and letting it plop down on the dirty ground bellow. Immediately the mother alley cat picks up the fish and darts off, her kittens tumbling along behind her. Those who wish to stay and observe the crow for longer will discover that all manner of strays, ferals and other wild denizens of the alleys approach the crow throughout the day, including one or two beggars and street kids. Each time something shiny is produced, and an item from the box given. Sometimes food, sometimes junk, and at one point even a dagger (given to a street kid) is pulled from the crate. At sundown several more crows gather at the spot in the alley and begin to fuss around the crate. Eventually they all take flight, labouring under a sack clearly laden with goods. They cary the sack high above the roof tops, eventually disappearing from sight, their mysterious trade having officially closed for the day.",
"A series of animals who seem to run every magic shop the party goes’s to. They’re capable of communicating via telepathy, but mostly prefer to make animal noises. Probably the familiars of some old mage.",
"A very short wizened old man with a wispy mustache. He runs a pet shop and seems to always be talking to himself. When someone enters his shop he will grab them by the elbow and begin walking them around to all the cages and kennels and tanks. No matter what they say, he’ll respond with things like ‘Yes, he is a bit tall, isn’t he?’ or ‘Now don’t be rude, he doesn’t smell that bad.’ or ‘Ah yes, I remember. You don’t want a single pet, you want to adopt a whole family.’ Finally he gets to one animal and says ‘Eh? This one looks good to you? Excellent!’ He then picks them up out of the cage, hands them to the person – again, regardless of whatever the person is saying – and then says ‘Now there is just the little matter of payment …’. Which is when the animal bites or claws the person and then gives the store owner a single drop of blood. Because he doesn’t sell pets to people, he sells people to pets."
]

