var challenges = [
"A room of freezing particles that stick to the skin and slow the characters down significantly Add monsters/other challenges to taste.",
"A room strung with a what looks like (initially) a net of thin, ghostly filaments. Turns out to be monowire strung at random intervals (hard to see where until you're right on it) that makes it difficult to cross. Monowire = a thread can slice through anything as easily as if it were passing through air. Be very careful.",
"A locked door that must be broken down to pass. On the other side? An abyss. Breaking the door down might cost your players a character or two.",
"An old man appears in a flash of light and offers to sell things to the characters. Does he have a motive?",
"A perfectly ordinary looking floor, empty room, etc. When the characters go in, the doors close, lock, and the floor starts to tilt. It's on an axis, so movement on it tilts it in one direction or the other, and it's going to take fast reflexes for the characters to keep from slipping into the punjee pit below. Unfortunately, the key that unlocks the door is sitting on a hook on the floor in such a way that it won't fall as long as the players are on the other side of the room, but if the floor tilts the other way, then the key comes loose and falls into the punjee pit.",
"A room filled with countless levers. One unlocks and opens the opposite door. The others have various nasty effects (release sleeping gases, laughing gases, flood the room, drop monster from a pipe in the ceiling [could be a complex mechanism with a whole bunch of caged monsters up there...])",
"A long passage of murky, depthless water. Two boats are tied up at the entrance- one that looks rickety and has a little water in the bottom, and one that is new looking, gilded on the edges and looks really watertight. Turns out the 'new' boat is actually an illusion, and it disappears in a puff of smoke about halfway through. Add water encounters, tentacles, piranhas, kelpies and the like to taste.",
"A powerful wizard creates a cavernous sinkhole beneath the city the players are in.",
"An illusory wall of fire, ice, water, lightning.",
"A room with a doorway 100-200 feet up. Walls are covered in tapestries. A random word has been engraved on the wall. Turns out it's the secret word for one of the tapestries, (treat as a flying carpet) but it has to be removed from the anti-magic clip holding it to the wall before it will respond.",
"A curving downward staircase. Pressure plates on the staircase trigger an automated crossbow/weapon at the bottom, making it seem like someone's down there. Turns out it's just a statue wired to shoot bolts/bullets like that. Door through is beside the statue.",
"A hexagonal room with no obvious way out and an arrow drawn on the floor facing a wall. Secret doors on every wall, each leading to another similar hexagonal room with another random arrow. (You might want to map this out so you don't get lost, even if the players do.) Makes a great maze.",
"A mimic that has taken the form of a door. (Turning the doorknob might cost a character his hand!) Add splintered wood bits around the door to give the characters a 'hint' or just throw them off.",
"A jelly/blob creature partway through a door. (About a foot sticking out.) Turns out that it's just the 'tip of the iceberg' as it were, a little piece that had to go somewhere, because the 1000 x 1000 ft room on the other side is already packed completely full with this thing's enormous bulk.",
"A room with yellow lines that border the walls and break for spaces at even intervals 2-3 times. Where the lines break, there's a pressure sensitive trap that spins the entire section of hallway to the left and ejects the character down into a pit of some kind or another (add punjees, zombies, monsters, etc. to receive them when they hit if appropriate.",
"A room with a ragged, bottomless-looking hole in the center. Closer inspection reveals massive toothmarks on the edge of the hole, and a deep breathing sound coming from far down in the bottom. Great to scare your characters. Add giant man-eating wyrm for a little more spice.",
"A circular room with a fountain in the center of it. Looks like the floor is covered with about a foot of water and gold coins are spread across the bottom. Turns out to be an illusion- the water is actually more like ten feet deep with something scary and hungry at the bottom (like tentacles and a big toothy mouth or another ooze or a horde of water-bloated zombies)",
"A door with multiple knobs. Wrong knobs trigger traps.",
"A long maze of gooey yellow sponge passages just large enough for one person to crawl through. Starts to shrink and harden if players take too long to get through",
"A room full of bubbles that show the players' nightmares, bad memories and fears to them",
"A horde of ghost pirates come through the walls and attack the players",
"A statue of a big buff man holding his bicep, hand halfway between open and a fist, and grinning. (Arm wrestle to get through)",
"An elaborate fake-out trap, like a room filled with obvious pressure plates (maybe marked, like a rune-word puzzle that has to be stepped on) or big bold lines, that sort of thing. Either the trap was disabled, or it's there to mess with people. Add incentives/scariness by putting dangerous-looking arcing electrical things at the end by the door, ominous nozzles, broken tiles that drop into magma... that sort of thing.",
"A room with an unusual light source (like a torch in a tube in the floor or something) with a lot of shadows. One or more of those shadows are living, and hungry.",
"A room with a man hanging at the far end, his wrists and ankles in shackles, chained to the wall and over the door. Walking closer to him tightens the chains (like a rack). He screams in pain and begs for mercy every time they tighten. Could be an illusion- you decide how much to mess with your characters' sense of right and wrong.",
"A room full of statues (8) holding corked vials. Setting off hidden pressure plates causes the statues to drop them, releasing nerve gas. The door handle is a knife blade.",
"Anything from Indiana Jones.",
"A circular raised platform. Light comes down upon in. Only the penitent man will pass.",
"Two chains retracted into the walls 30ft apart. Pull the two together (feat of strength) to open the door. Find a way to connect them to keep it open. Door falls quickly.",
"Eight levers in sockets that must all be turned at once",
"A long gravel corridor with a heavy statue of a laughing guy in football gear holding a rope at one end and a car trunk at the other. Drag the man through the gravel to the car trunk and connect them to pass.",
"A pool of bubbling sewage with a pipe under it leading to a toilet bowl that must be climbed up through.",
"A wall of acoustic force that blasts the ears and takes a force of will to get through. Makes characters temporarily deaf.",
"8 holes in the wall, each with a steel rod inside. One opens the door, the other seven shock the character. 1d4/turn. Almost impossible to get free- other characters will usually have to pry the shocked one loose.",
"A massive, tsumani-style tidal wave immediately rises up to crush the characters. Run away in fear or face it- Turns out to be illusion.",
"(Great for the next room) A real tsunami-style tidal wave rises up to crush the characters.",
"A thick wall of ice blocking passage that shoots blades out ten inches when touched. (1d6)",
"A two-hundred foot steel wall blocks the way. Handholds are razorblades of sharpness.",
"A room with gravity pulling four ways (up, down, left, right.) each 'wall' is a five-foot deep pit of molten gold",
"Two electrified handles on opposite sides of a thirty-foot chamber. Like the chains, except the characters need to form a conductive link to power the door and get it to open.",
"A room with a mud floor. He who swims to the bottom and finds the tunnel to the next room escapes",
"A room filled with sharpened bamboo poles sticking out of the room at evenly spaced intervals, floor to ceiling. There's not really enough room to just slip by, and if one of the poles is touched, it comes alive, dealing 1d4 hp damage to the character.",
"The players walk into a large room with a large stone ring sticking out of one wall. An equal number of ghostly figures (to characters) step through the wall, one carrying the ball. They're all pretty strong, and it should really be a challenge for the players to beat them, if they do at all. You see, the winners are hauled away and sacrificed, and like Aztec ball players, the ghosts think this honorable death desirable.",
"A table with two chairs and a statue of a smiling, one-armed hick that comes alive and starts pouring drinks. Outdrink the hick.",
"A circular man-sized opening/door sweeping down into the floor. It's filled with something sticky and viscous like honey or molasses. Beyond the floor (where it can't be seen except by diving in,) it narrows steadily down to a fist-sized opening with a lever at maximum arm's reach that opens a secret door (leading to the next room) but it's back beyond the mouth of the pipe.",
"A room full of bouncing basketballs that the players have trouble wading through. In the middle somewhere, balls start shooting in toward the characters at random, hitting them in 'stun' type locations, like the face and groin.",
"A large, olympic-sized pool with a rectangular shape and a rectangular bottom about 12 feet down covered in rusty-looking armor and items, etc. Turns out there's a jelly blob thing down there that's translucent with the gear inside it completely covering the floor up to about two feet from the bottom. It's hungry too, so the characters better watch out!",
"A room crammed full of rotten barrels filled with decaying dynamite. No room to get around- over is the only way.",
"The players open a flimsy-looking door and find themselves face to face with a massive, arena-style room packed with an audience of 10-20 thousand hungry zombies.",
"The players enter an empty room with a slowly strobing light (spell-based or technology, whatever works in your campaign.) what they don't see is the monster/ninja/assassin stuck to the ceiling above them.",
"A room filled with water and fish and contained within the room by magic or technology. Whatever it is, you can walk through it, and you're going to have to if you want to see what's on the other side. The water is dark and a little cloudy, but there's just some harmless-looking fish visible, so it cant be that bad. (Until you get about half way in and there's a shark or a larger room with a bigger shark, or something like that.)",
"A long hallway filled with misters. In the center is a pedestal that does nothing, but looks like it does something. The trick is in the misters- they're dispensing liquid LSD, and it starts to take effect before too long. Longer exposure = more vivid hallucinations.",
"A large field of flowers and fruit and peace. Fruit has a sleep toxin. It's all an illusion, and the 'flush' lever can be found with a little searching. Turns out all the 'food' was actually sewage.",
"A zodiac spreads across the floor. Close observation shows that it has a thirteenth symbol, closer observation reveals it's an unrelated symbol, (get creative- make it the ford symbol or something) even closer inspection reveals that it's a pressure plate.",
"A single mirror at the end of the room. Looking into it reveals a face after a moment that jumps out of the mirror and screams. He who overcomes his fear and screams back gets grabbed and pulled through to the other side.",
"A fifty-foot chasm full of razor-sharp blades stands between the characters and their goal or the next door.",
"Room with a mud floor. Door at the opposite end. This floor is sticky, like quicksand, and about twelve feet deep.",
"Room full of about thirty gorillas that all look up when the door is opened. Watch your players freak out. Gorillas are actually really gentle. They don't care what the players do, as long as they don't hurt any of them, and if they do, the gorillas just run away or attempt to defend themselves",
"A pedestal with a cute little rabbit sculpture on it in the center of a room. Does nothing, but if they ever all look away from it at once (like if they're leaving) it roars and shakes the room.",
"A room with a hyper-aging field in it (turns 1 minute into one year). Inside the field, the room has given way to a lush forest with flowers that bloom, turn to fruit and drop all in the space of a minute. There's a door on the other side.",
"A room with eight pools of water and eight flush levers. Pressure plates in the floor allow levers to be used. Seven of them flush the characters into a pit full of water and zombies. One opens the door",
"A room with an oddly golden haze hanging in it. In the center of the room is a squalling baby on a dias. If the players scoop it up, it smiles and laughs, and then turns into a wad of angry mutant flesh with talons that tries to latch onto faces and whatnot. At that moment, the rest of the room turns into something living, like the inside of a stomach.",
"A room filled with an odd network of pipes that is so thick it's difficult to move through. Closer inspection reveals some of the pipes are made out of substances other than metal (like skin or wood) and the pipes react to being touched. If threatened in any way, or if the room thinks it can take whoever's in it, it will burst pipes near that person, spraying them with steam, ground glass, acid, or any number of other things the DM can come up with. Dead characters/abandoned objects left in the room are absorbed to make new pipes.",
"A strobe-lit hall of warped mirrors. Every time the light flashes, something grotesque appears. Add dopplegangers to amp up the fun if you wish.",
"A door with a large, unusual keyhole. The room is filled with keys and a handful of random objects. All the keys but the proper one are coated in poison (sleep poison, withering, etc. it's up to you) and the proper one turns out to be something really random like a wine bottle (breakable... muhahaha) or a dildo (who's gonna want to touch that?)",
"A door that's totally barricaded over. If the characters tear down the barricades, they find whatever it is on the other side that the door was barricaded against...",
"Set up a junction. In one room is a trap/challenge and a locked, unbreakable door but no key. In the other is the key, but it's set on a pedestal in the middle of a cluster of ominous-looking statues of armed warriors who are all staring at it. Whether or not the statues come to life when the key is taken is up to you.",
"A simple looking room with a locked door and a key on a pedestal. When the characters pick up the key and try to insert it into the lock, it crumbles to dust the instant it touches the keyhole. The real key is still in the room, but it's hidden somewhere, either under the pedestal or under a brick in the floor... the options are endless.",
"The characters enter a room filled with a hazy blue/red/green mist. It could just be mist, or an illusion, or it could be vampiric, leaching blood (Hit Points) stats, even artifact/item powers. Maybe it makes all gunpowder it touches non-functional- there's a lot of room for creativity here.",
"Create a trap or situation using something from a different time/dimension. For fantasy settings, throw a couple claymore tripmines at the characters. For futuristic settings, throw a steam-powered monstrosity at them, or something involving magic (like a fireball-hurling mage)",
"A device (or a room housing a device) that subsonically triggers the pleasure centers of the brain to all who are exposed to it. Maybe triggered by a pressure plate in the center of the room. Imagine- the characters might get caught permanently in the center of the room, unwilling (or unable) to move simply because they're experiencing something akin to an endless, massive orgasm. Sure, they'll die of starvation eventually, or maybe you could have some kind of creature come along and nibble on them first...",
"A really creepy room with really creepy things the players can explore, play with, or even take with them. Consider your living room, and then imagine if every piece of furniture were made from bone and poorly stretched human hide. That kind of thing.",
"While in a town buying supplies, looking for work, or relaxing, a wizard in that same town unwittingly opens a singularity bubble in his tower, making the town the focal point of a baby black hole that the whole world is slowly imploding into. (Great start for a new quest.)",
"The players find themselves face to face with a giant steel double door covered in a series of dark, symmetrically-aligned holes. Opening the door triggers the forty-at-once wheeled arrow battery on the other side to fire it's payload through the door.",
"A room full of corpses in various states of decay. They can either lay in wait for the moment to rise and attack, or maybe they really are just corpses. Or you could get creative and have them rise up magically, but be nothing more than a puppeteer's toys.",
"The characters have to get into a building/dungeon/installation. Make the only entrance be through the hopper of an automated meat processing unit. Alarm sounds if they break it. Encourage them to get creative in their attempts to get in without being turned into hamburger.",
"...Or, maybe the only way to get in to the facility is to 'become' one of it's denizens/defenders. This could be as simple as acquiring a uniform, or as sacrificial as being assimilated (cybernetically) or being transformed into something... otherworldly.",
"A long, windy passage with grates spaced at even intervals along the floor. A closer look will reveal unnaturally smooth walls, the surface almost glassy. Before they get in too far, the door they came through slams shut, opening a wide pipe that starts filling the room with some liquid as all the floor grates seal. The liquid could be simple water, or, if you're feeling particularly nasty, make it something more dangerous, like sulfuric acid. You can also make the door at the other end of the tunnel a puzzle to open too, for added fun and panicking.",
"A room with dirt/stone walls, like the inside of a cave. Looks totally ordinary, but there could be any number of things hidden behind the walls (large animals/monsters, mining lasers, mechanisms that push the walls together to crush what's in the room, etc.)",
"Create a big central door with 3-6 keyholes in it. Every key must be inserted in it to get it open. Now hide each of the keys in a different part of the dungeon/facility, either in some really obvious (and therefore irritating) place, like on top of a fireplace mantle, or at the end of some daunting challenge. Whether there's anything good behind this big central door is up to you. There might just be nerve gas behind it or something equally dangerous. It's up to you.",
"The players find an important door they have to go through, but a massive pillar has fallen directly into it, jamming it and blocking the way.",
"A room with another smaller room inside of it. Blood and gore has seeped out through the door of the smaller room and soaked the floor. If the players go inside, they find a sickeningly macabre scene of dismembered corpses- then the door locks, and the walls (or the ceiling) sprout knives and start to move.",
"The players find a music box in some random part of the dungeon/facility. It plays a simple tune. Later (how much later is up to you) they come across an impassable door filled with holes about the size of a dagger blade. When a dagger is inserted into a hole, it makes a specific and unique tone. The door is a sound-based lock- play the song from the music box to open the door.",
"An impassable door in a room with a large monolith in it. On the face of the monolyth are glowing runes that are each a different color and shine their light across the face of the door. What opens the door is up to you- maybe the characters have to cover up a key rune word to open the door, or maybe they have to cover all the runes but those that make the word, or maybe they need to create a certain color (or series of colors, as with multiple locks) in order to open the door.",
"A living door with a face greets the characters as they come into the room. He doesn't want to let them through, but if they persist, then he says he requires a living sacrifice. If they try to get through anyway, he chooses one of them at random and traps them in a constricting magic jar. He can be persuaded to let his target go, but only at a steeper price. If they pay the price, he lets them through.",
"A normal-looking room with some decent furniture in it (a couch, a coffee table, several easy chairs, a bookcase, a clock, etc.) There's also a water fountain and a bowl of fruit on the table. When they go inside, the door locks behind them and becomes impassable. (As the other door already is.) How to get out? The clock on the wall is open and magical- turning it advances time (or reverses it) in the room, but only on the objects in the room (and the doors). They can reverse it to reopen the first door, or they can push it forward until the doors rot away and fall off the hinges. (Or open automatically- something like that)",
"The players enter a gallery of odd looking paintings, and both doors close and lock. If anyone pauses to look at the paintings, they feel themselves drawn into them like they could just step forward and be in that realm. If they try, they get sucked into the painting and must deal with the denizens thereof (fight a knight, fight a creature made of clocks, be subject to the world of 'The Scream'.) The key is in one of these painting worlds.",
"The players walk into a room just in time to see a man with a jackal's head (Anubis) confront a man who looks like another adventurer. He says 'Only he whose heart is so pure that it weighs less than a feather may pass to the other side. Show me your chest so that I might judge.' The adventurer does so, and Anubis reaches out and removes his heart, then weighs it, and finding it weighs more than a feather, he hucks the heart into the mouth of a nearby crocodile and the adventurer dies on the spot. Anubis then looks at the characters and repeats his first line. In truth, the whole thing is illusion, but the shock of having one's heart devoured as such is enough to kill a character.",
"The characters walk into a room with a door at the other end. The room is empty, and the door is locked, but whoever tries to open the door triggers a trap that opens the floor beneath him/her and he/she falls into a shallow pit for minimal damage (mostly just surprised.) If they find a way to get past the door, they find that it's just for show- it's just stone on the other side. The real door out is a trap door at the bottom of the pit.",
"The characters enter a room with a locked door and a dome of glass overhead through which they can see sky. Put the key somewhere really obvious to unnerve them- like on a hook next to the door. The real trick is if they break the glass on the dome, the sky illusion shatters too, and an underground lake (previously held back by the dome) pours into the room/dungeon/facility through the hole. You can also make the door more complex to really put an edge on things and give the characters additional reason to break the dome.",
"The characters enter another gallery full of paintings. The door out is locked and unpassable, but is interesting in that it seems to have a strange mesh quality to it. How do they get out? There is a letter written on the back of each of the paintings, and when they're combined (and de-jumbled) and the password is spoken aloud, the door opens. You can make it something really cheesy like 'open sesame' or even go for full words on the backs of the paintings and require them to put together a sentence that could even be a hint to another puzzle further on (lots of people learn by doing).",
"A pit trap opens beneath a character and then seals overhead as it triggers locks on all doors in or out of the room. Inside the trap and in the room are a series of switches that do things like fill the opposite space (pit trap or room above it) with water or release sleeping gas or fill the room with arcing lightning- those sort of fun things that can be combined to create a really hairy situation (like a flood of gasoline and later a fireball) Luckily the switches are on/off toggles, even though the machinery is old and might take a moment or two to respond. There's also one switch that opens the doors, but both have to be turned to 'on' to work.",
"Create a fun trap that will catch stragglers- a good example would be an L-shaped hallway with a door at both ends and the floor covered with about three inches of gasoline. As soon as the door in the boot of the L is opened, the opposite door sinks into the ground five feet, revealing a large flame thrower that toasts anything in the long part of the hallway and lights the gasoline on fire. Whoever opened the door and anyone else with him/her better beat feet fast, and hope everyone else that caught the brunt of the fire made it out okay.",
"The characters walk into a room that's filled with a misty red haze and there's a noticeably odd iron tang to the air. You can put things hiding in the mist, but the presence of the mist alone should be enough to mess with the characters. Later (like a room or two down the line, they walk into a room, the doors close (they don't have to lock) and with a crackle and hum of electricity, a hyper sensitive electromagnet that covers the whole ceiling comes alive. This will of course grab weapons, armor, anything magnetic- including items not properly cleaned after the red mist room. Next, the room begins to fill with water (or something else- it depends how nasty you want to be.) There's a drain on the other side of either door though, so if they can get free before they drown, there's still hope of escape.",
"The characters walk into a hallway filled with rushing air enchanted to extinguish any light sources, so they have to stumble around in the dark. This leads to a large room that is likewise enchanted, but unwittingly stepping on a pressure plate in this room disables the enchantment and triggers a cache of 50 coins each enchanted with a very bright continual light spell to drop from the ceiling. The combined light of player's light sources and the coins is blinding- especially combined with the fact that the entire room has been covered in mirrors... Add monsters that leap out and jump on blinded players as you see fit.",
"A room with a number of sealed glass insets and a locked, impassable door with the note 'In case of fire, break glass' pinned to it. Most of the glass boxes are filled with Halon gas, which blasts out and chokes the characters exposed to it (or you could put in something worse) and one of the insets opens the door (or maybe just floods the room, if the door turns out to be a dud in your scheme of things.)",
"The characters enter a room and suddenly steel walls fall from the ceiling and separate them, creating individual hallways from which there appears to be no escape. The walls should be soundproof too. As soon as the character looks away or gets desperate, someone appears who he/she loves or really trusts, and this someone tries to keep them there by any means necessary. Add rising water or heat or other deadly panic-inducers for extra fun. How to get out? Work up the nerve to attack and kill the illusory person.",
"A locked, impassable door that, when touched, beeps and says 'Password please.' nearby is a large, onyx pyramid on a pedestal that, when touched, steals the spirit of the person who touched it and randomly injects the spirit of one of it's other captives into the vacant body. One of these souls knows the password, and a number of them are violent, insane, or previous adventurers with their own agendas who wont be too keen on giving up the body they're in.",
"A large, unpassable door that wont budge. On either side of the door, two to a side, are four long, flexible copper wires that are rolled up. Also in the room are a number of fruit trees, including oranges and grapes, and a number of clay pots. The trick to get through is to make four primitive batteries to power the door by filling pots with acidic fruit juice and putting the copper wires in them.",
"Another room where the door closes behind the characters and becomes impassable. There are no other visible doors, and the room is starting to flood. The trick to get out? A concealed trap door on the ceiling that can only be reached by swimming as the room fills...",
"A wise-looking (or famous) sage/messiah waits for the characters in a room with no visible doors. He/she greets them, speaks with them, and if asked where to go or how to proceed, the sage tells them that only in death can one see and go through the door which lies in this room. It is locked to all else. Attempts to find the door should fail. The sage will continue to 'help' them accept that they have to die, and will gladly kill them if they wish, (absorbing their spirits as payment and keeping them from passing to the next world, so they are just dead, gone forever.) The only way through is to confront the sage, who, after the players start getting aggressive, turns into some kind of hideous monster that turns out to be a real test of the characters' strengths. Killing the monster reveals the door and unlocks it."
    ]

var physical_trigger = [
"Balance - if “x” side is too heavy / if either side is too heavy / if balanced",
"Button - push / push “x” times / multi button sequence / if released",
"Clock Hands - set time, all hands together, etc",
"Domino Trigger - trap 1 sets of trap 2 which sets of trap 3 etc, etc…",
"Door / Lid - opened / closed / door knob turned / latch turned",
"Float - float attached to a trigger wire; change in water level or wave can trigger trap",
"Fragile Containers - if broken, trigger trap / set up to be broken by other traps / precariously balanced",
"Guard - a guard watches and uses a button, lever, or pull cord to actiavte the trap",
"Keys & Pedals (musical instrument) - piano, pipe organ / specific key / key combination / out of sequence",
"Ladder Rung - ladder rung is a lever that triggers trap",
"Lever - pull / throw / position / sequence / multi lever position / removing weight holding lever in position",
"Lever (Disguised) - arm of statue / book on a shelf / hook on a wall / vase",
"Lock - opened / locked / fail to pick / incorrect key / incorrect key turn / incorrect key turn sequence",
"Lock (Fake) - if unlocked or picked, then trigger",
"Lock (Multiple) - as lock + if unlocked out of sequence / unlocked (at same time, not at same time)",
"Magic Trigger - Magical Trap Triggers*",
"Plug - if removed, triggers trap",
"Pressure Plate (add pressure) - any pressure above “x” amount",
"Pressure Plate (remove pressure) + bait object",
"Pressure Plate - (set pressure) - too much or too little weight triggers trap + bait object",
"Pull Cord / Chain - pull / multi-cord sequence / attached to bait object",
"Puzzle - set move / incorrect move in sequence",
"Temperature Gauge",
"Tilt Trigger",
"Timer",
"Tripwire - (add tension) - triggers when pulled or pushed",
"Tripwire (remove tension) - triggers when cut or broken",
"Turn Crank",
"Turn Dial",
"Turn Dial (disguised) - base of statue or sculpture, head of statue, torch sconce, etc",
"Trip wire",
"Pressure plate",
"Opening a door",
"Lifting the lid on a chest",
"Grabbing a certain rung of a ladder",
"Removing an object from it’s resting place",
"Touching anything in the room, including the floor",
"Breaking the beam of a light source",
"Disturbing a source of water in the room",
"Pulling on a suspicious looking rope hanging from the ceiling"
]

var physical_reaction = [
"Gears can be heard grinding from inside the walls",
"A low boom is heard that echoes out through the dungeon",
"A high pitched whirring can be heard",
"Various ticking sounds are heard",
"A quick release of steam followed by a bang",
"A low rumbling that shakes the room for a moment",
"A single click",
"The sound of chains sliding across stone",
"A thumping sound that starts slow and begins picking up speed",
"Nothing. Silence"
]

var physical_trap = [
"The floor opens downward into a 40 foot pit",
"From unseen slits in the wall, poisoned needles fly out",
"A wall opens revealing a golem to ambush the party",
"A large log swings down from the ceiling",
"The parts of the dungeon begin collapsing, blocking off areas",
"Vents on the ceiling begin emptying noxious fumes into the room",
"A large blade swings horizontally across the room attempting to decapitate",
"The room begins filling with water after the doors slam shut",
"The walls slowly begin closing inwards",
"A large rolling boulder drops from the ceiling towards the party",
"Alarm - bells, gong, musical instruments, mechanical sign, signal fire, signal flare",
"Ambush - terrain designed to hide opponents / terrain that would give opponents a tactical advantage / holes that small opponents might crawl out of or drop out of",
"Auto Locker - containers, doors, gate, portcullis, windows, shutters, etc",
"Auto Opener / Closer - containers, doors, gate, portcullis, shutters, sliding walls, windows, etc",
"Avalanche - rocks stacked at the top of an incline, held in place by a pin. Rocks roll down hill",
"Bee’s Nest - strategically placed bee’s nest; swarm & attack if disturbed",
"Bee's Nest Deadfall - trap causes bee's nest to fall onto or next to victim",
"Bee’s Nest Kicker - trap impacts or shakes a bee’s nest causing them to swarm & attack",
"Breakaway Flooring - floor, bridge, ledge, platform, walkway, collapsing ground",
"Breakaway Handholds - surprise those annoying thieves that climb your walls",
"Breakaway Ladder - ladder section falls away",
"Caltrops - caltrops covering floor",
"Catapulting Floor - large counter weight drops, hits seesaw under floor, launches floor plate & anything standing on it into the air + spikes in impact or landing area + pit or crevasse in landing area",
"Chemical Sprayer (type) - sprays chemical in gas, liquid spray, goo, or steam form + Chemical*",
"Clamp Trap - bear trap, rat trap / bladed, blunt, spiked",
"Clamp Trap (restraint) - wrist trap, ankle trap",
"Close Line - thin wire at roughly neck height + tiny barbs + fishhooks + poison",
"Collapse Structure - destroys critical support beams causing structure to collapse; room / passage way / entire dungeon",
"Crossbow Trap - trap trigger pulls trigger on crossbow",
"Crushing Ceiling, Walls, etc",
"Deadfall Trap - rock, ceiling slab, heavy object, spear / bee’s nest / clay pot filled with chemical*",
"Deadfall Trap (liquid) - Triggering the trap causes some type of liquid to dump or spill onto victim. (acid, flammable oil, hot pepper juice, ink, insect attack pheromones, monster attractant)",
"Deadly Ramp - slide + blades, circular saws, grater blades, sliding weight, spikes + dump into hazard, high fall, trap, or wall of spikes",
"Deadly Stairs - changes to slide, retracts into wall, section pivots to flip upside down, + dump into hazard, high fall, or trap",
"Deadly Stair Step - blade hits ankle, slippery step, step pivots to trip victim (down stairs / over edge)",
"Door to Nowhere - door opens to the outside of a tall building, cliff, or pit + door sticks, difficult to open",
"Drop down Cage",
"Fire Starter - starts fire that spreads through structure + burning causes collapse, containers of flammable material within structure, structure is flammable",
"Firing Port - arrow slit, gun port, murder hole; + closable panel; allow guards to attack intruder",
"Flood Gate - starts filling dungeon with water",
"Flour Bomb - bags of flour drop from ceiling & bust open creating a cloud of flour. Any open flame sets off flour bomb.",
"Foot Spike - breakaway floor panel, space with upward pointing spikes + barbed spike",
"Foot Trap - breakaway floor panel, space with 45 degree angle downward facing spikes or nails",
"Fragile Containers - if broken release - bees, acid, explosive, flammable, potions, toxic, venomous animals",
"Frozen Support - treasure Item frozen in a column of ice. the column holds up the ceiling. If attempt to break or melt the column without first finding a way to support the ceiling, the ceiling collapses.",
"Fungus - mushroom or other fungus release toxic or drug spores if disturbed",
"Gas - drug or toxic; lighter than air at top of stairs; heavier than at at bottom of stair or pit",
"Gas (Non-Toxic) - displaces oxygen; heavier than air in pit, lighter than air at top of stairs",
"Grinder - moving blades, gears, parts, etc blocking a hole, door, or passageway",
"Hourglass - doors close, room slowly fills with “x” substance. Acid, sand, tar, water, etc",
"Lock Pick Cutter - add difficulty to pick + if fail cuts lock pick",
"Magnifying Glass - large magnifying glass, exposed to sunlight. if victim moves into focal point, take burn damage",
"Nails - set in floor, set in climbing surfaces, embedded in rope",
"Net - drop down / on floor pulls victim up / shot like a net gun",
"Noisy Floor - floor makes loud noise when stepped upon. creaky, tacky, covered in crunchy objects, etc. Alerts nearby people & creatures",
"Pendulum - axes, blades, hammers, spiked weight",
"Pit - opened / covered / covered self closing",
"Pit (options) - deep / very deep / insanely deep / drops into cage / filled with or starts filling with (acid, boiling oil, boiling water, burning oil, flammable oil, heavier than air gas, lava, liquid metal, poison, poison gas, quicksand, spikes, tar, water) / flowing river / greased walls / lava / monster in pit / nails in walls / pit wider than mouth / spell trap*",
"Pivot Drop - bridge, floor, stairs, walkway, etc suddenly folds down causing victim to fall",
"Poison Coating - poison or drug coating objects, containers, or door handles",
"Precariously Balanced Stack - alarm + damage from falling objects + avalanche if giant stack",
"Pull Apart - shoots barbed arrows or harpoons attached to cables from several direction, then starts retracting the cables",
"Pushing Walls - walls push victim off walkway or ledge; push victim into another trap",
"Psychological (fake trap) - device looks like a trap / bodies with similar injuries along a hallway, in front of a door, or around treasure",
"Psychological (signs) - “warning Traps”, “no Traps here”, “death awaits those who can’t solve the riddle”",
"Quicksand / Mud - victim sinks in, gets stuck, possibly suffocates",
"Retracting Surface - walkway, stairs, ladder; boards, slabs, logs, handholds, etc retract into wall",
"Rolling Boulder - ice, metal, stone, etc",
"Rolling Log Bridge - cylinder or log spanning a gap, rolls when victim tries to walk on it",
"Rolling Logs - logs stacked at the top of an incline, held in place by a pin. Logs roll down hill",
"Rolling Spiked log - spiked log, 2 ends set in ramps in the wall. If ramp ends, log builds enough speed to get launched into the air",
"Sabotaged Ropes - climbing, swinging, rope bridge / drop away, embedded needles + poison, greased",
"Slick Surface - algae, grease, oil, or ice + inclined surface, ladder, ramp, stairs, edge of pit, or edge of cliff + (broken glass, caltrops, spikes, another trap, hazardous substance, hazardous terrain, rooted monster) in fall area",
"Snare - loop of rope, grabs victim by foot & pulls – into air, into pit, over cliff, into water, into other traps, etc. +pulls foot into narrow hole",
"Spinning - axes, bar, blades, drum (bladed), drum (spiked), chains, hammers, hooks, etc",
"Stairs to ramp",
"Swing (weapon) - spring + lever arm + weapon; axe, bar, barbed spike, blade, hammer, hook, spike, spike plate, etc",
"Swinging Log - attached to ceiling by rope. Swing end first, broadside, or hanging down + spikes",
"Thrower - arrows, blades, bladed disk, darts, harpoon, javelin, needles, shuriken, spears, spikes + barbed + enchantment + poison",
"Thrusting - blades, harpoon, lances, needles, spears, spikes + barbed + enchantment + poison",
"Trap Door - ceiling + dead fall trap / floor + pit trap",
"Trip Wire - wire set at ankle height, meant to trip victim + tiny barbs + fishhooks + poison + (broken glass, caltrops, spikes, another trap, hazardous substance, hazardous terrain, rooted monster) in fall area",
"acid",
"acid (gas)",
"acid (sticky)",
"blinding powder",
"boiling oil",
"boiling water",
"flame",
"flame (sticky)",
"flammable liquid",
"flammable gas",
"fungal spores",
"glue",
"high pressure water",
"holy water",
"hot pepper juice",
"ink",
"insect attack pheromones",
"itching powder",
"liquid metal",
"monster attractant",
"oil slick",
"paint",
"pepper spray",
"poison (gas)",
"poison (spray)",
"sewage",
"slime",
"smoke",
"sneezing powder",
"steam",
"stink spray",
"stink spray (sticky)"
]

var arcane_trigger = [
    "An arcane rune on the floor",
    "Arcane markings around a door frame",
    "A pillar that has a low hum to it",
    "A jeweled eye that scans the room",
    "Stone statue that has glowing red eyes",
    "A mysterious green fog that rolls around the base of the room",
    "A very dimly lit candle that could be extinguished with the faintest breath",
    "A phrase scrawled on the wall that activates when said out loud",
    "Failing to cast any spell on a dull crystal floating in the center of the room",
    "Lighting a rather inviting looking torch in the center of the room",
    "Proximity to an object",
    "Entering a room",
    "Damaging an object",
    "An invisible arcane rune"
]

var arcane_reaction = [
"Stone can be heard grinding from inside the walls",
"A low boom is heard that echoes out through the dungeon",
"A high pitched whirring can be heard",
"A low rumbling that shakes the room for a moment",
"A single electical sparking sound",
"Nothing. Silence",
"A low hum is heard",
"A very unnatural light begins glowing brightly from an unknown source",
"Any runes in the room begin glowing a bright red",
"The room suddenly drops drastically in temperature",
"The room gets uncomfortably hot",
"A soft hiss is heard",
"A fizzling sound is heard",
"A high pitched hum rings out",
"A crackling of energy is heard through the room",
"Silence"
]

var arcane_trap = [
"Sleep is cast on the room",
"Victim must resist being petrified",
"A fireball explodes throughout the room",
"All surfaces of the room begin to become too hot to touch (Effectively heat metal)",
"Fumes begin materializing as if stinking cloud was cast",
"A wall of lightning races towards the victim and any others in its way",
"All people in the room have blindness cast on them",
"The victim is sent to the astral plane for one minute",
"Everything in the room begins to levitate, no save",
"The spell Confusion is cast on everyone",
"A glyph of warding containing a single spell level 3",
"A glyph of warding containing a single spell level 4",
"A glyph of warding containing a single spell level 5",
"The room appears to extend on forever and no amount of travel will reach the other side",
"Gravity reverses in the room, the ceiling may be more dangerous than it first appeared",
"A golem animates from a natural resource nearby",
"An illusion is cast altering the perception of the room",
"A mind effecting illusion is cast causing Frightened/Nausea/Blind",
"Lightning bolt",
"Fireballl",
"A wild magic triggers",
"Heat metal is cast on a nearby metal object",
"Catapult spell cast on a nearby rock or stone",
"1 Large, 2 medium, or 4 small objects animate and become hostile",
"Breaking spell is cast, a nearby mundane object gains the broken status",
"Grease spell is cast on the floor in a wide area",
"Tasha's Hideous Laughter is cast in an area",
"Darkness is cast in an area",
"Alarm is cast in an area",
"A magical barrier forms blocking the way",
"INT save or everyone now speaks a different language that none of the other players understand",
"Thunderwave is cast damaging and knocking back characters from an origin",
"Slow is cast on character, halving their movement speed for 10 minutes",
"Scorching Ray is cast targeting any number of characters",
"Blindness/Deafness is cast in an area",
"Levitate is cast targeting a random number of characters",
"Sleet Storm is cast in an area",
"Stinking Cloud is cast in an area",
"Tidal Wave is cast in an area",
"A character falls through a wall or floor into a seperate section of the dungeon",
"Otiluke's Resilient Sphere is cast on one character",
"Wall of Fire is cast",
"Polymorph is cast on a random number of characters",
"Conjure Elemental is cast 1d3 times",
"Geas is cast on a character",
"Modify Memory is cast on a character to confuse them about the location or nature of the room",
"Eyebite spell is maintained for a long duration",
"Flesh to Stone spell is cast on a player",
]

var trap_reset =[
    "Trap was never reset. Nothing dangerous happens",
    "The trap does multiple things, roll twice on the effect table",
    "Enemies in the room knowingly trigger the trap and then run from it",
    "Enemies can be overheard talking about how useless the trap is",
    "An enemy has a list of traps and how to avoid them",
    "There is a dummy trigger, drawing attention away from the real trigger",
    "Illusion magic is used to disguise all of the triggers",
    "Enemies are foolish enough to be lured into their own traps",
    "The trap fails, but not before scaring the pants off the party",
    "Delay of ten seconds. Count out loud"
]








