var worldFeature = [
    "The party sees a giant stone monument of old dwarvish origins, huge boulders are set up to create a humanoid figure. Its species is uncertain.",
    "While driving past an old farm house the party sees a horse mating with a cow, while driving on more and more horses with horns and udders are seen.",
    "While driving past an old farm house, the party sees a farmer next to a minatoress in a beautiful dress, they seem to have some type of ceremony.",
    "A dwarf from the north carrying a bucket on his back walks with you for (1d4) days, every evening he makes a beautiful meal for you and tell you stories from his homeland. (the party only loses half their rations these nights)",
    "A tiny turtle, with the word Tizian written on its shell, is seen walking on the side of the road a strange aura looms around it. He may heal (1d8+5)hp to anyone who holds him.",
    "You drive past a huge mansion, you can see several children running around, a half elf with a noble look and a wise looking dwarf waves happily at you from the porch. It restores your hopes for the future, a happy ending is always possible, even in a world like this.",
    "You see a two young women training in the forest, one seems to be a 14 year old fighter in an impressive red armour she keeps referring to herself as the Immith the arena champion, the other is an aasimar monk with beautiful silver hair. They duel furiously, the sight of which inspires you to train harder.",
    "You travel alongside a big mountain, one of you comments that it looks like a giant petrified troll. Not everyone in the party can see it, though.",
    "You travel past a small town, they seem to be celebrating a harvesting festival. Any player can pay 5 copper to join one of the many games and earn a prize (roll for one trinket).",
    "Nothing interesting was seen today, but at least the weather was nice.",
    "Late in the evening the party meets a charismatic tiefling women who introduce herself as the magnificent Frieda Kohl she carries a lot of instruments with her and for 1 gold each she’ll play them a song. When paid all her instruments magically start playing a beautiful song, the party is now motivated to keep going without sleep, getting an extra days worth of travels.",
    "The party finds corpses of a group of bandits, on top of the leader sits a black cat cleaning himself, he can be heard mumbling with a scottish accent. The cat gives you 5 silver each to forget what you saw and move on and vanishes.",
    "You see a 10 foot tall scarecrow, with two heads, a long cape and an ugly face. For a second you thought it moved, must have been your imagination.",
    "Out in a field you drove by you saw a living scarecrow shaped as a bird teaching a young farm boy martial arts, there’s also a dwarf walking around the field picking up rocks and then writing something down in his notebook. There’s probably a great story behind this.",
    "As it’s getting late you stop to sleep in a forest, that night you have a horrible dream about large, hairy, green creatures running around while making strange clicking noises. the dream ends with the creatures sprouting wings and flying of into the night. the next morning you notice the forest seems to have disappeared.",
    "A large rock is set next to the road, it has the names of many travellers carved into it, as you touch it your name is magically carved into the rock. Nothing else seems to happen.",
    "Along the road there seems to be strewn several different ball gowns, there seem to be one for each of the male party members in fitting sizes.",
    "You find a tiny altar dedicated to Pelor close to the road, whenever anyone prays to Pelor close to the altar it lights up.",
    "You see a fantastic oasis not too far off the road, as you get closer it disappears, must have been a mirage.",
    "Nothing much happened, it rains a lot.",
    "You find a book with your name on it as you open the first page you see a list of chapters named after your life achievements, the last three chapters are called the The Hero's Reward, A Dark Descent and A GoreyGory Demise. That night while no one is watching you burn the book.",
    "While traversing the mountains you see a bunch of goats walking 90 degrees up the mountain. They don’t seem to be worried by the heights.",
    "A minotaur challenges your strongest char to arm wrestle, roll a strength check (17 or higher) the winner gets 2 gold.",
    "You hear the flap of gargantuan wings and see an ancient red dragon flying in the distance disappearing behind a snow covered mountain.",
    "You see a dog with an empty toilet paper roll taped to it's head… Erh I mean, you see a gracious unicorn, one of the world's most beautiful creatures.",
    "A passing traveler tells you about the magnificent hank, gentlemen thief and master of disguise, he hands you a business card when he leaves with the name hank on it.",
    "You see 7 dwarfs walking to the mountains with pickaxes while singing a catchy tune.",
    "A tall man with a tattoo covered face walks with you for (1d4) days, he introduces himself as Mountain Leaper every evening he’ll prepare a meal for the party while telling them stories about his adventure. (the party lose no rations these nights)",
    "You see a bony and frail lone wolf wander roughly 50 yards from your party. It notices you and keeps a close eye on your movements. The eyes of the wolf glow red, it follows you for three miles then mysteriously disappear.",
    "Nothing much happened, it snowed a lot.",
    "You spot a small, cozy looking cottage on the hillside as your party walks on the trail. There is smoke rising from the chimney and there is a soft glow in the windows. However, as you approach there is a strange stench in the air.",
    "The huge shadow of an eagle falls over you and your travelling companions, follows you for a few seconds, and then speeds off to the North. Looking up you're dazzled by the sun, and can't tell if it's an eagle flying close to the sun and casting a huge shadow, or a Roc out hunting.",
    "A column of slightly-larger-than-usual ants is marching down the road side, carrying scraps of paper as other ants might carry bits of leaf. On inspection, it looks like each ant is carrying a single word cut out of a book, but you can't make sense of any of it or find the book.",
    "A single, giant-sized mitten hangs from a snowbound pine branch off the side of the road. A family of mice seem to be living in it now.",
    "There suddenly appears what is unmistakably a 'Flail Snail' trail on the road, but it vanishes again after a hundred meters or so, with no sign of the snail.",
    "A large rabbit with pigeon wings and tiny antlers emerges from a bush, sees you, then runs off into the forest",
    "Someone has hung lanterns through this stretch of the forest trail. At night they light up with colourful elemental light. Every so often, you think you can see a lantern far off in the forest, away from the trail. Probably a trick of your eyes.",
    "The forest which was wild at the start of your journey, has been cleared of all trees except for birch [willow, maple, whatever], and there are no leaves on the ground . You don't see any stumps. Nature check (10 or better) and you see that many patches of the earth have been filled in with fresh soil. Careful observation reveals that this patch of the forest trail deviates slightly from your map, but recombines with the expected trail when the birch forest ends.",
    "The trail has begun to run alongside a low, calm creek with flat stones at the bottom. The water is only about calf-high. Walking in the water is soothing and invigorating. However every so often the creek bed is marred with deep (20+ yard) stone holes, perfectly circular.",
    "Nothing much happened, the weather was hot and damp.",
    "You notice the whole world is actually a giant computer, with every person, animal, monster, and discreet action acting to compute, you decide to lay off the bottle for a while.(see hitchhiker'shitchhikers guide to the galaxy)",
    "The path climbs up a steep cliffside, only wide enough for single file travel. The air is dry and hot. Off the side of the cliff you can see a small village worth of gnomes are holding a forest fire at bay. They seem to have the situation under control.",
    "Someone has put down mile markers along the trail, big slabs of local stone with carefully carved dwarven numbers. They are not evenly spaced though, and don't seem to accurately reflect distance at all.",
    "A small clearing is filled with tents and campfires, with a wide array of folk making camp. The tents look like they have been there a while, all covered in leaf litter and debris. The campfires look to be well burned into the earth. Some of the campers are discussing the best location for a more permanent lodge.",
    "A fox is resting on top of a sunny rock. The trail splits in two to go around the rock and then recombines on the other side.",
    "You begin seeing signs and fliers posted in many different languages, Geoff's Fireworks and Inn, 5 miles straight ahead! and You won't want to miss out on Geoff's continental breakfast and fireworks display! No matter how far you travel, the signs promise it is only 5 miles ahead.",
    "It's late at night and not to far off the main road in the densely packed forest area you can hear sounds of laughter, the roar of a welcoming fire and its bright light and the smells of a home cooked meal. It somewhat reminds you of your own ragtag group when you rest up after a particularly hard day on the road. As you move on down the road you see this image of serenity flicks in and out of existence with every tree that you pass. You can see staring at all of you is one of the people who is around the fire but facing the road you're on. It seems to be a half-elf woman with ashen grey skin and moonlight colored hair and behind her is a large wagon that reads Caravan of Misfits. Just before you pass the final tree she gives a small nod of respect to your group. You share drinks that night, and you feel motivated to keep fighting for this world and the people in it.",
    "As the party crests a large hill, the forest thins to reveal the grassland. Endless green hills bump out of the landscape. Past the miles of gentle prairie lies an impressive mountain range, so tall it splits the clouds that flow past it. As a result, long strips of cloud stretch over the landscape (perception roll to notice subtle details of vegetation, such as wildflowers and foods?)",
    "Nothing much happened, but there was a big storm lasting the whole journey.",
    "While passing a field full of cows what seems to be a big flying greataxe flies down to the ground, a hatch on the underside opens throwing and a very confused cow is thrown back on the ground. The greataxe then flies off.",
    "A small rain cloud forms in the distance, and moves towards the party, as it begins to rain on the group, it seems the direction of the raincloud changes, and begins to follow the group. The raincloud is only about 20 feet across, and the party can tell that it is only raining in their direct vicinity. When the group approaches their destination, the cloud dissipates.",
    "You see a large brown sphere, in front of it is a plaque reading: World's largest ball of dung You've seen bigger.",
    "A male tiefling, hidden under a cloak, walks along the path you are on, trying to be inconspicuous. If asked, he reveals himself to a be merchant selling jars of his highly coveted dehydrated water. Just add water and you’ll have a jar of water in no time. (ie. a charlatan selling empty glass jars for a huge mark-up). A DC 10 Arcana or investigation check confirms it is just a normal glass jar with no special properties.",
    "You come across a Building which appears to be a warehouse. behind it there lies a huge dragon skeleton. A sign hangs in front of the building Pronouncing it as Ye Olde Dragon Corpse Shoppe",
    "During your sleep, you start to hear light rustling around your campsite, with nothing to be seen. As morning comes by, you wake up surrounded by a perfect circle made of stones",
    "You see a man with a strange hat, waving at the party up ahead the road.when you reach his location, there is only a pile of bones, and you hear a faint laughter, coming from the nearby forest.",
    "Snow starts to fall out of nowhere. You see one snowflake that didn’t melt in your arm and looking closely, notice it’s shaped like a humanoid",
    "Cicadas. You definitely notice the sound of Cicadas in the distance. After what feels like even more miles of journeying, the sound is almost upon you. The forest is alive with activity. Deer cross your path in a panic, bears are running to the river to drown themselves. As you pass through the Cicada forest, you wonder what god created such a horrible creature. As the light slowly wane, the sounds of the Cicadas remain, ever present in this forest. (Do you want to rest, or risk exhaustion to get through the forest?)",
    "Nothing much happened, you saw a rainbow though.",
    "As you are walking through the forest, the light grows dim, the sap on the tree's starts to glow, and the air starts to smell like your favorite food.",
    "The party sees an elderly blind woman, named Macha, walking along the road with her seeing-eye (blink) dog, Enyo. She is friendly and her dog is friendly as long as Macha is treated well. She will travel along the road with the party for 1d4 days and may offer support if the party offers to let her join them at their fire and provide a meal. Macha is an innate spellcaster and can cast each of the following spells once per day: Identify, Locate Object, Locate Creature, Legend Lore, and Augury. If combat breaks out, Macha will immediately leave the area with her dog. It is up to the DM how she does so, but in my game this NPC can cast any Divination spells at any time (Macha is a spirit)",
    "A creature charges into camp, stomps out the fire crying out Take that you dweebs! He then runs out into the darkness while laughing hysterically and repeatedly saying Good one, Brad to itself.",
    "A young female bard is playing on a lute off the road, she isn't paying attention to any of you.",
    "You see a squirrel on a tree branch. Make them roll Perception (dice 12). If they succeed, they see that it's holding an acorn with a huge, happy smile.",
    "A mermaid in a river/lake, sitting on a rock and singing beautifully. (Twist: she's trash talking the group in merfolk-language.)",
    "A blood-caked altar. Both the altar and the blood is old and you can see wax remains on the side.",
    "There’s a small stage in front of a field filled with women of all races, on the stage there seems to be a flamboyant curly haired bard in a TIGHT blue bodysuit with a red star on it next to him there’s a man dressed in black his eyes shine with both an all enveloping hate and an uncontrollable lust for blood. They seem to be singing a love ballad about long journeys and epic battles for a princesses Peppermint creams. The entire party must do a will check (dice 20) or be temporarily in love with the bard, leading to a bunch of awkward and new feelings for the rest of the travel.",
    "Nothing much happened, the sky is cloudy.",
    "You dream of an endless castle in the Feywild where an ashen skinned Eladrin asks you to help her destroy the corruption festering inside. After living through nightmarish encounters, and tricks that your mind can barely bend around, you wake sweating, with a name inscribed as a searing enigma into your memory Lannawnshee. Your restless sleep gives you a level of Exhaustion the next day.",
    "You turn a corner in the path and in front you is a wagon seemingly filled to the brim with various types of cheeses. Asleep in the dirt next to it is a large man. In between snores you hear him mutter various names of different types of cheeses, which you can only assume are the types in the cart.",
    "A lightning bolt strikes the path in front of the party, deafening them. After their daze has faded, they examine the spot only to find a large green gemstone embedded in the ground. It appears to be flawless, but as one of the players touch the gem, a spark arcs between it and their hand.",
    "A large swath of the road the party is travelling on has been lined on either end with long, wooden stakes driven into the ground. It is unclear why these stakes have been +driven into the path, as they are not connected and wide enough for anyone to walk through. The party cannot seem to remove or damage the stakes in any way, and the last stake is not yet driven into the ground. The party can choose to place this new stake, should they wish. On closer inspection, each statestake has names carved into them, presumably previous travellers.",
    "As you wind your way through the forest, a trail of breadcrumbs bisects the path. You can smell gingerbread faintly on the wind.",
    "The forest trail seems to never end, and time seems to draw on. As the sun begins to set in front of the party, it also begins rising behind them. They lose a night'snights worth of rest, but can still choose to make camp.",
    "A downcast Kenku walks alongside the road with you. Its black eyes are full of sadness. Unable to speak for itself, it’s only able to mimic back to you the yells and abuse it has suffered in nearby human villages. If offered the chance and the materials to do so, it eagerly makes a copy of anything you give it.",
    "As you camp in the mountain pass you hear thunder, but it’s not raining, and the stars are out. Once outside the firelight of your camp, you can see two giants down in the valley below hurling boulders at each other for fun. The thunder is actually the sound of a boulders smashing on a giants heads.",
    "A group of Kenku children are playing in the field beside you. They are making elaborate battle sounds using their mimicry as they do so. This may lead the party to think they’re being attacked.",
    "Nothing much happened, it was really windy outside.",
    "You see a group of nomads travelling in the distance, but they’re travelling steadily forward and you’re unable to reach them. A perception check might allow you to find their camp and barter with them in the future.",
    "You see a huge blue box, when you turn away you hear a strange sound and now the box seems to be gone. You sigh in relief, it wasn’t much to look at anyways.",
    "Camping out in a flowery meadow, you awaken at midnight. The full moon has risen behind the hill nearby, silhouetting half a dozen bears as they dance around a stone circle.",
    "The players pass under a man made arch of stone carved with intricate symbols in a forgotten language. As they pass, they feel a ripple through their body and find that when one of them goes to tell another of the feeling, they can no longer speak. Their surroundings are eerily quiet.",
    "Travelling down the road, minding your own business, you meet a man with seven wives. Each wife had seven sacks. Each sack had seven cats. Each cat had seven kittens. It’s weird.",
    "A tall man staggers towards you, wearing a long, hooded cloak. He looks drunk. His boots are far too small, and he’s wobbling from left to right as he walks. As he draws level with you, he falls over, revealing that he’s actually three goblins on each others shoulders. The goblins run screaming into the woods.",
    "Although you’re many, many miles from the sea, or even the nearest lake, you spot a Halfling building a large, single-sailed ship in the middle of a field. He seems happy enough as he works away.",
    "You look up as you walk, searching for anything to break the monotony of the endless fields. Two clouds glide towards each other, which is weird, as the wind should only be going one way. The one to the West is huge, and gliding East. It looks like a massive, horned dragon. To the East, and gliding West, there’s a cloud which looks like a smaller dragon with five heads. Both are destroyed when they collide.",
    "You encounter a heavily armored man walking with a cane, as you approach him he offers you the armor if you can best him in single combat, and grant him a death worthy of a warrior.",
    "Nothing much happened, but although there’s not a cloud to be seen and the sun is bright you are filled with a feeling of dread. Something is coming!",
    "As you walk through the forest trail a pair of bare feet make their way up the road towards you. As it gets a little nearer, you realize it’s a nude man in an invisibility cloak. You realize this because the cloak snags on a tree branch, and the man walks on a few paces without it, totally naked.",
    "Minutes after lighting your own campfire, bonfires flicker on across the hillside to the East. Oddly coloured smoke floats up from each fire, and the wind brings the smells of a dozen different reagents. These must be the potion moonshiners you’ve heard about.",
    "A small lodge sits in a clearing. It seems warm and inviting, the sound of smooth jazz flows out of a window left slightly ajar.",
    "The party approaches a clearing surrounded by various types of deciduous trees. Each of the trees has a bucket attached to a tap. The buckets are all filled to the brim with sap and in the distance you can hear a faint tune being whistled into the fall air.",
    "A woman rushes toward you in a frantic state. She is almost incoherent, but you can discern between sobs that her three year old has climbed into a gorilla disclosure in a nearby zoo. She asks for the parties help. By the time they get there, the gorilla has dragged the child around, killing it. She asks you to shoot the beast to death.",
    "An old man is sitting with his walking stick beside him, he starts into a tale about how a short blue haired girl became a God and gave her life so that her love can rebuild the world anew with somebody else he loved. He then mutters on insane. If the characters point out his seeming insanity to him, he replies with please, don’t remind me of my insanity yet, let me enjoy it for a little while longer and then goes back to linguistic static.",
    "A magical Inn seemingly appears out of nowhere and in the most odd place. The inn is well tended, stocked and provisioned. On top of everything the climate inside is perfectly comfortable. The wine is cold and a feast is laid out on a large table that dominates the Inn. Beds upstairs are clean, the pillows cold (on both sides!) and every need you can imagine is provided for (in an Inn sense). The food is top quality along with much of everything else. However. It is mysteriously empty. No one tends the Inn nor does it seem that anyone has disturbed it.",
    "If anyone spends the evening in the inn they wake to it cold and the life of the inn itself dispersed. The fire pits are cold. The food gone and the wine goblets empty. No ill effects are suffered from anything partake inside.",   "An abandoned cartwheel",
    "A holy man meditating at a roadside shrine",
    "A newly constructed traveler’s waystation",
    "A caravan of gypsies waiting for a birth",
    "A statue of a two-headed goat",
    "A covered well",
    "A squashed hedgehog",
    "A hermit’s cave",
    "A teahouse",
    "An abandoned barn",
    "The remnants of a campfire",
    "A dead sheep",
    "An old road, now overgrown and abandoned",
    "A footpath leading away",
    "A tumbled-down rock wall",
    "A tree adorned in prayer flags",
    "An oak tree split by lightning",
    "The ruins of a croft",
    "A standing stone",
    "A tiny roadside tavern",
    "An old blind woman begging for alms",
    "A coin",
    "Signs of a fight",
    "A totem depicting foxes and wolves chasing owls",
    "A boarded-up mineshaft",
    "An overgrown graveyard",
    "A broken, rusty halberd",
    "A scarecrow",
    "Three dead foxes strung up in a tree",
    "A mangy old dog",
    "The carcass of a giant, picked clean by vultures",
    "An abandoned child",
    "A gallows with a dead victim",
    "A coaching inn",
    "The corpse of a criminal in a hanging cage",
    "A road repair gang",
    "A pile of flagstones waiting to be laid",
    "A milestone",
    "A huge footprint",
    "A tumbling waterfall cascades into a deep pond",
    "A bent willow tree provides shelter",
    "A ruined bridge carved with dancing angels",
    "A quaint wishing-well",
    "A limestone gorge filled with ancient trees",
    "A lone tree upon a moor",
    "Mighty stones have weathered into incredible shapes",
    "Carved millstones lie abandoned in a flower meadow",
    "A stone outcropping that looks like a dragon",
    "The ruins of a once-majestic manor house",
    "A crumbling hillside",
    "A farmed valley with lush grass",
    "The still waters of a pool reflect an ancient dolmen",
    "A natural tower of broken, weathered stone",
    "Sunlight suddenly strikes the purple heather",
    "The sun picks out the hillside in a blaze of color",
    "A ruined croft with the chimney still intact",
    "A crumbling gatepost leading to a ruined croft",
    "A cobbled track worn smooth with age",
    "A standing stone in a hollow",
    "Curious weathered stones tumble down the hillside",
    "An old ruined chapel wreathed in ivy",
    "A shallow cave with a moss-covered floor",
    "A stone trough filled with flowers, overlooking a lake",
    "An old stone bridge with a small religious shrine",
    "A cairn with a wide panorama of the countryside",
    "A weathered flagstone path leads to a rustic barn",
    "A ruined tower surrounded by heather",
    "Ancient trees gather on a small knoll",
    "A fine bridge over a cool swimming hole",
    "A stone circle in a forest clearing",
    "An empty old burial cairn on the edge of a hillside",
    "A forest clearing bathed in sunshine",
    "An abandoned house by a river",
    "A ruined mill surrounded by cascading waterfalls",
    "A mighty oak towers over the path",
    "A village pond with ducks and dragonflies",
    "A holly bush with a ruined house within",
    "A statue of a man with a cloak of flowers",
    "A meadow filled with buttercups",
    "An old graveyard at the foot of a cliff",
    "A flagged ford across a river",
    "An outcrop of rock that looks like an owl",
    "Three intertwined apple trees",
    "A curious rocky tor rising from a small copse of trees",
    "A pond clogged with watercress and lilies",
    "A green lane surrounded by ancient sycamore trees",
    "A natural seat under a cliff, draped with kudzu",
    "Bright red berries swing from the arch of a tree",
    "A hollow holds three graves, surrounded by ivy"
    ]

var worldWeather = [
    "Balmy: mild and pleasant weather",
    "Blizzard: a dense snowstorm",
    "Bluster: strong wind",
    "Breeze: light wind",
    "Calm: no wind",
    "Chill: unpleasantly cold",
    "Cool: moderately cold",
    "Cyclone: violent, destructive storm",
    "Damp: moisture in the air",
    "Deluge: sudden heavy rainfall",
    "Dew: condensation forming just above the ground",
    "Downpour: heavy rainfall",
    "Draft: current of air",
    "Drizzle: fine rain",
    "Drought: continuous dry weather",
    "Dust storm: severe windstorm lifting dust and sand",
    "Fair: pleasant weather",
    "Fog: thick mist or cloud",
    "Freezing rain: rain that freezes when it lands",
    "Frigid: intensely cold",
    "Frost: frozen dew",
    "Gale: strong wind",
    "Hail: pellets of frozen rain",
    "Haze: condensing ground vapor caused by heat",
    "Heat wave: prolonged period of warm weather",
    "Humid: warm, moist air",
    "Hurricane: windstorm moving around a central point",
    "Mild: moderately warm weather without rain",
    "Mist: water vapor in the air",
    "Monsoon: heavy, prolonged seasonal rain",
    "Muggy: damp, warm, oppressive weather",
    "Overcast: heavy cloud cover",
    "Pea soup: thick yellow fog",
    "Rain shower: short period of rainfall",
    "Rainfall: prolonged period of rain",
    "Sleet: ice pellets mixed with rain or snow",
    "Smog: smoky fog",
    "Snow flurry: short period of light snow",
    "Snowstorm: prolonged heavy snow",
    "Squall: sudden, localized storm",
    "Storm: violet wind and rain",
    "Sunny: bright, clear weather",
    "Temperate: without extremes of warm or cold",
    "Thunderstorm: storm with thunder and lightning",
    "Tornado: destructive, rotating windstorm",
    "Tropical storm: cyclonic storm from the tropics",
    "Typhoon: violent cyclonic storm",
    "Warm: moderately hot temperature",
    "Whirlwind: violent wind moving in a circular motion",
    "Whiteout: heavy snow, causing visibility problems",
    "Partially Cloudy - The clouds block the sun periodically, causing some shadows to be cast over the lands.",
    "Sunny Day - Roll a d6, 1 - The warm sun feels good on your skin, 2-3 - You become very sweaty (-1 on all strength rolls for six turns), 5-6 - You get a sunburn (-1 on all strength and charisma rolls for the rest of the day).",
    "Slight Breeze - The wind is refreshing, and your mood is increased. +1 to all charisma rolls for 1d10 turns.",
    "Very Windy - You have to push against the wind with nearly every step. -2 to all dexterity rolls for 1d10 turns.",
    "Light Drizzle - The soft rain makes you think about your past. +1 to all intelligence rolls for 1d10 turns.",
    "Tornado - Find shelter that can keep you safe from the destructive nature of the nearby tornado.",
    "Light snow - The snow calms you. Wisdom and charisma increase by 1 for 1d6 turns.",
    "Fog - It’s hard to see. -2 disadvantage in any action based roll.",
    "Icy Wind - A cold wind blows in from the north.",
    "Frosty Air - A very cold wind blows in from the far north, bringing hints of snow.",
    "Astral Disturbance - Something shifts in the Astral Plane. Nearby wildlife runs in fear. Trained animals are fearful, but do not flee. Nearby players feel a shift in something in the back of their minds.",
    "Arcane Radiance - The sky is lit up with a brilliant light that extends from horizon to horizon. It is awe-inspiring, but strangely calming.",
    "On the Hunt - The wolves are out hunting again. They probably won't attack, but don't expect to find any wildlife. They're all running.",
    "Essence of the Shadowfell - The area darkens for a split second. A disturbance occurred in the planes, bringing hints of necrotic energy and darkening the entire area for a 1d6+3 minutes. The area is now considered dimly lit instead of brightly lit, or total darkness instead of dim lighting.",
    "Foreboding Calm - The first warning of a storm. Hurry, before it hits.",
    "Fury of the Elements - A great storm hits, pouring with rain, crackling with lightning, and howling with wind. It demands attention and refuses to let anyone sleep.",
    "Hail - either small annoyances that disrupt concentration checks to a barrage of ice the size of fists that could knock out an orc. Either way, seek shelter",
    "Sunshower - A deluge of rain yet the sun shines in full force. Some say it's sign of the occurrence of marriage between magical creatures (or foxes) or that the devil is beating his wife in anger at how beautiful the day is. Some say its a moment of balance of the opposing forces in nature, others say its just one of those phenomenon. Up to DM which of these is true.",
    "Massive (tropical) rainstorm - The deluge is oppressive. The din of rainfall is the only thing you hear. Visibility is nil beyond a few feet. Beware of flash floods.",
    "Little fall of rain - You are caught in a light shower. For some people, this is an annoyance. Small cut to concentration and charisma in their surliness. Some people enjoy the rain and the sensation of water droplets on their bodies and get a boost to wisdom and charisma. Others don't mind but would really rather be somewhere dry.",
    "Silence in the forest - After hours of the non-stop sound of bird song and animals rustling in the plant life, the massive silence that follows is somehow more crushing. What would cause an entire forest of wildlife to not want to draw attention to themselves?",
    "A great migration - Ants blanket the forest floor in purposeful movement, a sea of red crabs march over a sleepy fishing town, mosquitos, thick as fog, all buzz in one direction, a crowd of lemmings run off a cliff and those that survive resume their marathon at the bottom. All riffs to the same song, a lot of animals going in one direction. A witnessed annual migration? Or something more sinister?",
    "Predatory desperation - Food has been scarce in this location lately, whether through over-hunting, adventurers' over-eagerness or disasters of a natural or magical sort. What matters though are there are going to be a lot of hungry animals and they might be insane enough to put you on the menu.",
    "Signal Flare! - a single comet of light climbs into the sky before exploding, filling the heavens with radiance. A poor soul looking for rescue? A signal of command undeciphered? A poorly thought out gnomish rocket launch? Or just swamp gas and will-o-the-wisps? Only one way to find out.",
    "Avian circles - A legion of birds of varying sizes and species, all flying in massive concentric circles in the sky, the biggest one probably kilometers wide. That can't be a good omen.",
    "Umibozu - On the high seas, there in the horizon, a colossal, shadowy humanoid specter looms. Do not speak it's name or draw it's attention, for it is known for spelling doom for ships.",
    "Cloud watcher's delight - Some strange looking clouds around this area. Almost as if they were shaped. Maybe they look like magic runes, seemingly carved out of clouds. Perhaps they spell instructions for the party or, depending on how 'well' the party usually takes advice, expletives tailored towards them written in plain text. Maybe they look like animals as though drawn by a child. And that one looks like two figures in-oh.... Let's hope there are no children around to see that.",
    "Fireworks Shower - The night sky is lit up with a series of brilliant coloured lights that last for a split second only. A celebration nearby? A trap? An arcane experiment gone wrong? Who knows? It's quite nice.",
    "Great Plague - A swarm of locusts, coming over the horizon, eating everything. This may last several days.",
    "Great Druid's Calm - The wild things are glad. A peaceful atmosphere reigns.",
    "Chaos Influx - A small entry from the Elemental Chaos. Puffs of smoke, small fires, water, wind, pebbles.",
    "Stampede! Roll 1D4 to have a stampede of; 1. Giant elephants, 2, Elephants, 3. Deer, 4. Rabbits run past the party.",
    "Rainbow - A pleasant rainbow shines, formed from a nearby rainshower.",
    "A Wild Friend is Born - The local wildlife and even plant-life seem to bow before this grand newborn. Is it a powerful elemental, or the next king of the jungle?",
    "Heatwave - The sun licks the earth with a sweltering power. Be sure to stay hydrated, and in the shade, or make a constitution roll to keep moving. If the roll is failed take 1d4 heat damage every 1d4 turns.",
    "Dust Storm - Blistering winds of sand blow in from the nearest desert. -2 Perception and -1 Dexterity.",
    "Meteor! - Roll 1d6; 1-2. A large celestial rock streaks across the sky, crashing into the land a ways off. 3-4. A massive stone comes crashing nearby, sending up a large amount of dust. Fires may start due to the residual heat. 5-6. The meteor is heading your way! Make a Dexterity roll; if failed, take 2d10 damage!",
    "Beautiful Blossoms - The local flowers are blooming! By breathing in the sweet and calming aroma restore 1d4 HP!",
    "Birds of the Forest - The local songbird population is in full song! Cheerful sounds of chirping and whistles from a variety of birds fill the air, providing a lovely background noise to travels. However, the birds sound lowers passive perception while in this neck of the woods by 1."
]

var worldClimate = [
    "Antarctic: southerly area of extreme cold",
    "Arctic: northerly area of intense cold",
    "Basin: tract of land drained by a river",
    "Beach: shoreline along a body of water",
    "Bog: wet ground made up of decayed vegetation",
    "Butte: isolated hill with steep sides",
    "Caldera: cauldron-like bowl caused by a volcano",
    "Canyon: deep gorge or ravine with steep sides",
    "Cave: small subterranean opening",
    "Cavern: large subterranean chamber",
    "Cliff: steep-sided rock formation",
    "Coast: tidal shore",
    "Crater lake: lake formed in crater of a volcano",
    "Desert: arid, barren land",
    "Dunes: hills of sand in deserts",
    "Farmland: agricultural land, often enclosed",
    "Fen: low marshy or flooded area of land",
    "Forest, coniferous: chiefly evergreen forest",
    "Forest, deciduous: forest of trees that shed leaves",
    "Glacier: slow-moving mass or river of ice",
    "Hills: landforms that rise above the surrounding land",
    "Icecap: permanent covering of thick ice",
    "Isthmus: narrow strip of land connecting two areas",
    "Jungle: land overgrown with vegetation",
    "Knoll: small natural hill",
    "Lake: large, inland body of water",
    "Limestone upland: exposed limestone outcrop on hill",
    "Meadow: land that periodically floods",
    "Mesa: elevated area of flat land",
    "Mire: swampy ground",
    "Moors: upland landmass usually covered in heather",
    "Mountain: prominent landmass of exposed rock",
    "Mountain, high: mountain with permanent glaciers",
    "Mountain pass: saddle point between mountains",
    "Ocean: large body of water",
    "Oxbow lake: U-shaped body of water",
    "Peninsula: point of land almost surrounded by water",
    "Plains: level tract of land",
    "Plateau: elevated tract of relatively flat land",
    "Ravine: small valley",
    "Ridge: a continuous elevated crest",
    "River: large watercourse",
    "Scree: broken rock fragments at a mountain’s base",
    "Stream: small watercourse",
    "Subterranean: below the surface, usually caverns",
    "Swamp: wet, spongy ground",
    "Tundra: vast, treeless region in arctic or antarctic area",
    "Valley: long depression or hollow between hills",
    "Volcanic: region with volcanic activity",
    "Wetlands: wet, soggy, seasonally waterlogged area"
]


var landscape_feature = [

"Massive Crevice. A massive crevice stretches out before the party. The crevice is 1d20+5 meters wide and you will lose 1d8 hours if you cannot find a way across it.",
"A Grove of Dead Trees. A grove of dead trees rest here. 1d4 = 1 you find a small pond with a peculiar skull in it. The skull reeks of Undoing and is likely the reason the trees died. 2-4 = The trees seemed to have been killed by a naturally occurring insect and make for excellent firewood.",
"A peaceful glade. Sleeping here results in +1 Exh and FP recovered.",
"Bod with Bog Mud. A bog 1d4 miles in radius is here. Difficult terrain. See rules for bog mud.",
"A Seemingly Peaceful Glade. The area was the site of ancient rituals and anyone who sleeps here automatically fail their rest check. A Sight check SC 15 can determine this.",
"Natural Camouflage. An area particularly rife with large bushes offering ample opportunity to hide but does not slow down travel. Advantage on Hide checks. Roll 1d6, on a 1 raptors or trolls have discovered this too.",
"Treacherous Terrain. The terrain is difficult to traverse, with many thorny plants, sudden changes in elevation, and loose rocks. Traveling here incurs +2 exhaustion.",
"Forest Clearing with Razorgrass. A clearing in the woods looks inviting, either to camp in or move through. But there is razorgrass here, see the rules for razorgrass.",
"Short Cut. The party navigator finds what they believe to be a shortcut which can cut down their travel time 1d4+1 hours. They must succeed on a SC 12 Wilderness Lore check to ensure they go the right way, if not they low 1d4+1 hours. Either way, the shortcut is difficult to traverse and it costs 5 Exh to move through it.",
"Buried Buildings. With a SC 14 Spotting check, they discover the buried foundations of a small cluster of buildings. Roll 1d4. 1= People of the Three Peaks hamlet which could be excavated, the location is worth 1d10 gold sovereign. 2-4 = earlier settlers who failed, but the land looks cleared of rocks and re- settlement might be swift. Excavating would take a minimum of 1d6+5 days, but might result in treasure.",
"Area with Strong Weave. This area is particularly strong with the Weave. Any rituals cast here cost half. In addition, it is particularly strong with one of fire, water, earth, or air, resulting in half cost for primordial spells of that element. Because of its strength, when rolling for Magick a critical failure is 1-3 and you have +10 to the critical failure table.",
"Abandoned Paved Road. The road was built by the People of the Three Peaks several centuries ago. There is a 1% chance that it leads you to the ruins of a settlement, a 30% chance that following it costs the party 1d4 hours, and a 69% chance that following it is shown to be pointless quickly.",
"Abandoned Well. An abandoned well. There is a 10% chance the water is contaminated and drinking it infects a person with Hellmaggots.",
"Great View of the Sky. A clearing in the forest on a small hill allow for a tremendous view of the sky. Any Astrology checks have advantage here, and this spot would be ideal for an observatory.",
"Point of Interest Atop a Hill. A steep hill leads to a point of interest: A small cave suitable for shelter granting +1 Exh to any who rest in it, a peculiar formation of stacked rocks, a particularly flat area suitable for structures, or a lone tree of some size. Regardless, scaling the hill costs 1 exhaustion and requires a SC 10 Terrain Scaling.",
"Area of Natural Fog. This area is inundated in fog during most times of the year due to a natural connection to the Mistlands. There is a 70% chance for each day spent here that there will be an encounter with the Lost. Navigating here is done with -3 SC.",
"A Marsh. A 1d4 mile area marsh where the party can find marsh plants or hunt marsh animals.",
"Dense Ghostpine Forest. A 1d8 mile area with dense ghotspines growing. This information may be valuable to a sawmill 1d20 gold sovereign.",
"Dense Undergrowth. Dense undergrowth add +1 Exh to travel, but hiding offers advantage.",
"Light Undergrowth. Light undergrowth offers advantage to small game hunting.",
"Massive River. An uncharted massive river stretches out before you. It is 1d100+20 m in width and needs to be crossed somehow. Roll 1d6, on a 1 there is a hungry river serpent in the river. The river is suitable for fishing though.",
"Clearcut Area. At one point in time this area was clear cut, resulting in an open space with young plants. Hunting medium game is done with advantage here as they love to come feast on the growing plants and are the reason it has never grown back.",
"Battleground. An ancient battleground. SC 15 spotting to notice the bones and tatters of clothing buried in the ground. 1% chance of finding a useful piece of weaponry or armor. 10% chance to find a trinket value 1d100 silver. 25% chance that sleeping here is interrupted by the howls of the dying, resulting in interrupted sleep.",
"Extremely Rough Terrain. Counts as inhospitable terrain and therefore adds +3 Exhaustion to travel here.",
"Hot Springs. A series of hot springs. Bathing here restores 1d6 MP, FP, and Exh. Can only be benefitted from once per week though.",
"Cave Spring. A small spring is trickling out of a cave. Waterskins can be refilled here. A great place for a permanent camp. Advantage on hunting medium and small game here as they often come to drink from the spring.",
"Elevated Camp Site. A location atop a small hill particularly suited for camping. All spotting checks against creatures approaching have advantage from up here.",
"A Grove of Apricot Trees. A grove of delicious apricots. Roll 1d4, on a 1 this is an abandoned grove and the apricots are domesticated, thereby larger, but ripen only in Fall. On a 2-4 they are wild and ripen in batches rather than simultaneously. Foraging here offers 1d4 rations instead of the usual 1",
"Elevated Vista. A beautiful vista of the surrounding forest from an elevated position. Resting here for an hour restores +1 exhaustion and 1d4 FP.",
"Area Rich in Clay. This area is particularly rich in high-quality clay, something which would be useful to someone wanting to set up a clay mining operation. Value of the information is in the region of 1d10 gold.",
"Area of High-Quality Stone. This craggy area is rich in edrite stone, a particularly sturdy building material that is highly sought after on Arevor. Similar to marble in shine, luster, and hardness, but lacks the marbling.",
"Dried Lakebed. A dried lakebed, offers a good place to set up a farming community.",
"Rolling Hills. Rolling hills in a 1d8 mile area offering a wonderful spot to set up orchards. Costs 1 Exh to get through though.",
"Natural Rock Formation. The rock formation has the shape of a face, animal, object, or is simply beautiful in its own right. Can be used as a clear landmark.",
"Ancient Gateway. These do not look like much; merely a series of young branches woven into a spherical gateway held in the air. A SC 15 Sight check would reveal the gateway is strong in Dark, Fire, and Chaos. SC 15 Demons would reveal that this type of gate is used to summon such entities. SC 15 Weave would be able to identify this as a gateway used to summon other entities, but not necessarily what it was used for.",
"Grape Orchard. See grove of Apricot Trees but replace apricots with grapes.",
"Large Ruins. These are the ruins of a village or a castle belonging to the People of the Coast. Today one of the following creature types occupy it: Trolls, Lost, Cavern Whisperers, or empty. Regardless, there is a 25% chance there is treasure within. Not to mention the historical value.",
"Small Ruins. These are the ruins of a single structure. On a 1 it belonged to the People of the Coast and is either a homestead, tavern, or workshop. Most likely a homestead. Otherwise it is the ruins of a homestead belonging to a group of settlers who failed. There is a 10% chance a group of Cave Whisperers have taken up residency. The ruins can be used as a landmark. There is a 15% chance they also contain common items left behind. If the ruins are from the People of the Coast they contain 1d6 gold worth of trinkets.",
"A Deep Gulley. You can walk around but will lose 1d4 hours. Climbing the sides require a SC 12 Terrain Scaling and costs 1 Exhaustion to attempt. The bottom of the gulley hosts a small stream where fishing can be done.",
"Tea Orchard. See 28 but for tea.",
"A Collapsed Cave. This cave collapsed naturally many years ago. Functions as a great landmark. If the Party spends 1d4 hours excavating it there is a 30% chance they will find the bones of a large-huge animal or beast within.",
"An Empty Mineshaft. See the hidden crevice in the rules. Don’t fall in.",
"Animal Burrows. This area is littered with animal burrows in a 1 mile radius. Hunting small game here is done with advantage.",
"A Small Camp. On a 1 this permanent camp is inhabited by 1d4 hunters, prospectors, scouts, or adventurers. Otherwise it abandoned but contains some basic adventuring gear. Good spot for staying the night though. ",
"Area of High Grass. This 1d4 mile area is almost void of trees but is very humid and covered in chest- high grass. There is a 25% chance a group of raptors are prowling the area. A SC 15 Taxonomy check will identify the grass as a type of grain which can likely be domesticated.",
"Apple Orchard. See 28 but with apples.",
"A Mineshaft. Beware falling in. There is a 10% chance this mineshaft has mineral finds. Iron, copper, zinc, tin, led, silver.",
"A Trickling Brook. A small brook, functions as a landmark and to refill waterskins. Fishing can be done here. If attempting to fish a large fish they can catch exactly 1 but double the yield.",
"Wildfire Area. This area is recovering from a recent wildfire and stretches 1d4 miles.",
"Cave Shelter. A nice little area for setting up camp for the night. Offers complete protection from the elements and gives advantage on the rest check.",
"Waterfall. A small waterfall with a 10% chance of treasure behind it.",
"Ruined Camp. The camp was used recently but was destroyed, SC 15 tracking to figure out what destroyed it. No one seems to have been injured though. Good camp site.",
"Small Lake. A small lake with plenty of fish. 15% chance of a lake serpent. Advantage on fishing.",
"A Large Lake. An uncharted large lake with ample opportunity for fishing and diving for freshwater pearls. A careful examination of the area will reveal ancient fishing traps and other signs of prior habitation. Would be a great spot for a settlement.",
"A Bog With a Light Man. A 1d4 mile area bog. At night strange lights are seen in the bog. Following the lights will lead to bog mud which you have disadvantage to spotting.",
"Lookout Point. Standing on this elevated spot affords a 20 mile radius view, allowing for the possibility of being forewarned of what will happen the next day. Also grants advantage on navigating the wilds, and serves as a landmark.",
"Rare Herb Spot. A spot where rare herbs grow. Invisible Hair, King’s Parsley, Prismatic Mulberry, or Serpent Wormwood. You can harvest 1d6+1 here, but the spot is valuable for long-term exploitation of the herb.",
"A Steep Area. This area is steep and needs to be scaled at the cost of 1d4 exhaustion to get through.",
"A Small Hovel. There is a 10% chance that this hovel is the home of a witch/hag. If so she has peculiar items for sale, see below. There is a 50% chance the hovel is abandoned, and a 40% chance the hovel is home to a hermit.",
"A Small River. In order to continue they must make it across this small river that is 1d10+5 m in width.",
"Area suitable for Arcanum extraction. The rock and soil in a 1d4 mile area is particularly strongly infused with the Weave and thus very suitable for Arcanum extraction.",
"Area of herbs. This area has many patches of densely growing herbs, giving anyone searching for common and uncommon herbs for components or to be used in other recipes advantage on the check.",
"The entire hex is difficult terrain. The trees and undergrowth here is dense, making it difficult to traverse.",
"A Mammoth graveyard. Within a 1d4 mile area, there are many mammoths buried. Although most of the bones are too old to be of much use, people looking can find mammoth ivory here. With a successful spotting check, it is possible to find 1 lb of ivory per days work.",
"Fertile Soil. The soil within a 1d12 mile area is particularly fertile, making it a good place for a farming community.",
"A sea of ferns. Dense ferns cluster in a 1d4 mile area, offering ample opportunities to hide. This area offers advantage to finding raptor nests. In addition, there is a 75% chance at any given time to encounter raptors.",
"A well-worn animal path. A well worn animal path leads 1d8 miles onward, making travel significantly easier. This is also a good place to construct a road.",
"Lindworm Lair. A cavern opens up in a small hallow. Outside of the cavern are a multitude of ancient trinkets, silver, gold, and other offerings as well as several stone and wood stelae and totems alongside other ornaments. This is the lair of a lindworm and the trinkets are offerings from people past and current. There is a 25% chance the lindworm is home.",
"A small tribe of Lizardfolk. A tribe of 1d10+5 lizardfolk have set up a handful of small huts. They are aggressive, but unlikely to be the first to attack. They do not speak Imperial or any Arevorean languages. They can offer bone trinkets and tools for food.",
"A crossroads. This crossroads offer advantage on any attempts at summoning demons or dealing with the Hells. ",
"Dense redpine forest. This 1d20 mile area is particularly dense with majestic redpine, making it a valuable location for logging.",
"Ruined Tower. This tower was built several centuries ago and its inhabitants were killed by the Lost. There is a 50% chance it is home to a nest of Cave Whisperers. Within there is a chance of finding trinkets and a valuable tome. In addition, there is a small overgrown herb garden outside where uncommon herbs can be found.",
"Animal Tracks. This area is rich in animal tracks and offer advantage on any small or medium game hunting checks.",
"Abandoned Quarry. A massive quarry stretches out before you. Today, overgrown by ferns and brush. There is a 25% chance trolls occupy the quarry and 25% chance Cave Whisperers do. This would be a good location to mine for one of: salt, quartz, marble, granite.",
"Area weak in the Weave. This 1d8 mile area is particularly weak in the Weave and all costs are increase by 10. In addition, spells in one of the following elements have disadvantage: fire, water, air, earth.",
"A crystal cavern. This cavern is filled to the brim with crystals and/or gemstone. There is a 5% chance it contains ley crystals. A 5% chance it contains valuable gemstones. Otherwise, it is filled with mundane crystals and common gemstones. You can harvest 1d4 lb of crystals per day or half a lb of gemstones. Mundane crystals have a value of 10 s/lb whereas mundane gemstones 1 g/lb. Ley crystals is far more valuable at 50 s/lb and valuable gemstone value is based on type.",
"A Troll Camp. You encounter a troll camp with 2d10 forest trolls and 1d8 greytrolls.",
"Beautiful Vista. You encounter a beautiful vista, birds are chirping, a gentle breeze is blowing. Life isn’t so bad after all.",
"Rich hunting grounds. This area is particularly rich in large game, offering advantage on any checks to hunt such.",
"Area of grassland with grasslands flora and fauna. This 1d12 mile area has little in common with the surrounding forest. Here you can hunt grasslands fauna and search for grasslands flora.",
"Grove of Copperoak trees. You find a small copse of copperoak. 1d4 trees are suitable to be harvested and is worth somewhere in the region of 2000-5000 silver per log.",
"A tunnel. This tunnel appears to be made by some animal. There is a 25% chance it is being used as a den and a 5% chance a massive purple worm is nearby.",
"Rich foraging grounds. Foraging in this area grants you 1d4 rations instead of 1.",
"Ring of mushrooms. A ring of mushrooms signals a weaker boundary between the material realm and the fae realm, meaning all Magick pertaining to the fae realm is cast with advantage here. There is a 10% chance that faeries are in the area and will cause trouble.",
"Ancient shrine to the Blood Gods. This shrine was erected when the Blood Gods were still walking the land. Any Blood Magick is halved in cost, and any servants of the Blood Gods who make a sacrifice here gain a permanent 10 MP.",
"Area of strong Magick negation. This 1d8 mile area is filled with chaotic Weave. Any Magick used here always rolls on the Magick critical failure table even though the spell may succeed.",
"Area of difficult terrain. This 1d8 mile area is difficult terrain.",
"A kurgan mound. A single burial taking the shape of half a dozen mounds look like small hills. Excavating the area will yield treasure. There is a 15% chance there is an entrance and 1d4 Draugr and 1d12 phantoms reside within.",
"An area of steep hills. This 1d20 mile area is craggy and composed of steep hills. Travel here costs 1d6 exh extra unless pace is slow.",
"Kurgan fields. A 1d4 mile area of small hills stretch out before you. It is clear that these are burial mounds. A large number of People of the Coast are buried here. Disturbing the graves have a 50% chance to awaken a Draugr and/or 1d6 Phantoms. Each day of excavation has a 5% chance of finding a small hoard. Spending the night here raises the resting SC to 18.",
"A surface seam of ore. Iron, tin, lead, copper.",
"Sulfuric Pools. A series of sulfuric pools spread a foul stench over the area.",
"Rickety wooden bridge. A rickety wooden bridge leads over a small chasm. The bridge is safe, but looks incredibly unstable. Walking around the bridge adds 1d4 hours to the travel.",
"A crater. It may not be clear at first, but eventually it becomes obvious that you are standing in a huge crater 1d4 miles in area. The soil here is particularly rich and all foraging or herb searches which are successful offer double yields. Similarly, the animals here offer 10% greater yield. ",
"Megaliths. A series of massive stones have been erected here and the area is Magickally powerful. Anyone who sleeps here gains +5 MP. In addition, sacrifices offer double effects if performed within the megaliths. Anyone who spends 1d4 days examining the megaliths will learn of the People of the Coast and gain +1 to Nau’tl language.",
"Standing stone with names of nearby settlements now gone. This standing stone names 1d4 places and their direction. You need 3 Nau’tl to read it. Micxa, Tetlie, Ozatl, Linte, Coatl, Etxilu.",
"Hollowed Trees. Nature have carved odd hollows in these dead trees. When the wind is light, they produce a soft, soothing sound, giving advantage to rest checks. If the wind is strong the opposite is true.",
"Witches’ Grove. This grove is particularly strong in Weave pertaining to Witchcraft. Any witchcraft rituals performed here costs half and may have a stronger effect. Every full moon a group of hags gather here to perform rituals.",
"Flooded Cave System. This cave system is marked by small hollows in the ground, some just barely large enough for a person to squeeze through. At any given time, there is a 75% chance that the system is home to a lake serpent. The cave system goes on for miles, but careful exploration has a 10% chance per day to reveal a small hoard, and 5% chance to reveal a useful metal find: iron, copper, tin, lead, gemstones, silver.",
"Dragon Lair. This is a dragon’s lair. No one should enter here. The cavern is massive and marked by the skeletal remains of the dragon’s prey. Entering the lair, there is a 60% chance the dragon is home and generally does not enjoy having unexpected guests. The dragon sits on a dragon hoard. If so much as a coin is missing, the dragon will go to every length to find the thief. "

]

var world_vignette = [

"Ahead on the track is an upturned cart, the horse and rider gone the contents of the cart scattered across the churned up ground. As the players approach the cart they hear a voice call out from up a tree some meters away, a disheveled figure waves to them and seems to be pointing at them, 'Bulettes! BULETTES!!' The ground begins to tremble.",
"An upcoming path through a forest narrows drastically, and in the path bodies of humanoids can be seen hung from trees, their feet dangle inches from the ground, blocking the path ahead. Closer inspection reveals the bodies are undead, and serve as a make shift alarm system for whatever has made its home beyond.",
"A raving man who looks and smells like he lives in a ditch is causing a scene near the palace gates, claiming to be the prince of a land no one has heard of before.",
"A local friendly witch wants assistance in catching her escaped pet. The problem is that after being experimented on for years, the animal has developed the ability to teleport short distances at will.",
"A filthy looking wizards apprentice has been living on the streets for days, too scared to return home. They had tried to resurrect their pet cat, but what came back wasn't a cat, so they bolted the doors and ran. But now the master wizard is returning home and the apprentice needs help to deal with the monster they made. If the party agree to help, they find the basement over-run with Gremishkas (from Van Richten's) or possibly just a zombie cat and a dozen zombie rats it has eaten since.",
"You encounter a lost goblin child holding a piece of parchment in his/her hand, trying to find their way back to their goblin tribe. They're holding a scroll of wish written in Goblin.",
"You see a young child playing with what you imagine to be their imaginary friend. All seems well at first, but a one sided argument erupts and the child swears at the invisible friend. Moments later the child is thrown to the ground and starts wailing. A visible hand print has starting welting on their cheek.",
"A disguised fey in the entrance of a town asks everyone who enters for their name (i.e. 'May I have your name?'), when they enter town they no longer remember them.",
"A young adult approaches you on the street. They say they have fallen for a romantic interest. They ask you to meet them on the same street in the night, where they will be with their romantic interest. All you need to do is act tough and threaten them, and flee when the asker 'scares' you away.",
"A battered humanoid in the trees beckons you over with a hand waive. A keen eye may notice fine thread running from his limbs up into the canopy. A large, intelligent spider sits up there, puppeteering the corpse of the recent victim to lure new prey into its webs.",
"On the edge of town there is a public trial being held before a crowd. On trial is a pig, it is wearing a suit.",
"A tree lands on the ground in front of the group. It appears to have been flung from somewhere over the tree line. Shortly after the ground starts to shake, the trees move apart and a giant steps out. The giant is actually practicing for a contest that will be held soon 'insert reason for contest if need be' and tries to apologize to the party before continuing with his training. Variants can easily be done with different large/huge creatures and sports (trolls footballing with a dead cow , minotaurs playing pettanque with boulders ...)",
"A hag's child comes of age and doesn’t understand what's happened to them. They’re sitting in a forest, crying about how they’re ugly now and they don’t understand what happened. Bonus points: they’re the missing princess.",
"The players round a corner and find a figure frozen in surprise. It is unmistakably petrified. And it's fresh.",
"The characters team up with a Robin-Hood style band of outlaws to rob the rich and give to the poor. Many levels later, the now-extremely-wealthy characters get robbed by those same vigilantes, who intend to give their money to the poor. If confronted, 'Robin Hood' can point out how they just sit on it and never use it for anything, never mind charity.",
"You find a bureaucratic devil sitting at a desk shuffling papers in the middle of the road. He wants to make a deal",
"The party find a good campsite, with plenty of cover from visibility, shelter from the elements, a stream of clear water, game etc. Any outdoorsy characters good at survival etc can have it put down to their own skills. They notice it’s been previously used by a similarly sized group years ago, with a few items of used mundane equipment, like cooking utensils and blankets scattered around and half buried by time and undergrowth, but there are no signs of combat and no tracks. Anyone on watch notices lights, like fireflies (actually minor forest/fey spirits if nature characters examine) attempting to guide them to a nearby copse, where they can choose to investigate, looking around. Interacting with some sigils carved on trees gives an arcana, wisdom, survival or language check that it’s a spell of imprisonment, now encompassing them too, requiring a ‘gift of value in return for hospitality given (the campsite)’. This gift isn’t necessarily financial or even physical value. A bard, Druid or ranger, or anyone with an academic interest in history/myth/magic, might realize that pure water, a song, a story, freshly prepared food, a simple toy or charm or anything that they’ve personally crafted, sewn, carved etc, or a keepsake are all appropriate too, the more heartfelt and related to hearth and hospitality the better. Successful, heartfelt roleplay by each PC, or at least offering something, gives a sense of power released. Returning to camp finds the ‘other party’ prepared to defend it as if nothing had happened and they had been sleeping there the whole time, but it becomes clear they have lost several years of time and didn’t realize or understand the requirement for a gift given in exchange for hospitality that wasn’t freely offered and of no obligation (which was the perfect campsite for adventurers). They will be talked down fairly easily and offer the party a reward for saving their hides, before heading off in a direction the party aren’t travelling in, probably to the last settlement the party came from. Refusal to investigate means nothing happens, but the disappeared adventuring party is a cool weird reminder that it’s not just bandits and ambushes etc they can find out there. Desecrating the campsite in any way leads to heavy combat with dryads etc (some characters may have an insight check after the nature of it is revealed to realize this would be a really stupid idea), but a canny party can reuse it, and might rediscover the exact same one, miles and miles away, if they impress the hosts enough and might enjoy it as a recurring encounter! It’s a fun encounter for nature-based characters to show off their wilderness smarts, and can be great if you’ve got a bard/dancer/storyteller in the party too once they realize what’s going on and that there’s an audience that would love to see or hear them perform. Use it to introduce a nature spirit NPC if needed, if you want to reward exceptional play, you can have an exceptional performance rewarded with a simple wooden flute as a parting gift (requiring no further obligation) that can summon the campsite once in any verdant wilderness setting but also acts as a sign of a respectful traveler to wilderness spirits. In future, PCs might be a little more respectful of their surroundings and the bounty of the natural world. Or find a sense of wonder in the magical, smaller spirits of nature being both capricious and generous in equal measure. Or they might just be a bit more cynical :D",
"As you progress along the road you see a small dot, quickly descending from the sky. As it falls the sun glints on metallic surfaces and you quickly realize that it is a dragon plummeting to the ground. With a resounding crash it impacts and as you draw near the crater you see a humanoid shape lying there with no trace of the dragon's body. The humanoid sits up and looks at you, speaking up in a shaky voice: 'Holy shit. I think I just saw a dragon.'",
"An ancient roadside ruin has two jaguar statues that preside over its entrance. If you camp nearby, the Jaguars animate in the middle of the night and attack.",
"A succubus is working in the kitchen of a pub, using her magic through the food she cooks to ensnare the tavern owner and the patrons.",
"The party turns a corner and finds a powerful enemy monologuing an evil speech dramatically to a baby as they literally steal candy from a baby.",
"While traveling through the countryside you pass the ruins of an old cottage. The walls have crumbled and the roof is gone. Stones are strewn about and overgrown with vegetation. Oddly though, there is a door standing in its frame, a rusty key in the lock.",
"You're in town and there is a weird vacant lot in between businesses. Folks say that it's a bar that only shows up with the full moon and rumor has it that its run by werewolves.",
"You find a cave full of kobolds that are worshipping a dead wizard's Pseduodragon pet as a baby red dragon.",
"They find an old wizard tower, and it's only inhabitant is a simulacrum completely out of spell slots, whose creator died many years ago.",
"A dire bear/other local beast attacks the party unprovoked. When it drops to 0 HP, it turns into a confused human in a scruffy noble's outfit.",
"A pair of Dwarven twins are arguing in the middle of the street over whose beard is prettier.",
"Along a path where the mountain meets the sea stands ancient statues long eroded by the ages. After reaching town you notice a small figurine like the statues has made its way into your backpack. When asking the locals about the statues, they warn travelers to pass by swiftly, lest they gain the attention of the watchers.",
"A frail old lady with very bad eyesight asks the party to get her cat down from a tree. When she shows them the tree, it becomes clear that “Mittens” is actually a Boggle.",
"As the party move on down the trail, they are aware of large creatures moving along with them, stalking them, as they go to make camp or to move to a new area the party are ambushed by a mating pair of manticores, who are severely starved and will not accept anything less than fresh meat or death.",
"There's a decrepit farmhouse in the distance, and you can make out a few people fixing it up and tending the grounds. Getting closer reveals these workers are a few zombies and skeletons, who affix you with blank stares as you pass. This place has recently become the retirement home of a necromancer who's 'employed' a few bodies to fix up the place.",
"A body wearing an integral suit of armor the likes you've never seen suddenly fall from the sky. The armor is too damaged to be of any use, but you can hear confused voices shouting in an unknown language when you get close to the helmet.",
"A man approaches you on the road and says 'my lord I thought I had lost you...'",
"A drunken dwarf recounts his 100% true story of that time he saved the world by punching Asmodeus in the face. He insists it's true and will nonchalantly mention it every opportunity he gets.",
"The party runs into a Druid in the middle of the woods. She claims that there is a great disturbance in the forest and that she needs the party’s help fixing it. When the party agrees, they find them polymorphed into squirrels. Nearby, two squirrels are loudly arguing over a large nut.",
"As the party travels in a creepy part of the country (haunted forest, swamp, etc.) they begin to hear the frantic singing of birds. The chattering continues but fades out slowly as the birds quiet down. A crazy old man passes them on the road, chuckling to himself, “they didn’t git ‘im”. The secret is that the birds, starlings in particular, try to eat the souls of people as they die in this region. The rhythm of their calls follows the breathing of person about to die. If they miss the soul, they just peter out into silence. But if they catch the soul then they continue chattering louder and louder until it’s deafening, then they fly away north, still singing.",
"There is a small sack in the middle of the road ahead.",
"The maddened ox stuck in the traces of the wagon, and its Karen of an owner, turn out to be more trouble than the goblins were.",
"A cart is overturned at the side of the road, the trunks and charts within spilled across the road. Among the wreckage is the robed corpse of a man and a number of orcish body parts. Dozens of feet in the air above a strange rod hovers in defiance of gravity. Accompanying encounter: This is how I like to give parties an immovable rod. The robed man is a wizard, ambushed by orcs. He bailed using his rod and misty step to get high in the air when they attacked, then the orcs released the captive mimics in his cart and many were eaten. Eventually the poor wizard realized he was out of spell slots, lost his balance on the rod, and fell to his death. The mimics are still a threat, the remaining orcs are in the nearby woods and come running at any particularly loud sounds, and the rod is a good 50 feet or more in the air so the party need to find a way up there.",
"A gnome with a tremendously heavy accent warns the traveling party that on the path ahead they should be worried about a visit from 'despoders'. The more difficult it is to understand him the better. When the players inquire, he struggles to explain. 'Ye nu,' wiggles fingers nonspecifically 'Despoders. Wertch ut.' Upon arriving in the area that the gnome warned them about, the party is attacked by giant spiders of your choice. When the battered, triumphant party emerges from the dangerous woods, the gnome will meet them once more before teleporting away: 'Tsk,' shakes head and folds arms ' I sed abut despoders....didy heer? Nu.'",
"You meet a elderly, unarmed, and arguing couple in the road (what they are arguing about can be mundane or campaign specific) in late evening. They are friendly, offer to feed and sit with the party, but spend the whole time going over the same argument - and attempt to get the party to take sides. The two act odd, not engaging in conversation for more than a couple of minutes outside their argument, don't sleep, despite serving delicious food don't eat, ect. If a party member agree with just one of the couple, the other becomes extremely aggregated, eventually revealing that they are a ghost and attempts to possess that part member in a surprise round. Both become hostel after that. If the party resolved the argument (multiple high DC persuasion checks and solid RP arguments) the two become very serene, and then vanish in the night, leaving behind a treasure. If the party fails to resolve the argument, both become agitated, eventually re-enacting how they murdered each other and then become hostile ghosts with no surprise round.",
"A kobold named Dave that collects a ton of random trinkets and items happens to be passing through town, which is apparent with the constant ruckus his traveling wagon causes.",
"Illusory flames form letters in the air above your heads. To your left, you hear soft snickering, and a voice whispers 'Leave them alone, silly!' through bouts of laughter.",
"A kid wild magic sorcerer accidentally hurt one of his friends while playing, so now he's trying way too hard to be the bad guy because he thinks that's what he is now.",
"A Green Hag used her shape shifting to trick a local farmhand into falling for her, then revealed her true form break the poor boy's heart. Now, over a week later, the party has been called in to solve a problem: The Green Hag has become desperate to get rid of her fawning admirer after all her other measures have failed, and has resorted to hiring out. Band of Adventurers to solve the issue, by whatever means they see fit.",
"Cabin in the Woods without the horror but lots of creepy: They find the stereotypical cabin in the woods complete with a big animal head like a bear or wolf on the walls. It has enough bedding for everyone and it’s near dark. If they spend the night there they hear all kinds of noises, have doors open and close randomly, wolves howling in the distance and even scratching at their doors during the night. But they are not attacked just annoyed. Fey creature or poltergeist spirits is the cause but they might not ever find out unless they stay the whole night. If a fey spirit have all their clothes mended and a freshly cooked breakfast if of course they stay through the night.",
"You hear the jingle of bells as a cart comes around the bend. The Tortle driver offers quirky magic items for a prize if you can solve his riddle. (Low level magic items like a iron beard potion. +1 to AC but you have a big ZZ Top beard) An annoyed citizen is complaining that they cant sleep at night due to the horrendous yowling coming from the alley out back. You investigate to find that its a group of winged cats fighting over territory.",
"A cat is stuck on a slender tree branch high in the air, unable to get down. If the party helps it down, the cat will reveal itself to be a Druid who was wildshaped. He got out onto the branch in order to avoid a predator, but then couldn't climb down, and the branch couldn't support his human weight. He should offer some helpful advice about the road ahead.",
"Someone approaches a member of the party and asks to purchase a lock of their hair. If they are refused, they offer a somewhat higher amount, and if they are again refused, they are infuriated and leave. They will not say why they want the lock of hair if questioned.",
"An eagle lands in front of the party and drops a tube in front of them, watching them expectantly. The tube contains the message 'We gather atop the Blue Spire at the next new moon. Will you join?' The eagle appears to be awaiting a reply.",
"A half-orc child is carrying a sack, tightly tied closed. Inside, something is emitting a high-pitched whine and struggling. If the sack is opened, four stirges emerge and attack.",
"You spot a hot air balloon over the forested path. As you approach, you see what appears to be a traveling acrobatics troupe arguing with a group of orcs wearing the country's insignia. From what you can overhear, the orcs are a border patrol and are asking for identification or travel documents. Goblins hang from the balloon overhead with bows at the ready. The argument mounts and it looks like a fight is about to break out.",
"A group of Kobolds run a very posh bath house. However, groups keep falling asleep after a time in the water and 1 member of their party disappears. The Kobolds are taking these people as a sacrifice to their protector: a dragon underneath that imbues the waters with heat and magic.",
"Several meters ahead under the dimly lit canopy, a large deer with a lame gate paws at something on the ground. As the PC approaches, a large predator bounds towards the deer out of nowhere, attempting to lay claim before the party does. As the beast leaps into the air mid takedown, dozens of thin writhing tentacles erupt from small holes beneath the deer's matted fur, piercing and enveloping the would be attacker. The thin fleshy tendrils pulse and constrict the beast as the loud crunching of flesh and bone can be heard from the clearing. Should your terror betray your position, the 'deer's' unnatural misshapen face turns towards your direction.",
"You found a house whose roof is covered with vegetation (a tendriculous in disguise). An scared raptoran with a broken wing is trapped there. She is terrified of the tendriculous and running low on food and water.",
"Breaching the water’s surface like the grasping fingers of a colossal sea god is an arrangement of ancient stone monoliths, all curved toward the middle of the circle they have formed. In the center of this circle a pale light gleams just beneath the surface of the water.",
"An important political figure (Like a princess or a prince, for instance) is lost in the Feywild, the party encounters them by chance while doing something completely unrelated, not only that, but they don't want to leave.",
"You come across a middle-aged man collapsed in the road. His dog paws at his body and whines with concern. The scene is a trap, and a group of bandits lurks nearby waiting to strike while you're distracted. The man and his dog are also a bandit and a mastiff.",
"Walking down the cobblestone streets you come across a naked man on the street looking up at the balcony of an attached cottage wherein several items of clothing, shoes, and other personal items are being flung haphazardly out of the open doorway. The naked man is desperately attempting to gather the belongings while pleading in a desperate apologetic tone toward the balcony and open door.",
"As the party travels down a country road, a herd of cattle is driven frantically past them going the opposite way. A young dragon (could be anything) is chasing them. Generally I have the dragon separate a few cattle from the rest and kill them. When the party inevitably tries to intervene, the dragon takes off after a few rounds of combat and flies back to its den.",
"A young girl leaning over a well. From a distance, she appears to be pulling up water or playing some sort of game. Upon closer inspection, she is speaking to the well. After a time, a voice from the well replies. (fill in further as you see fit)",
"A small child approaches a member of the party and says 'I have a gift for you', pointing to his closed fist like they want to drop it in the PC's hand. If the PC offers their open hand, the child puts their fist on it, then opens it and with a terrifying, devilish smile, says 'You're it!' before running away. The PC notices a black mark on their palm. They are now cursed.",
"This vignette is meant for like an extdaplanar city or something: A rakhasa smoking a pipe idly chats with an Ifrit about the current market value of Human slaves.",
"You are traveling along a road when a strange sound from behind quickly approaches. Turning around to investigate you see a monopedal war forged hopping towards you at some speed. Arriving next to you it exclaims; ‘ Customers, make your selection’, revealing a display that lists a selection of spells.",
"A man walks down the road, mumbling to himself and looking completely disheveled. He looks like he's been walking for a long time. He ignore the PCs and if they approach, a pair of trolls emerge. They aren't looking to fight, but demand the PCs leave the man alone and will only turn violent if the PCs attempt to aid the man or take him away from the trolls. If asked what is wrong with that man or what he did, the trolls only reply 'He knows what he did, that's enough!'",
"The sun sets behind the party as they wander down the dusty road. As the last rays begin to fade, in the distance a singing can be heard. First faint, then growing into a choir, mournful ululations begin to echo through the darkening forest. Peering off the road into the gloom, flitting figures can be seen. They twirl and dance around inside a circle of large toadstools. On the mushrooms are perched a solemn choir of satyrs, and the dancers inside appear to be children of every kind.",
"Three goblins blocking a road with a plank of wood. They demand a toll of 'three'. What three you ask? The goblins just look at each other confused and reply '...three'. You can just simply drive around them since there's open fields besides them, but who would dare Rob these cute little goblins from their hard earned money? Getting that plank out into the road must've been really hard for them. They are just doing their job. (If they murderhobo them, they definitely worked for the BBEG all along. He hired them because he felt bad for them. The BBEG is now more empathetic than the 'heroes'. Fuck them.) Also: the base idea is stolen from some other comment in another thread some time ago can't find it anymore, but can't take credit for the whole thing.",
"Shark attack. Jumps up, bites whoever is most damaged, and then falls back down and disappears. Party has to figure out a way to stop it before their most vulnerable party member dies. In the water? Normal shark. Over land? Rock shark with burrowing instead of swimming. On a volcano? Lava shark, immune to fire damage. In an airship? Sharknado. Low level party? Baby shark, do doo do doo do do.",
"(Requires less knowledgable players) Party is warned by a local of the presence of a cat-toe-blee-pus along their route, proceeds to describe a ridiculous and surely fictional creature",
"An amiable satyr (secretly archfey) sits in a circle of standing stones. He will challenge the party to a friendly competition (small bets or for honor), challenges are decided by the party. Once concluded, the prank is revealed as a flash of light reveals an invisible message in Sylvan on one of the stones that read 'The Folly of Pride.' Only those who have lost an earnest competition can leave the standing stones.",
"On this misty afternoon/evening you walk back to town X, you see a cart coming your way. On the cart you can see a cloaked man, seemingly to be asleep, while his mule is slowly pulling the cart forward. The cart looks old and is squeaking a bit. (Make it clear that everything is looking old and poor) (Perception check) high and medium Medium; Two crates with supply's and a box with two sleeping chickens. It turns out that the two 'poles' are actually spears, upside down Some corn/weed leaves and a sack of flour or the like A sack of coin in the back of the cart, sized like merchants have High; you noticed that the person on the cart had at least one eye open when he approached you. A glimmering of a weapon, dagger or small sword perhaps On one of the boxes you can see the faded logo/name of ....",
"In the peaks if the mountains, the party comes across a vibrant thriving city. There are no farms around it, and the twin guards at the gate don't look particularly strong. As the party enters the city, it comes to life with market sellers, construction workers, tavern brawlers, revelers and blacksmiths, all of them like the guards. Pushing through the crowds, the party hears a crack, and looks up to see that a flat of stone bricks is falling into the crowd. Nobody notices or cares. Before the party can do anything, it has already squashed 5 ppl. All that remains is a large pile of snow. As the party moves up the large street, they find it leads to a particularly warm and welcoming palace. In the great hall, the find a decadent and vain looking wizard modeling another sculpture of himself, and his doppelganger is sculpting it. The doppelganger finishes his statue, and walks away, and the thrones wizard mutters something vain while the new simulacrum stars sculpting another with a pile of snow and a toenail. Have him give the party a vain and meaningless quest or something, idk. Any meta gamers will recognize as soon as they walk into town that a powerful wizard has created a simulacrum of himself, that made a simulacrum of him, and so on. They built a city, and may just go on until a disaster wipes them all away.",
"A one-legged elder needs help crossing a rope bridge so he can deliver a basket of bread to his family across the gap. He has trouble balancing on the bridge due to his use of a cane. Once on the other side the elder will thank the players with a loaf of bread and a few coins. Just before leaving he will mention that he now has to walk several miles more through the dangerous local woods.",
"The party happens upon a vicious argument between two farmers. Each claims that the other spied on them to find their family’s historic garden patch where they grow highly sought-after spell components. The herbs and other components are such good quality that this feud has turned to blows and could lead to blood. It turns out that neither of them followed the other. The farmers are both descended from the original owner of the hidden patch but hadn’t known.",
"A distraught traveler NPC that is actually a recently turned werewolf. If the party brings him along, it will trigger a werewolf attack at night.",
"Village elder needs special meat for making meat pie",
"As you are traveling along the road, the sickly smell of burning flesh fills your nostrils and you can see smoke you ahead. As you get closer, you can see the remains of a burned down village, burnt corpses and charred bones haphazardly strewn about the small community. Next to the road is a small, slightly bloodstained corn husk doll, slightly charred at the bottom. Oh it’s leg, there’s a small note that in [language of your choice] “From: Mother, To: Samantha, my most beloved and helpful daughter.",
"A hunter approaches the party asking for assistance in finding a monster that's been terrorizing the area. But when the party goes off with him, they find that he's the one they're looking for.",
"A silver dragon stuck in human form and bound to a place offers rest, food, and protection in return for news of the outside world and an offering from each player for her to add to her hoard, it can be anything but she prefers trinkets with a strong personal connection. She is old and wise and willing to hear the travelers' trouble and give advice in return for more information of the outside world.",
"As you enter the bay, the captain solemnly bids sails raised and anchor lowered. You may note a number of vessels similarly motionless in the waters around you. When questioned, he points to a peculiar flag on the silent, empty docks. 'There's been a murder, we just kind of... Have to wait a few days out here.' As night falls, you hear a strange, thunderous crackling, as of iron boots on cobblestones... (Spoiler: it's redcaps. I have a whole 'chapter' in mind for this, but there's a few different implications and threads in just the idea that this village has regular enough redcap appearances that they have a procedure for riding it out.)",
"A pair of farmers patch up a broken fence by the road’s edge.",
"Some force of the Nine Hells (devils, cultists, w/e) wants to kidnap the princess of the realm after having kidnapped several other maidens fair. It turns out they are binding the voice of the maidens to an church organ to power a ritual. Ends in a climatic battle in the church where the devil/cultist/we uses the organ to summon allies, cast spells, use lair actions what have you. And the party bard has to counter play on the organ to cancel the ritual",
"A poison merchant who may or may not be using poison gas to make the party hallucinate",
"Approaching the two figures standing motionless in the field, the party finds that the two half-elves are very clearly reanimated corpses. A human girl is found resting between the two, hidden in the tall grass. Her two sentinels were party members that lost their lives in a lich’s lair and she has been returning her deceased party to their hometowns for a proper burial.",
"The party encounters somebody lying by the side of the road with a stab wound--alive and conscious, but fading fast, with no rations, weapons, or equipment. They refuse to say what happened or why. If the party heals the victim and manages to convince them that they mean no harm, the victim will warn them that there are bandits on the road up ahead. (The victim used to be one of them, until they were stabbed in a loot dispute and left for dead by one of their 'friends'-- but obviously, they're reluctant to admit to this.) The party can easily go around the bandits if they wish... or they can ambush the ambushers and make the road a safer place. (The stab victim knows exactly how many bandits there are and what tactics they use, but it may take some work to pry that information out of them.)",
"The PCs come across a dead wizard who with their dying breath scribed a spell scroll of Speak With Dead using a ripped off piece of their robe and their own blood for ink.",
"The party is to retrieve something from a long abandoned library. Description as you enter the west wing of the library (maybe a few light encounters before this room). You see the dust is heavy in the air and the old musty smell of books fills your nose, bodies lay strewn about the center walkway. Some skeletal forms still hold books from whatever killed this town. Some of the bodies still have skin and viscera, indicating they died more recently. You hear movement from the darkness. It grunts then rushes toward you. This is an illusion (a good one) have the illusion charging but start initiative before it reaches the party. As they attack the thing have it react normally for the first round, round 2 the skeletons rise from the ground and advance on the party. Remember the illusion should keep missing as to not break the illusion. While the party destroys things conti6to evolve the illusion, the skeletons get hit by a fireball, they fall and rise the next round on fire. The big thing keeps regenerating ect.. The illusion it to tax the party resources, before the skeleton wizard reveals itself as one of the skeletons reading a book.",
"A madman is running around the streets of a large city shouting about the 'spiderman' who creeps into your room at night, singing a lullaby before feeding from you. He has two fang marks on his neck.",
"'Just ahead of you on the road/path you notice a boat...in a tree.'",
"A pair of lowly workers becomes more contemplative as they drink as opposed to being rowdier.",
"You happen upon a castle owned by an evil Wizard employing a legion of goblins/gnomes for nefarious deeds. The goblins have all gone on strike demanding better working conditions. Optional: Wizard wears a big red hat and robe",
"You encounter a retired adventure who is living in the woods with his wife and kids. He lives in a small wooden house and enjoys growing pumpkins and other kinds of squash. He is a level 7 monk and will offer the party a meal if they help him pick the squash in his garden.",
"A ragged young woman runs through the woods, clearly terrified. She tells the party that she is being chased by a horrible monster. Just a few moments later, two hags leap from the woods. The woman, now on the opposite side of the party, is revealed to be a hag herself, and the coven attacks the party.",
"An empty cart is turned on it’s side by the road, as you get closer you hear a high-pitched war cry and small stones come flying over the cart. You find that this is a group of orphans living in the woods.",
"A wagon wheel breaks off of a cart and begins rolling fast down the inclined street. Screams and shouts erupt as people dodge out of the way of the erratic projectile before it crashes through a glassblower's window, shattering it and many things inside.",
"Two men are haggling loudly at a market stall over the price of pork belly. The butcher has his cleaver in hand waiving it around. Before the guards are called one of the men's wife comes out screaming at them both. They hang their heads and apologize. The man pays and leaves.",
"A team of men are working on felling a dead tree in town while trying not to hit any buildings with the falling branches. Two guards are keeping people from getting too close to the danger.",
"Horror: the town is alive and bustling but suddenly all human chatter stops. Everyone slowly turns to look at the party/player before immediately going back to their business with no recollection of what just happened.",
"Horror: a thief is being read his last rites on the executioners block. A line of cripples, lepers, and syphilitic people stand in a line nearby. As the executioner hacks the man's head off the line of sick people take turns holding out their cups, taking their sanguine blood hot from the stump and drinking it down greedily. The last one in line even goes so far as to get on the platform and tilt the man's body to get the last bit out. Nobody in town seems to mind. (What’s messed up is this was a legit thing in Europe. The last recorded instance of this was I think late 1800s Germany. They believed in corpse magic and that the blood of a particularly evil, executed person would cure some diseases.)",
"An old lady is struggling to plant flowers because she can't push her hand spade into the dry earth outside her house. Anyone who offers to help her gets a free pastry and a cheek pinch."


]
