var worldFeature = [
    "The party sees a giant stone monument of old dwarvish origins, huge boulders are set up to create a humanoid figure. Its species is uncertain.",
    "While driving past an old farm house the party sees a horse mating with a cow, while driving on more and more horses with horns and udders are seen.",
    "While driving past an old farm house, the party sees a farmer next to a minatoress in a beautiful dress, they seem to have some type of ceremony.",
    "A dwarf from the north carrying a bucket on his back walks with you for (1d4) days, every evening he makes a beautiful meal for you and tell you stories from his homeland. (the party only loses half their rations these nights)",
    "A tiny turtle, with the word Tizian written on its shell, is seen walking on the side of the road a strange aura looms around it. He may heal (1d8+5)hp to anyone who holds him.",
    "You drive past a huge mansion, you can see several children running around, a half elf with a noble look and a wise looking dwarf waves happily at you from the porch. It restores your hopes for the future, a happy ending is always possible, even in a world like this.",
    "You see a two young women training in the forest, one seems to be a 14 year old fighter in an impressive red armour she keeps referring to herself as the Immith the arena champion, the other is an aasimar monk with beautiful silver hair. They duel furiously, the sight of which inspires you to train harder.",
    "You travel alongside a big mountain, one of you comments that it looks like a giant petrified troll. Not everyone in the party can see it, though.",
    "You travel past a small town, they seem to be celebrating a harvesting festival. Any player can pay 5 copper to join one of the many games and earn a prize (roll for one trinket).",
    "Nothing interesting was seen today, but at least the weather was nice.",
    "Late in the evening the party meets a charismatic tiefling women who introduce herself as the magnificent Frieda Kohl she carries a lot of instruments with her and for 1 gold each she’ll play them a song. When paid all her instruments magically start playing a beautiful song, the party is now motivated to keep going without sleep, getting an extra days worth of travels.",
    "The party finds corpses of a group of bandits, on top of the leader sits a black cat cleaning himself, he can be heard mumbling with a scottish accent. The cat gives you 5 silver each to forget what you saw and move on and vanishes.",
    "You see a 10 foot tall scarecrow, with two heads, a long cape and an ugly face. For a second you thought it moved, must have been your imagination.",
    "Out in a field you drove by you saw a living scarecrow shaped as a bird teaching a young farm boy martial arts, there’s also a dwarf walking around the field picking up rocks and then writing something down in his notebook. There’s probably a great story behind this.",
    "As it’s getting late you stop to sleep in a forest, that night you have a horrible dream about large, hairy, green creatures running around while making strange clicking noises. the dream ends with the creatures sprouting wings and flying of into the night. the next morning you notice the forest seems to have disappeared.",
    "A large rock is set next to the road, it has the names of many travellers carved into it, as you touch it your name is magically carved into the rock. Nothing else seems to happen.",
    "Along the road there seems to be strewn several different ball gowns, there seem to be one for each of the male party members in fitting sizes.",
    "You find a tiny altar dedicated to Pelor close to the road, whenever anyone prays to Pelor close to the altar it lights up.",
    "You see a fantastic oasis not too far off the road, as you get closer it disappears, must have been a mirage.",
    "Nothing much happened, it rains a lot.",
    "You find a book with your name on it as you open the first page you see a list of chapters named after your life achievements, the last three chapters are called the The Hero's Reward, A Dark Descent and A GoreyGory Demise. That night while no one is watching you burn the book.",
    "While traversing the mountains you see a bunch of goats walking 90 degrees up the mountain. They don’t seem to be worried by the heights.",
    "A minotaur challenges your strongest char to arm wrestle, roll a strength check (17 or higher) the winner gets 2 gold.",
    "You hear the flap of gargantuan wings and see an ancient red dragon flying in the distance disappearing behind a snow covered mountain.",
    "You see a dog with an empty toilet paper roll taped to it's head… Erh I mean, you see a gracious unicorn, one of the world's most beautiful creatures.",
    "A passing traveler tells you about the magnificent hank, gentlemen thief and master of disguise, he hands you a business card when he leaves with the name hank on it.",
    "You see 7 dwarfs walking to the mountains with pickaxes while singing a catchy tune.",
    "A tall man with a tattoo covered face walks with you for (1d4) days, he introduces himself as Mountain Leaper every evening he’ll prepare a meal for the party while telling them stories about his adventure. (the party lose no rations these nights)",
    "You see a bony and frail lone wolf wander roughly 50 yards from your party. It notices you and keeps a close eye on your movements. The eyes of the wolf glow red, it follows you for three miles then mysteriously disappear.",
    "Nothing much happened, it snowed a lot.",
    "You spot a small, cozy looking cottage on the hillside as your party walks on the trail. There is smoke rising from the chimney and there is a soft glow in the windows. However, as you approach there is a strange stench in the air.",
    "The huge shadow of an eagle falls over you and your travelling companions, follows you for a few seconds, and then speeds off to the North. Looking up you're dazzled by the sun, and can't tell if it's an eagle flying close to the sun and casting a huge shadow, or a Roc out hunting.",
    "A column of slightly-larger-than-usual ants is marching down the road side, carrying scraps of paper as other ants might carry bits of leaf. On inspection, it looks like each ant is carrying a single word cut out of a book, but you can't make sense of any of it or find the book.",
    "A single, giant-sized mitten hangs from a snowbound pine branch off the side of the road. A family of mice seem to be living in it now.",
    "There suddenly appears what is unmistakably a 'Flail Snail' trail on the road, but it vanishes again after a hundred meters or so, with no sign of the snail.",
    "A large rabbit with pigeon wings and tiny antlers emerges from a bush, sees you, then runs off into the forest",
    "Someone has hung lanterns through this stretch of the forest trail. At night they light up with colourful elemental light. Every so often, you think you can see a lantern far off in the forest, away from the trail. Probably a trick of your eyes.",
    "The forest which was wild at the start of your journey, has been cleared of all trees except for birch [willow, maple, whatever], and there are no leaves on the ground . You don't see any stumps. Nature check (10 or better) and you see that many patches of the earth have been filled in with fresh soil. Careful observation reveals that this patch of the forest trail deviates slightly from your map, but recombines with the expected trail when the birch forest ends.",
    "The trail has begun to run alongside a low, calm creek with flat stones at the bottom. The water is only about calf-high. Walking in the water is soothing and invigorating. However every so often the creek bed is marred with deep (20+ yard) stone holes, perfectly circular.",
    "Nothing much happened, the weather was hot and damp.",
    "You notice the whole world is actually a giant computer, with every person, animal, monster, and discreet action acting to compute, you decide to lay off the bottle for a while.(see hitchhiker'shitchhikers guide to the galaxy)",
    "The path climbs up a steep cliffside, only wide enough for single file travel. The air is dry and hot. Off the side of the cliff you can see a small village worth of gnomes are holding a forest fire at bay. They seem to have the situation under control.",
    "Someone has put down mile markers along the trail, big slabs of local stone with carefully carved dwarven numbers. They are not evenly spaced though, and don't seem to accurately reflect distance at all.",
    "A small clearing is filled with tents and campfires, with a wide array of folk making camp. The tents look like they have been there a while, all covered in leaf litter and debris. The campfires look to be well burned into the earth. Some of the campers are discussing the best location for a more permanent lodge.",
    "A fox is resting on top of a sunny rock. The trail splits in two to go around the rock and then recombines on the other side.",
    "You begin seeing signs and fliers posted in many different languages, Geoff's Fireworks and Inn, 5 miles straight ahead! and You won't want to miss out on Geoff's continental breakfast and fireworks display! No matter how far you travel, the signs promise it is only 5 miles ahead.",
    "It's late at night and not to far off the main road in the densely packed forest area you can hear sounds of laughter, the roar of a welcoming fire and its bright light and the smells of a home cooked meal. It somewhat reminds you of your own ragtag group when you rest up after a particularly hard day on the road. As you move on down the road you see this image of serenity flicks in and out of existence with every tree that you pass. You can see staring at all of you is one of the people who is around the fire but facing the road you're on. It seems to be a half-elf woman with ashen grey skin and moonlight colored hair and behind her is a large wagon that reads Caravan of Misfits. Just before you pass the final tree she gives a small nod of respect to your group. You share drinks that night, and you feel motivated to keep fighting for this world and the people in it.",
    "As the party crests a large hill, the forest thins to reveal the grassland. Endless green hills bump out of the landscape. Past the miles of gentle prairie lies an impressive mountain range, so tall it splits the clouds that flow past it. As a result, long strips of cloud stretch over the landscape (perception roll to notice subtle details of vegetation, such as wildflowers and foods?)",
    "Nothing much happened, but there was a big storm lasting the whole journey.",
    "While passing a field full of cows what seems to be a big flying greataxe flies down to the ground, a hatch on the underside opens throwing and a very confused cow is thrown back on the ground. The greataxe then flies off.",
    "A small rain cloud forms in the distance, and moves towards the party, as it begins to rain on the group, it seems the direction of the raincloud changes, and begins to follow the group. The raincloud is only about 20 feet across, and the party can tell that it is only raining in their direct vicinity. When the group approaches their destination, the cloud dissipates.",
    "You see a large brown sphere, in front of it is a plaque reading: World's largest ball of dung You've seen bigger.",
    "A male tiefling, hidden under a cloak, walks along the path you are on, trying to be inconspicuous. If asked, he reveals himself to a be merchant selling jars of his highly coveted dehydrated water. Just add water and you’ll have a jar of water in no time. (ie. a charlatan selling empty glass jars for a huge mark-up). A DC 10 Arcana or investigation check confirms it is just a normal glass jar with no special properties.",
    "You come across a Building which appears to be a warehouse. behind it there lies a huge dragon skeleton. A sign hangs in front of the building Pronouncing it as Ye Olde Dragon Corpse Shoppe",
    "During your sleep, you start to hear light rustling around your campsite, with nothing to be seen. As morning comes by, you wake up surrounded by a perfect circle made of stones",
    "You see a man with a strange hat, waving at the party up ahead the road.when you reach his location, there is only a pile of bones, and you hear a faint laughter, coming from the nearby forest.",
    "Snow starts to fall out of nowhere. You see one snowflake that didn’t melt in your arm and looking closely, notice it’s shaped like a humanoid",
    "Cicadas. You definitely notice the sound of Cicadas in the distance. After what feels like even more miles of journeying, the sound is almost upon you. The forest is alive with activity. Deer cross your path in a panic, bears are running to the river to drown themselves. As you pass through the Cicada forest, you wonder what god created such a horrible creature. As the light slowly wane, the sounds of the Cicadas remain, ever present in this forest. (Do you want to rest, or risk exhaustion to get through the forest?)",
    "Nothing much happened, you saw a rainbow though.",
    "As you are walking through the forest, the light grows dim, the sap on the tree's starts to glow, and the air starts to smell like your favorite food.",
    "The party sees an elderly blind woman, named Macha, walking along the road with her seeing-eye (blink) dog, Enyo. She is friendly and her dog is friendly as long as Macha is treated well. She will travel along the road with the party for 1d4 days and may offer support if the party offers to let her join them at their fire and provide a meal. Macha is an innate spellcaster and can cast each of the following spells once per day: Identify, Locate Object, Locate Creature, Legend Lore, and Augury. If combat breaks out, Macha will immediately leave the area with her dog. It is up to the DM how she does so, but in my game this NPC can cast any Divination spells at any time (Macha is a spirit)",
    "A creature charges into camp, stomps out the fire crying out Take that you dweebs! He then runs out into the darkness while laughing hysterically and repeatedly saying Good one, Brad to itself.",
    "A young female bard is playing on a lute off the road, she isn't paying attention to any of you.",
    "You see a squirrel on a tree branch. Make them roll Perception (dice 12). If they succeed, they see that it's holding an acorn with a huge, happy smile.",
    "A mermaid in a river/lake, sitting on a rock and singing beautifully. (Twist: she's trash talking the group in merfolk-language.)",
    "A blood-caked altar. Both the altar and the blood is old and you can see wax remains on the side.",
    "There’s a small stage in front of a field filled with women of all races, on the stage there seems to be a flamboyant curly haired bard in a TIGHT blue bodysuit with a red star on it next to him there’s a man dressed in black his eyes shine with both an all enveloping hate and an uncontrollable lust for blood. They seem to be singing a love ballad about long journeys and epic battles for a princesses Peppermint creams. The entire party must do a will check (dice 20) or be temporarily in love with the bard, leading to a bunch of awkward and new feelings for the rest of the travel.",
    "Nothing much happened, the sky is cloudy.",
    "You dream of an endless castle in the Feywild where an ashen skinned Eladrin asks you to help her destroy the corruption festering inside. After living through nightmarish encounters, and tricks that your mind can barely bend around, you wake sweating, with a name inscribed as a searing enigma into your memory Lannawnshee. Your restless sleep gives you a level of Exhaustion the next day.",
    "You turn a corner in the path and in front you is a wagon seemingly filled to the brim with various types of cheeses. Asleep in the dirt next to it is a large man. In between snores you hear him mutter various names of different types of cheeses, which you can only assume are the types in the cart.",
    "A lightning bolt strikes the path in front of the party, deafening them. After their daze has faded, they examine the spot only to find a large green gemstone embedded in the ground. It appears to be flawless, but as one of the players touch the gem, a spark arcs between it and their hand.",
    "A large swath of the road the party is travelling on has been lined on either end with long, wooden stakes driven into the ground. It is unclear why these stakes have been +driven into the path, as they are not connected and wide enough for anyone to walk through. The party cannot seem to remove or damage the stakes in any way, and the last stake is not yet driven into the ground. The party can choose to place this new stake, should they wish. On closer inspection, each statestake has names carved into them, presumably previous travellers.",
    "As you wind your way through the forest, a trail of breadcrumbs bisects the path. You can smell gingerbread faintly on the wind.",
    "The forest trail seems to never end, and time seems to draw on. As the sun begins to set in front of the party, it also begins rising behind them. They lose a night'snights worth of rest, but can still choose to make camp.",
    "A downcast Kenku walks alongside the road with you. Its black eyes are full of sadness. Unable to speak for itself, it’s only able to mimic back to you the yells and abuse it has suffered in nearby human villages. If offered the chance and the materials to do so, it eagerly makes a copy of anything you give it.",
    "As you camp in the mountain pass you hear thunder, but it’s not raining, and the stars are out. Once outside the firelight of your camp, you can see two giants down in the valley below hurling boulders at each other for fun. The thunder is actually the sound of a boulders smashing on a giants heads.",
    "A group of Kenku children are playing in the field beside you. They are making elaborate battle sounds using their mimicry as they do so. This may lead the party to think they’re being attacked.",
    "Nothing much happened, it was really windy outside.",
    "You see a group of nomads travelling in the distance, but they’re travelling steadily forward and you’re unable to reach them. A perception check might allow you to find their camp and barter with them in the future.",
    "You see a huge blue box, when you turn away you hear a strange sound and now the box seems to be gone. You sigh in relief, it wasn’t much to look at anyways.",
    "Camping out in a flowery meadow, you awaken at midnight. The full moon has risen behind the hill nearby, silhouetting half a dozen bears as they dance around a stone circle.",
    "The players pass under a man made arch of stone carved with intricate symbols in a forgotten language. As they pass, they feel a ripple through their body and find that when one of them goes to tell another of the feeling, they can no longer speak. Their surroundings are eerily quiet.",
    "Travelling down the road, minding your own business, you meet a man with seven wives. Each wife had seven sacks. Each sack had seven cats. Each cat had seven kittens. It’s weird.",
    "A tall man staggers towards you, wearing a long, hooded cloak. He looks drunk. His boots are far too small, and he’s wobbling from left to right as he walks. As he draws level with you, he falls over, revealing that he’s actually three goblins on each others shoulders. The goblins run screaming into the woods.",
    "Although you’re many, many miles from the sea, or even the nearest lake, you spot a Halfling building a large, single-sailed ship in the middle of a field. He seems happy enough as he works away.",
    "You look up as you walk, searching for anything to break the monotony of the endless fields. Two clouds glide towards each other, which is weird, as the wind should only be going one way. The one to the West is huge, and gliding East. It looks like a massive, horned dragon. To the East, and gliding West, there’s a cloud which looks like a smaller dragon with five heads. Both are destroyed when they collide.",
    "You encounter a heavily armored man walking with a cane, as you approach him he offers you the armor if you can best him in single combat, and grant him a death worthy of a warrior.",
    "Nothing much happened, but although there’s not a cloud to be seen and the sun is bright you are filled with a feeling of dread. Something is coming!",
    "As you walk through the forest trail a pair of bare feet make their way up the road towards you. As it gets a little nearer, you realize it’s a nude man in an invisibility cloak. You realize this because the cloak snags on a tree branch, and the man walks on a few paces without it, totally naked.",
    "Minutes after lighting your own campfire, bonfires flicker on across the hillside to the East. Oddly coloured smoke floats up from each fire, and the wind brings the smells of a dozen different reagents. These must be the potion moonshiners you’ve heard about.",
    "A small lodge sits in a clearing. It seems warm and inviting, the sound of smooth jazz flows out of a window left slightly ajar.",
    "The party approaches a clearing surrounded by various types of deciduous trees. Each of the trees has a bucket attached to a tap. The buckets are all filled to the brim with sap and in the distance you can hear a faint tune being whistled into the fall air.",
    "A woman rushes toward you in a frantic state. She is almost incoherent, but you can discern between sobs that her three year old has climbed into a gorilla disclosure in a nearby zoo. She asks for the parties help. By the time they get there, the gorilla has dragged the child around, killing it. She asks you to shoot the beast to death.",
    "An old man is sitting with his walking stick beside him, he starts into a tale about how a short blue haired girl became a God and gave her life so that her love can rebuild the world anew with somebody else he loved. He then mutters on insane. If the characters point out his seeming insanity to him, he replies with please, don’t remind me of my insanity yet, let me enjoy it for a little while longer and then goes back to linguistic static.",
    "A magical Inn seemingly appears out of nowhere and in the most odd place. The inn is well tended, stocked and provisioned. On top of everything the climate inside is perfectly comfortable. The wine is cold and a feast is laid out on a large table that dominates the Inn. Beds upstairs are clean, the pillows cold (on both sides!) and every need you can imagine is provided for (in an Inn sense). The food is top quality along with much of everything else. However. It is mysteriously empty. No one tends the Inn nor does it seem that anyone has disturbed it.",
    "If anyone spends the evening in the inn they wake to it cold and the life of the inn itself dispersed. The fire pits are cold. The food gone and the wine goblets empty. No ill effects are suffered from anything partake inside.",   "An abandoned cartwheel",
    "A holy man meditating at a roadside shrine",
    "A newly constructed traveler’s waystation",
    "A caravan of gypsies waiting for a birth",
    "A statue of a two-headed goat",
    "A covered well",
    "A squashed hedgehog",
    "A hermit’s cave",
    "A teahouse",
    "An abandoned barn",
    "The remnants of a campfire",
    "A dead sheep",
    "An old road, now overgrown and abandoned",
    "A footpath leading away",
    "A tumbled-down rock wall",
    "A tree adorned in prayer flags",
    "An oak tree split by lightning",
    "The ruins of a croft",
    "A standing stone",
    "A tiny roadside tavern",
    "An old blind woman begging for alms",
    "A coin",
    "Signs of a fight",
    "A totem depicting foxes and wolves chasing owls",
    "A boarded-up mineshaft",
    "An overgrown graveyard",
    "A broken, rusty halberd",
    "A scarecrow",
    "Three dead foxes strung up in a tree",
    "A mangy old dog",
    "The carcass of a giant, picked clean by vultures",
    "An abandoned child",
    "A gallows with a dead victim",
    "A coaching inn",
    "The corpse of a criminal in a hanging cage",
    "A road repair gang",
    "A pile of flagstones waiting to be laid",
    "A milestone",
    "A huge footprint",
    "A tumbling waterfall cascades into a deep pond",
    "A bent willow tree provides shelter",
    "A ruined bridge carved with dancing angels",
    "A quaint wishing-well",
    "A limestone gorge filled with ancient trees",
    "A lone tree upon a moor",
    "Mighty stones have weathered into incredible shapes",
    "Carved millstones lie abandoned in a flower meadow",
    "A stone outcropping that looks like a dragon",
    "The ruins of a once-majestic manor house",
    "A crumbling hillside",
    "A farmed valley with lush grass",
    "The still waters of a pool reflect an ancient dolmen",
    "A natural tower of broken, weathered stone",
    "Sunlight suddenly strikes the purple heather",
    "The sun picks out the hillside in a blaze of color",
    "A ruined croft with the chimney still intact",
    "A crumbling gatepost leading to a ruined croft",
    "A cobbled track worn smooth with age",
    "A standing stone in a hollow",
    "Curious weathered stones tumble down the hillside",
    "An old ruined chapel wreathed in ivy",
    "A shallow cave with a moss-covered floor",
    "A stone trough filled with flowers, overlooking a lake",
    "An old stone bridge with a small religious shrine",
    "A cairn with a wide panorama of the countryside",
    "A weathered flagstone path leads to a rustic barn",
    "A ruined tower surrounded by heather",
    "Ancient trees gather on a small knoll",
    "A fine bridge over a cool swimming hole",
    "A stone circle in a forest clearing",
    "An empty old burial cairn on the edge of a hillside",
    "A forest clearing bathed in sunshine",
    "An abandoned house by a river",
    "A ruined mill surrounded by cascading waterfalls",
    "A mighty oak towers over the path",
    "A village pond with ducks and dragonflies",
    "A holly bush with a ruined house within",
    "A statue of a man with a cloak of flowers",
    "A meadow filled with buttercups",
    "An old graveyard at the foot of a cliff",
    "A flagged ford across a river",
    "An outcrop of rock that looks like an owl",
    "Three intertwined apple trees",
    "A curious rocky tor rising from a small copse of trees",
    "A pond clogged with watercress and lilies",
    "A green lane surrounded by ancient sycamore trees",
    "A natural seat under a cliff, draped with kudzu",
    "Bright red berries swing from the arch of a tree",
    "A hollow holds three graves, surrounded by ivy"
    ]

var worldWeather = [
    "Balmy: mild and pleasant weather",
    "Blizzard: a dense snowstorm",
    "Bluster: strong wind",
    "Breeze: light wind",
    "Calm: no wind",
    "Chill: unpleasantly cold",
    "Cool: moderately cold",
    "Cyclone: violent, destructive storm",
    "Damp: moisture in the air",
    "Deluge: sudden heavy rainfall",
    "Dew: condensation forming just above the ground",
    "Downpour: heavy rainfall",
    "Draft: current of air",
    "Drizzle: fine rain",
    "Drought: continuous dry weather",
    "Dust storm: severe windstorm lifting dust and sand",
    "Fair: pleasant weather",
    "Fog: thick mist or cloud",
    "Freezing rain: rain that freezes when it lands",
    "Frigid: intensely cold",
    "Frost: frozen dew",
    "Gale: strong wind",
    "Hail: pellets of frozen rain",
    "Haze: condensing ground vapor caused by heat",
    "Heat wave: prolonged period of warm weather",
    "Humid: warm, moist air",
    "Hurricane: windstorm moving around a central point",
    "Mild: moderately warm weather without rain",
    "Mist: water vapor in the air",
    "Monsoon: heavy, prolonged seasonal rain",
    "Muggy: damp, warm, oppressive weather",
    "Overcast: heavy cloud cover",
    "Pea soup: thick yellow fog",
    "Rain shower: short period of rainfall",
    "Rainfall: prolonged period of rain",
    "Sleet: ice pellets mixed with rain or snow",
    "Smog: smoky fog",
    "Snow flurry: short period of light snow",
    "Snowstorm: prolonged heavy snow",
    "Squall: sudden, localized storm",
    "Storm: violet wind and rain",
    "Sunny: bright, clear weather",
    "Temperate: without extremes of warm or cold",
    "Thunderstorm: storm with thunder and lightning",
    "Tornado: destructive, rotating windstorm",
    "Tropical storm: cyclonic storm from the tropics",
    "Typhoon: violent cyclonic storm",
    "Warm: moderately hot temperature",
    "Whirlwind: violent wind moving in a circular motion",
    "Whiteout: heavy snow, causing visibility problems",
    "Partially Cloudy - The clouds block the sun periodically, causing some shadows to be cast over the lands.",
    "Sunny Day - Roll a d6, 1 - The warm sun feels good on your skin, 2-3 - You become very sweaty (-1 on all strength rolls for six turns), 5-6 - You get a sunburn (-1 on all strength and charisma rolls for the rest of the day).",
    "Slight Breeze - The wind is refreshing, and your mood is increased. +1 to all charisma rolls for 1d10 turns.",
    "Very Windy - You have to push against the wind with nearly every step. -2 to all dexterity rolls for 1d10 turns.",
    "Light Drizzle - The soft rain makes you think about your past. +1 to all intelligence rolls for 1d10 turns.",
    "Tornado - Find shelter that can keep you safe from the destructive nature of the nearby tornado.",
    "Light snow - The snow calms you. Wisdom and charisma increase by 1 for 1d6 turns.",
    "Fog - It’s hard to see. -2 disadvantage in any action based roll.",
    "Icy Wind - A cold wind blows in from the north.",
    "Frosty Air - A very cold wind blows in from the far north, bringing hints of snow.",
    "Astral Disturbance - Something shifts in the Astral Plane. Nearby wildlife runs in fear. Trained animals are fearful, but do not flee. Nearby players feel a shift in something in the back of their minds.",
    "Arcane Radiance - The sky is lit up with a brilliant light that extends from horizon to horizon. It is awe-inspiring, but strangely calming.",
    "On the Hunt - The wolves are out hunting again. They probably won't attack, but don't expect to find any wildlife. They're all running.",
    "Essence of the Shadowfell - The area darkens for a split second. A disturbance occurred in the planes, bringing hints of necrotic energy and darkening the entire area for a 1d6+3 minutes. The area is now considered dimly lit instead of brightly lit, or total darkness instead of dim lighting.",
    "Foreboding Calm - The first warning of a storm. Hurry, before it hits.",
    "Fury of the Elements - A great storm hits, pouring with rain, crackling with lightning, and howling with wind. It demands attention and refuses to let anyone sleep.",
    "Hail - either small annoyances that disrupt concentration checks to a barrage of ice the size of fists that could knock out an orc. Either way, seek shelter",
    "Sunshower - A deluge of rain yet the sun shines in full force. Some say it's sign of the occurrence of marriage between magical creatures (or foxes) or that the devil is beating his wife in anger at how beautiful the day is. Some say its a moment of balance of the opposing forces in nature, others say its just one of those phenomenon. Up to DM which of these is true.",
    "Massive (tropical) rainstorm - The deluge is oppressive. The din of rainfall is the only thing you hear. Visibility is nil beyond a few feet. Beware of flash floods.",
    "Little fall of rain - You are caught in a light shower. For some people, this is an annoyance. Small cut to concentration and charisma in their surliness. Some people enjoy the rain and the sensation of water droplets on their bodies and get a boost to wisdom and charisma. Others don't mind but would really rather be somewhere dry.",
    "Silence in the forest - After hours of the non-stop sound of bird song and animals rustling in the plant life, the massive silence that follows is somehow more crushing. What would cause an entire forest of wildlife to not want to draw attention to themselves?",
    "A great migration - Ants blanket the forest floor in purposeful movement, a sea of red crabs march over a sleepy fishing town, mosquitos, thick as fog, all buzz in one direction, a crowd of lemmings run off a cliff and those that survive resume their marathon at the bottom. All riffs to the same song, a lot of animals going in one direction. A witnessed annual migration? Or something more sinister?",
    "Predatory desperation - Food has been scarce in this location lately, whether through over-hunting, adventurers' over-eagerness or disasters of a natural or magical sort. What matters though are there are going to be a lot of hungry animals and they might be insane enough to put you on the menu.",
    "Signal Flare! - a single comet of light climbs into the sky before exploding, filling the heavens with radiance. A poor soul looking for rescue? A signal of command undeciphered? A poorly thought out gnomish rocket launch? Or just swamp gas and will-o-the-wisps? Only one way to find out.",
    "Avian circles - A legion of birds of varying sizes and species, all flying in massive concentric circles in the sky, the biggest one probably kilometers wide. That can't be a good omen.",
    "Umibozu - On the high seas, there in the horizon, a colossal, shadowy humanoid specter looms. Do not speak it's name or draw it's attention, for it is known for spelling doom for ships.",
    "Cloud watcher's delight - Some strange looking clouds around this area. Almost as if they were shaped. Maybe they look like magic runes, seemingly carved out of clouds. Perhaps they spell instructions for the party or, depending on how 'well' the party usually takes advice, expletives tailored towards them written in plain text. Maybe they look like animals as though drawn by a child. And that one looks like two figures in-oh.... Let's hope there are no children around to see that.",
    "Fireworks Shower - The night sky is lit up with a series of brilliant coloured lights that last for a split second only. A celebration nearby? A trap? An arcane experiment gone wrong? Who knows? It's quite nice.",
    "Great Plague - A swarm of locusts, coming over the horizon, eating everything. This may last several days.",
    "Great Druid's Calm - The wild things are glad. A peaceful atmosphere reigns.",
    "Chaos Influx - A small entry from the Elemental Chaos. Puffs of smoke, small fires, water, wind, pebbles.",
    "Stampede! Roll 1D4 to have a stampede of; 1. Giant elephants, 2, Elephants, 3. Deer, 4. Rabbits run past the party.",
    "Rainbow - A pleasant rainbow shines, formed from a nearby rainshower.",
    "A Wild Friend is Born - The local wildlife and even plant-life seem to bow before this grand newborn. Is it a powerful elemental, or the next king of the jungle?",
    "Heatwave - The sun licks the earth with a sweltering power. Be sure to stay hydrated, and in the shade, or make a constitution roll to keep moving. If the roll is failed take 1d4 heat damage every 1d4 turns.",
    "Dust Storm - Blistering winds of sand blow in from the nearest desert. -2 Perception and -1 Dexterity.",
    "Meteor! - Roll 1d6; 1-2. A large celestial rock streaks across the sky, crashing into the land a ways off. 3-4. A massive stone comes crashing nearby, sending up a large amount of dust. Fires may start due to the residual heat. 5-6. The meteor is heading your way! Make a Dexterity roll; if failed, take 2d10 damage!",
    "Beautiful Blossoms - The local flowers are blooming! By breathing in the sweet and calming aroma restore 1d4 HP!",
    "Birds of the Forest - The local songbird population is in full song! Cheerful sounds of chirping and whistles from a variety of birds fill the air, providing a lovely background noise to travels. However, the birds sound lowers passive perception while in this neck of the woods by 1."
]

var worldClimate = [
    "Antarctic: southerly area of extreme cold",
    "Arctic: northerly area of intense cold",
    "Basin: tract of land drained by a river",
    "Beach: shoreline along a body of water",
    "Bog: wet ground made up of decayed vegetation",
    "Butte: isolated hill with steep sides",
    "Caldera: cauldron-like bowl caused by a volcano",
    "Canyon: deep gorge or ravine with steep sides",
    "Cave: small subterranean opening",
    "Cavern: large subterranean chamber",
    "Cliff: steep-sided rock formation",
    "Coast: tidal shore",
    "Crater lake: lake formed in crater of a volcano",
    "Desert: arid, barren land",
    "Dunes: hills of sand in deserts",
    "Farmland: agricultural land, often enclosed",
    "Fen: low marshy or flooded area of land",
    "Forest, coniferous: chiefly evergreen forest",
    "Forest, deciduous: forest of trees that shed leaves",
    "Glacier: slow-moving mass or river of ice",
    "Hills: landforms that rise above the surrounding land",
    "Icecap: permanent covering of thick ice",
    "Isthmus: narrow strip of land connecting two areas",
    "Jungle: land overgrown with vegetation",
    "Knoll: small natural hill",
    "Lake: large, inland body of water",
    "Limestone upland: exposed limestone outcrop on hill",
    "Meadow: land that periodically floods",
    "Mesa: elevated area of flat land",
    "Mire: swampy ground",
    "Moors: upland landmass usually covered in heather",
    "Mountain: prominent landmass of exposed rock",
    "Mountain, high: mountain with permanent glaciers",
    "Mountain pass: saddle point between mountains",
    "Ocean: large body of water",
    "Oxbow lake: U-shaped body of water",
    "Peninsula: point of land almost surrounded by water",
    "Plains: level tract of land",
    "Plateau: elevated tract of relatively flat land",
    "Ravine: small valley",
    "Ridge: a continuous elevated crest",
    "River: large watercourse",
    "Scree: broken rock fragments at a mountain’s base",
    "Stream: small watercourse",
    "Subterranean: below the surface, usually caverns",
    "Swamp: wet, spongy ground",
    "Tundra: vast, treeless region in arctic or antarctic area",
    "Valley: long depression or hollow between hills",
    "Volcanic: region with volcanic activity",
    "Wetlands: wet, soggy, seasonally waterlogged area"
]
